### ISSUE TITLE
How to prevent default on react-native

### ISSUE THREAD

**Issue by dbuarque** [oliviertassinari/react-swipeable-views#101]
Hi @oliviertassinari 

I have used your awesome module for while, now I am trying to integrate with the react experimental navigation but the swipe event from the navigation blocking the react-swipeable-views, I am not sure if the preventDefault can solve this problem, any idea how can I solve this?

**Comment by oliviertassinari** [comment]
Hi, thanks for the kind words.
I have never used the `experimental navigation`. I'm clueless here.

**Comment by nabn** [comment]
I think @dbuarque is talking about [NavigationExperimental](https://facebook.github.io/react-native/docs/navigation.html#navigationexperimental)

**Comment by oliviertassinari** [comment]
I'm closing the issue as I don't have the answer and that has been inactive for quite some time.
