### ISSUE TITLE
React Native: Are views rendered lazily?

### ISSUE THREAD

**Issue by vdrg** [oliviertassinari/react-swipeable-views#102]
Are they? We need to use ir for a large quantity of views.

Thanks!

**Comment by oliviertassinari** [comment]
Hi. No, the views are not lazy rendered.
But that responsability can be hanlded by the slides components. This what we are doing [here](https://www.doctolib.fr/cabinet-dentaire/conflans-sainte-honorine/cabinet-dentaire-de-conflans-chennevieres/pictures) (mobile phone).

**Comment by oliviertassinari** [comment]
How many views do you need to render? I think that my above solution can handle up to 50 views and still provide a good UX.

**Comment by vdrg** [comment]
We are going to use this for an e-reader, and the books can have hundreds of pages. I'll try to do it with the slides components, thanks!

**Comment by oliviertassinari** [comment]
I'm closing this issue in favor of https://github.com/oliviertassinari/react-swipeable-views/issues/22. Thanks for raising that point. That seems like a quite needed feature.
