### ISSUE TITLE
callBacks should also be called on componentWillReceiveProps

### ISSUE THREAD

**Issue by FalkNisius** [oliviertassinari/react-swipeable-views#103]
In the moment the callBacks are only called, on touch events. If the slide pos changed programmatical, with changing the index property from the render function of the parent components, then they would never be called. It would be fine to have these callBacks in the same way like in touch Events, to do some things after the new position is arrived especially onSwitching(index, 'end').

**Comment by oliviertassinari** [comment]
I don't get it. That's gonna break the single data flow pattern that makes React so nice to play with.
What's the issue that you are experiencing? Or even, better, what would be the use case? Don't we have better way to fix it?
