### ISSUE TITLE
Webpack build error right after install package via NPM

### ISSUE THREAD

**Issue by JisuPark** [oliviertassinari/react-swipeable-views#104]
First of all, thanks for the great packages.

I installed `react-swipeable-views` package via npm.
And I got error message from during webpack builds like belows.

```
ERROR in ./~/react-swipeable-views/lib/SwipeableViews.js
Module not found: Error: Can't resolve 'react-motion' in '/node_modules/react-swipeable-views/lib'
./~/react-swipeable-views/lib/SwipeableViews.js 19:19-42
```

If we have to not only installed this package but also `react-motion` package, we better fix `README.md` files.

AS-IS `npm install react-swipeable-views`
TO-BE `npm install react-swipeable-views react-motion`

If I missed sth, please tell me :)
Thanks!

**Comment by oliviertassinari** [comment]
Right, this package has a *peer dependency* on `react-motion`. Do you want to submit a PR to fix it? That would be great. Thanks!

**Comment by JisuPark** [comment]
Sure!
