### ISSUE TITLE
Keyboard Navigation?

### ISSUE THREAD

**Issue by oyeanuj** [oliviertassinari/react-swipeable-views#106]
Hi @oliviertassinari! While I know that this is intended mostly towards mobile use-cases, I was wondering if you plan to support keyboard navigation and ARIA attributes given that it works for browsers?

Thanks!

**Comment by oliviertassinari** [comment]
Hi,
I don't think that we should build the keyboard navigation in the core of the lib.
But we could do something like the `autoPlay` HOC using [react-event-listener](https://github.com/oliviertassinari/react-event-listener) 👍 .
Regarding the ARIA, I don't have any expertise on this field. What do you have in mind?
