### ISSUE TITLE
Feature : no animation on index change

### ISSUE THREAD

**Issue by jadus** [oliviertassinari/react-swipeable-views#108]
In my use case I'd like the view to change immediately (no animation) if I change the index prop. Would it be possible ?
Thanks

**Comment by oliviertassinari** [comment]
@jadus What platform are you targeting? It's kind of possible today depending on the platform.
I should make this more straightforward and simple.

**Comment by oliviertassinari** [comment]
@jadus What platform are you targeting? It's kind of possible today depending on the platform.
I should make this more straightforward and simple.

**Comment by oliviertassinari** [comment]
@jadus What platform are you targeting? It's kind of possible today depending on the platform.
I should make this more straightforward and simple.

**Comment by oliviertassinari** [comment]
@jadus What platform are you targeting? It's kind of possible today depending on the platform.
I should make this more straightforward and simple.

**Comment by jadus** [comment]
Thanks a lot !
