### ISSUE TITLE
Sync Multiple Rows

### ISSUE THREAD

**Issue by tleish** [oliviertassinari/react-swipeable-views#112]
I want to make a view with multiple rows.  Each row may differ in height from the previous row, but all items in the same row would be equal height.  If I scroll view A 50% down the page, I want to swype to view B, which should also be 50% down the page.  The reason for the matching height is when I swype from one view to the other, similar content blocks are visible.

I imagine I could create multiple rows, each row it's own swypable view.  Then when I swype one row, it moves all the other rows as well.  Is it possible to sync multiple rows like this?

**Comment by oliviertassinari** [comment]
Wow, your needs seems quite challenging.
The best solution I can think of is using one `<SwipeableViews />` and keeping adjacent slide scroll positions in sync.

**Comment by tleish** [comment]
How would you sync the views so they slide simultaneously, rather than when the slider completes.

**Comment by oliviertassinari** [comment]
Have you tried using the `onSwitching` property?

**Comment by oliviertassinari** [comment]
I'm closing the issue for inactivity. I believe `onSwitching` is what you are looking for.

**Comment by MoeSauber** [comment]
I was looking for the exact same thing. WIll check out `onSwitching`!
