### ISSUE TITLE
embedding touch elements within a swipeable view

### ISSUE THREAD

**Issue by funkyeah** [oliviertassinari/react-swipeable-views#114]
I've implemented a Swipeable view and nested a [Checkbox](https://github.com/react-native-material-design/react-native-material-design/blob/master/lib/Checkbox.js) from [React Native Material Design](https://github.com/react-native-material-design/react-native-material-design) inside of one of the slides. 

It seems though that the swipe gesture takes precedence over the tap gesture for the checkbox... the symption being that unless I very careful tap the button without any left or right movement, it will start the slide motion instead of the checking the box. 

Any ideas on how you might correct this or where to start debugging?

**Comment by funkyeah** [comment]
Adding some notes:

Panresponder initialization in [index.native.animated.js](https://github.com/oliviertassinari/react-swipeable-views/blob/master/src/index.native.animated.js#L121)

Similar [issue](https://github.com/facebook/react-native/issues/3082) reported in the react-native repo... reportedly about iPhone6 and 6s 3D touch so may be unrelated. 

One fix is to increase the threshold for the [onMoveShouldSetPanResponderCapture ](https://github.com/oliviertassinari/react-swipeable-views/blob/master/src/index.native.animated.js#L123) parameter

Currently it's set so that if the x movement is greater than the y movement then swipeableViews claims the responder:

```
return Math.abs(gestureState.dx) > Math.abs(gestureState.dy);
```

My theory is that its really hard to consistently tap a button or checkbox with no x movement so tweaking this code may help. Maybe:

```
return Math.abs(gestureState.dx) > Math.abs(gestureState.dy) && Math.abs(gestureState.dx) > threshold;
```
Where threshold is either passed or some value that works experimentally.

**Comment by funkyeah** [comment]
My description of the issue above appears to be correct. 

I made the threshold = 3 and the nested checkboxes I have can be tapped without issue. With a threshold of 3 I also don't notice any interference with the swipe gesture itself.

@oliviertassinari  Would you accept a pull request that modifies this? if so how do you think it should be modified? a hard-coded value or an additional API option?

**Comment by funkyeah** [comment]
@oliviertassinari I forget... do you get a notification if I don't @ mention you? If so apologies for pestering.

**Comment by oliviertassinari** [comment]
@funkyeah I do. I'm investigating on your issue. I'm looking at https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabViewPanResponder.js at this moment.

**Comment by funkyeah** [comment]
Yeah, sorry I realized it was a dumb question as soon as I posted it... so promptly deleted.

**Comment by oliviertassinari** [comment]
@funkyeah Would the following code do the trick? If so, we could also update the browser version.
```js
return Math.abs(gestureState.dx) > Math.abs(gestureState.dy * 3);
```

**Comment by funkyeah** [comment]
It certainly might work. I can try tonight and let you know.

**Comment by funkyeah** [comment]
@oliviertassinari I tried:
```
return Math.abs(gestureState.dx) > Math.abs(gestureState.dy) * 3;
```
and it recognized the tap event more consistently than existing code does but was still fairly error prone. I would say when casually tapping (e.g. when not specifically focusing on tapping without moving in the x and y direction) I had a 30% success rate with the original code. The change above got it to 50-50.

If I change it to:
```
    return (
      (Math.abs(gestureState.dx) > Math.abs(gestureState.dy * 3)) &&
      (Math.abs(gestureState.vx) > Math.abs(gestureState.vy * 3))
    );
```

It works closer to 3/4 or 4/5ths of the time.

Honestly the best is still:
```
return Math.abs(gestureState.dx) > Math.abs(gestureState.dy) && Math.abs(gestureState.dx) > 3;
```
The tap is recognized correctly pretty much every time even with fairly sloppy taps, and I'm unable to perceive any negative impacts to the swipe gesture recognition.

If I set it to `>2` it works a little better than the `vx` / `vy` route but not as good as `>3`.

I also tried to find where on the upper end it starts to impact the swipe. At `>8` you can just start to notice it if you move your finger really slow and are really paying attention. If you are moving your finger at a normal speed though it wouldn't be noticeable. At normal swipe speeds I couldn't really tell until somewhere around `>20` and that is only when I was specifically looking for it. I don't think a normal user would notice until well beyond that.

**Comment by oliviertassinari** [comment]
> Honestly the best is still:

That's sounds good to me. Would you mind doing a PR for this?
I will implement a similar logic for the browser. It's going to be a bit more work.

**Comment by funkyeah** [comment]
Submitted a pull request and attached the note below to it, but putting it here for reference.

Before accepting this you may want to try it. Setting it to 3 is basically the minimum it can be, but a larger value (up to 8) might work better. Having it be a settable parameter is also an option.

I looked at the Gmail app and it appears to have some sort of threshold for its swiping functionality too. As far as I could guage it seemed to be fairly large. The Inbox gmail app it seemed smaller.
