### ISSUE TITLE
Reset the component state after a re-render, React-Native

### ISSUE THREAD

**Issue by pnakibar** [oliviertassinari/react-swipeable-views#122]
I'm trying to achieve an swipeable-view with an filter to show only the information I want, and after an re-render the components index stays the same.

In the situation, I have two possible arrays of data, one having 2 views and the other having 3 views, and one button to toggle between them, but since after an re-render the react-swipeable-views doesn't re-render and resets the index to 0. If I'm in the 3rd view, and I toggle the array, it shows me an black screen with no way to change swipe, but if I'm in the 2nd view, and toggle the array, it shows perfectly.

I'm using the component in an React-Native environment.

**Comment by oliviertassinari** [comment]
@pnakibar You raised a good point. The `index` shouldn't go beyond his bounds.
I thnk that it should be handled at the user level, still, it would be good to have a warning about it, so you know that it's wrong when working in the dev environment.

**Comment by pnakibar** [comment]
I got an workaround around this:
```javascript
// ...
  <SwipeableViews
          index={this.state.page}
          onChangeIndex={(index) => this.setState({ page: index })}
  >
  // ...
  </ SwipeableViews>
// ...
```

And then, whenever I need to _reset_ the view, I call _this.setState({ page: 0 })_ and it's fine!

**Comment by oliviertassinari** [comment]
@pnakibar Yeah, that's exactly how I would have solve it 👍.
