### ISSUE TITLE
[style] Issue with fix positionning

### ISSUE THREAD

**Issue by zhouyu11** [oliviertassinari/react-swipeable-views#124]
For the container style , use translate3d transform to switch the different slide views, but transform will  create a new local coordinate system, so position fixed will not work inside the slide view.
This can use left instead of translate3d transform to avoid this issue, I have forked the code and fixed it .

**Comment by oliviertassinari** [comment]
> This can use left instead of translate3d transform to avoid this issue.

From the https://csstriggers.com/transform:
> Changing transform does not trigger any geometry changes or painting, which is very good. This means that the operation can likely be carried out by the compositor thread with the help of the GPU.

It's not the case for the `left` property. This means that it's much better to use the `transform` over the `left` one from a performance point of view.

> so position fixed will not work inside the slide view.

I'm wondering if something like a [`<Portal />`](https://react-bootstrap.github.io/react-overlays/#portals) wouldn't be a better workaround.

**Comment by oliviertassinari** [comment]
I'm closing the issue for the **Portal** workaround.

**Comment by damianobarbati** [comment]
@oliviertassinari I just stumbled upon this but the Portal workaround works flawlessly 🤙🏻
For anyone else stumbling on this, just wrap your absolute/fixed positioned element:
```
import Portal from 'material-ui/Portal';
<Portal container={window.document.body}>
    ...my positioned element
</Portal>
```
I'm using `window.document.body` because I have a fixed element, watch out to use the correct container ref otherwise.

**Comment by oliviertassinari** [comment]
@damianobarbati Thanks for sharing a use case of the [Portal](https://material-ui-next.com/api/portal/) component of Material-UI. Keep in mind that the `container` property is optional. You are providing the default value.

**Comment by damianobarbati** [comment]
Oh ok, thanks for clarifying!

**Comment by joeyparis** [comment]
I would like to add that the Portal component functionality used by Material-UI is a built-in ReactDOM feature if anyone is looking for a more barebones approach.

https://reactjs.org/docs/portals.html

```js
render() {
  // React does *not* create a new div. It renders the children into `domNode`.
  // `domNode` is any valid DOM node, regardless of its location in the DOM.
  return ReactDOM.createPortal(
    this.props.children, // Whatever element you want rendered outside of the local transform coordinate-system
    domNode // Any node outside of the local transform coordinate-system (e.g., document.body)
  );
}
```
