### ISSUE TITLE
How to improve performance on first render?

### ISSUE THREAD

**Issue by abelovic** [oliviertassinari/react-swipeable-views#126]
It appears on first render there are 2 renders per view. The problem I am having is that when I first enter the page it is slow. It is especially noticeable since I animate into the route with react-motion (animation has a delay now) and this gets exponentially worse as the amount of content in the tabs increase x the number of tabs. 

Is there a way to only render the view that is visible once? For example I tried something like this:

```javascript
<SwipeableViews index={this.state.slideIndex} onChangeIndex={ (value) => this.setState({slideIndex: value}) }>

    <div>
        this.state.slideIndex === 0 ? <ComponentOne } /> : null
    </div>

    <div>
        this.state.slideIndex === 1 ? <ComponentTwo /> : null
    </div>

    ...

</SwipeableViews>
```

Which is faster when you have many views since I don't render *all* the tabs twice just the first one (still renders the first one twice) however I now get this message when switching between tabs:

Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

I also tried wrapping the components in a div and setting the style display: 'none' based on the slideIndex but that didn't seem to make a difference either :/

Any recommendations on how to improve the performance?

**Comment by oliviertassinari** [comment]
> there are 2 renders per view

Where do you get this from?
To increase time to first paint, we first render the screen corresponding to the asked index. Then we render the other one.
As soon as your slides component are quite expansive to render, you need to implement a pure logic.
