### ISSUE TITLE
Error with React Native 0.31

### ISSUE THREAD

**Issue by sylvainbaronnet** [oliviertassinari/react-swipeable-views#129]
![screen shot 2016-08-23 at 11 29 06](https://cloud.githubusercontent.com/assets/1569516/17887043/d94f78a2-6924-11e6-93d4-897a876a5dfc.png)

The file is there, I tried to reinstall node modules... It worked with 0.28. Any idea ?

**Comment by delta-9** [comment]
After lookout inside checkIndexBound.js, It seems you use import warning from 'warning';
but you don't specify this in dependency in package.json, I open a pull request.
