### ISSUE TITLE
Material-ui dialog in slide

### ISSUE THREAD

**Issue by zlangbert** [oliviertassinari/react-swipeable-views#13]
If you have a material-ui dialog in a slide after the first, it will pop up in the first slide and you won't see it. Not sure whose issue this would be exactly. I'm sure this problem isn't limited to material-ui dialogs.

**Comment by oliviertassinari** [comment]
That's probably linked to https://github.com/callemall/material-ui/issues/1641. This is not specific to this lib. I'm closing the issue.

**Comment by oliviertassinari** [comment]
One way to fix it is to teleport the creation of the dialog dom outside the slider.
But I'm wondering what is exactly responsabible for this behaviour

**Comment by zlangbert** [comment]
I think because the dialog is `position: fixed` it ignores the containers `transform3d`.

> One way to fix it is to teleport the creation of the dialog dom outside the slider.

What do you mean exactly? How would you render the dialog outside its parent?

**Comment by oliviertassinari** [comment]
I'm talking about somethings like https://github.com/rackt/react-modal/blob/master/lib/components/Modal.js#L59.

**Comment by oliviertassinari** [comment]
@zlangbert We are working on this. https://github.com/callemall/material-ui/pull/2040 is the first step.

**Comment by zlangbert** [comment]
Great to hear, thanks :+1:

**Comment by oliviertassinari** [comment]
@zlangbert Can you try https://github.com/callemall/material-ui/pull/2129?

**Comment by oliviertassinari** [comment]
@zlangbert The PR is merged, could you try again?

**Comment by zlangbert** [comment]
@oliviertassinari Sorry I didn't get back to you. I was trying to test it out using material-ui checked out from git but I couldn't get my project to build with it. I just tried 0.1.4.0-rc1 though and it works perfectly. Thanks again for all your help, you guys are awesome!
