### ISSUE TITLE
is it possible to import from a styles.css file? 

### ISSUE THREAD

**Issue by jasan-s** [oliviertassinari/react-swipeable-views#137]
The reason i inquire is because I wanted to use flexbox and integrate this libs component with other components in a Container.

**Comment by oliviertassinari** [comment]
I don't get it. What's your issue?

**Comment by jasan-s** [comment]
sorry, let me clarify. I have always used css stylesheets for styling. New to inline styles. I want to to use flexbox. however, my babel-loader cause an error when i use say a property "justify-content" . So i was wondering if i can use imported classes to style each swipeeable view.  Additionally I have the benefit of using auto-prefixer.

**Comment by jasan-s** [comment]
sorry, I got it working . silly question.
