### ISSUE TITLE
More interesting behavior when at the ends of the slide deck?

### ISSUE THREAD

**Issue by williamle8300** [oliviertassinari/react-swipeable-views#14]
Hi Olivier thanks for making this!

Are you planning on introducing this? For example, dragging the last slide and it bounces back.

**Comment by oliviertassinari** [comment]
I guess it would be something like
![Image of Yaktocat](https://github.com/souporserious/react-motion-slider/raw/0.0.2/images/react-motion-slider.gif).

I don't have any plan on this, but it would be great.

**Comment by williamle8300** [comment]
Yea that's it! That's too bad! It would be nice if it had that.

I've never really built anything with swiping/touching involved so I don't think I have the competency to give your a decent PR. Thank you for your reply though! Cheers.

**Comment by oliviertassinari** [comment]
This shouldn't be a lot of line changed, but can be tricky to get right.
I will require to allow the index to go outside the allowed range.
We could apply this type of filter http://www.wolframalpha.com/input/?i=1-e%5E%28-x%29 to the input

**Comment by williamle8300** [comment]
I actually don't really understand any of the abstractions for animating stuff. I'm still kind of a noobie programmer

**Comment by oliviertassinari** [comment]
https://github.com/oliviertassinari/react-swipeable-views/commit/bf4182551a03443e0076931f575da5c80242809c should fix this issue.

**Comment by williamle8300** [comment]
DUDE. YOU. ARE. FREAKIN. AWESOME.

In other words, thank you so much! I appreciate this project. Happy thanksgiving Olivier!
