### ISSUE TITLE
onChangeIndex callback  with animation lag  while sliding

### ISSUE THREAD

**Issue by bikashsharmabks** [oliviertassinari/react-swipeable-views#143]
Hello

When I put a callback for SwipeableViews, there is a lag in animation while sliding

```javascript
<SwipeableViews style={styles.slideContainer}
       onChangeIndex={this.props.actions.introSlider}
       threshold={0}>
....
....
</SwipeableViews>

introSlider() {
   let slideIndex = 'slide'+ (index + 1)
   let circleIconfont = {
      slide1: 'circle-o',
      slide2: 'circle-o',
      slide3: 'circle-o'
    }
    circleIconfont[slideIndex] = 'circle'
}
 ```

introSlider slider basically makes dot dot dot on slide

Thanks
Bikash

**Comment by oliviertassinari** [comment]
What's the expected behavior and the current behavior?

**Comment by bikashsharmabks** [comment]
@oliviertassinari Thanks for the reply... 

The issue is with swipe transition being laggy - when I swipe the slider view, the event onChangeIndex is called which calls the function introSlider() there I have  logic written to toggle the slider dots (causing a re-render of view)  which makes the slider bit laggy and the transition from left - right not so smooth as compared to if we don't have the onChangeIndex callback

**Comment by oliviertassinari** [comment]
Oh right, thanks for providing more details. So you are experiencing some junks. Basicaly, it's user responsability to avoid wasted rerendering. You can have a look at https://github.com/oliviertassinari/react-swipeable-views/blob/master/README.md#performance-on-browser.
I'm closing the issue. Feel free to improve the docs if you find anything unclear.
