### ISSUE TITLE
Should not show scrolls while in height transition

### ISSUE THREAD

**Issue by ashl1** [oliviertassinari/react-swipeable-views#144]
Now when using with ```animateHeight``` and different ```div``` heights like in demo 4, the scroll bar is shown in transition because the ```<div>``` with greater height doesn't fit current. The default browser scroll bar has thin width and the content jumped left when transition will be started and return back to right when will be finished.
Could we able to apply ```overflow: hidden;``` while doing transition animations with enabled ```animateHeight```? Or corresponding ```overflow-x/y: hidden;```

**Comment by oliviertassinari** [comment]
Using `overflow-x/y: hidden;` sounds like a good idea :+1:.

**Comment by ashl1** [comment]
This is more complex problem.
The current solution in ed190a6 breaks possibility to use ```maxHeight``` CSS-attribute for slides container.
For example, it breaks the code:
```html
<SwipeableViews
  animateHeight={true}
  containerStyle={{
    maxHeight: 80,
  }}
>
  <div>
    Content for the height greater than 80px
  </div>
  <div>
    Small text
  </div>
</SwipeableViews>
```
The idea that we should enable ```overflowY: hidden``` on the start of animation and return previous ```overflowY``` value after animation will be finished. And this is what not simple for me.

**Comment by oliviertassinari** [comment]
> The idea that we should enable overflowY: hidden on the start of animation and return previous overflowY value after animation will be finished.

Wouldn't we have a content jump if we do so?

**Comment by ashl1** [comment]
Yes, You are right.
What about to create addition ```<div>``` wrapper to slide? I tried in Chrome inline editing for that:

```html
<div style="max-height: 80px; transform: translate(...) ...">
  <div style="width: 100%; flex-shrink: 0; overflow-x: auto; overflow-y: hidden;">
    <div style="overflow-y: auto; height: 100%;">
      <div>
        User slide content
      </div>
    </div>
  </div>
</div>
```

And change ```updateHeight``` to something:
```js
updateHeight(node) {
if (node !== null) {
  const child = node.children[0].children[0];
  if (child !== undefined && child.offsetHeight !== undefined &&
	this.state.heightLatest !== child.offsetHeight) {
	this.setState({
	  heightLatest: child.offsetHeight,
	});
  }
}
}
```

The idea that first ```div``` wrapper handle the whole user content in according of ```max-height``` and add scrollbar if needed. The second ```div``` wrapper used in animation and shouldn't show changed scroll bars at all.

**Comment by ashl1** [comment]
And what about compatibility with ```axis```?

**Comment by oliviertassinari** [comment]
> And what about compatibility with `axis`?

This property isn't fully supported right now. I wouldn't worry until some people complains about it.
Would advising people to disable the `overflowY: 'hidden'` is they need so be an acceptable solution?

**Comment by ashl1** [comment]
I'm talking about not simple behavior in which I need in the future.
Why you don't like my proposal?

**Comment by oliviertassinari** [comment]
> Why you don't like my proposal?

I'm not keen on adding a new layout element `<div />` as it come with a larger overhead. Would be great to solve the issue without.

**Comment by ashl1** [comment]
Sorry, I don't really now about that overhead. Could you please refer me to the measurements?
I only see two variants (theoretically possible): make this with JS or give the browser ability to do it job - manage the visual to meet declared properties.

I will open a PR in 5 days...

**Comment by oliviertassinari** [comment]
I don't have any benchmark. My point is, an additional layout `div` is more work for the browser to do.

> I only see two variants

I have another option. You can apply the following style on each slides:
```css
    max-height: 200px;
    overflow-y: auto;
```
If that's good enough, we can *cherry-pick* `ed190a6` and add a demo with this behavior.
I feel like we reach a point where I should finish #139 so we get some proper e2e tests.

**Comment by ashl1** [comment]
I'll try it test it tommorow or at last - next day.

**Comment by ashl1** [comment]
@oliviertassinari You are right! That's solves the problem.

Think I open PR to add this case to Examples

**Comment by oliviertassinari** [comment]
@ashl1 Awesome, you can change the existing *Demo 4*.
