### ISSUE TITLE
Cannot set height to 100%

### ISSUE THREAD

**Issue by janhartmann** [oliviertassinari/react-swipeable-views#147]
Hi and thanks for this beautyfull library!

I am currently writing an application which is going to be run on both iPads, Android tablets and other screens. The applications runs in full screen and I am trying to get the swipe-able views to be on the whole screen.

My application uses flexbox and most container components have height 100%.

Component render:

```js
render() {
	const { children } = this.props; 
	const BindKeyboardSwipeableViews = bindKeyboard(SwipeableViews);
	const styles = {
		height: "100%"
	}
	return (
		<App>
			 <BindKeyboardSwipeableViews style={styles} slideStyle={styles}>
				<div className="swipe-view" style={styles}>
				   Slide view 1 content
				</div>
				<div className="swipe-view" style={styles}>
					I can slide in
				</div>
			</BindKeyboardSwipeableViews>
		</App>
	);
}
```

While all my slides have 100% now, one of the `div`'s which Swipeable Views render does not. This "breaks" my layout. :-)

If I set `animateHeight={true}` on the `BindKeyboardSwipeableViews` the height on the container is now `0px`.

Is it possible to have property where I can set height height explicity?

The rendered style is as so:

```html
<div style="overflow-x: hidden; height: 100%;">
    <div style="transform: translate(0%, 0px); flex-direction: row; display: flex; will-change: transform;">
        <div style="width: 100%; flex-shrink: 0; overflow: auto; height: 100%;">
            <div class="swipe-view" style="height: 100%;">
                Slide view 1 content
            </div>
        </div>
        <div style="width: 100%; flex-shrink: 0; overflow: auto; height: 100%;">
            <div class="swipe-view" style="height: 100%;">
				I can slide in
			</div>
        </div>
    </div>
</div>
```

I would like to provide the height for the div containing the style: `transform: translate(0%, 0px); flex-direction: row; display: flex; will-change: transform;`

Thanks :-)

**Comment by janhartmann** [comment]
Nevermind! I did not see `containerStyle` could be passed! Closing....

**Comment by oliviertassinari** [comment]
I'm glad you found a solution.

**Comment by mflores-verys** [comment]
@oliviertassinari is there any way to pass styles for the child of the container that receives `containerStyle`? I'd like to override `overflow`.
