### ISSUE TITLE
Components receive multiple mount events

### ISSUE THREAD

**Issue by sterlingwes** [oliviertassinari/react-swipeable-views#15]
Tested with a single child div, received `componentWillMount` event twice.

**Comment by oliviertassinari** [comment]
That's right, we first render one slide and then we render the other slides.
The goal is to render something interesting as quickly as possible.

**Comment by sterlingwes** [comment]
Multiple mounts for the same slide doesn't make sense though. In this case I was fetching data for the view in that slide's componentWillMount, and with swipeable wrapping it that request went out twice due to that lifecycle event getting called twice at setup.
Slick looking library though!






On Sun, Nov 22, 2015 at 11:17 AM -0800, "Olivier Tassinari" <notifications@github.com> wrote:












That's right, we first render one slide and then we render the other slides.

The goal is to render something interesting as quickly as possible.

**Comment by oliviertassinari** [comment]
> Multiple mounts for the same slide doesn't make sense though

I agree, this just just be one mont and two render. I'm gonna investigate this.

**Comment by oliviertassinari** [comment]
https://github.com/oliviertassinari/react-swipeable-views/commit/a44b928070b88e4d4aabefb53a8922a5c63a49b4 Solve this issue
