### ISSUE TITLE
Multiple slides are treated as a single slide when axis="y"

### ISSUE THREAD

**Issue by tomkel** [oliviertassinari/react-swipeable-views#155]
Here's a simple example:

```javascript
import React from 'react'
import ReactDOM from 'react-dom'
import SwipeableViews from 'react-swipeable-views'

const styles = {
  slide: {
    minHeight: 100,
  },
}

const App = () => (
  <SwipeableViews axis="y">
    <div style={styles.slide}>1</div>
    <div style={styles.slide}>2</div>
    <div style={styles.slide}>3</div>
  </SwipeableViews>
)

ReactDOM.render(<App />, document.getElementById('app'))
```

**Comment by oliviertassinari** [comment]
What the expected result?

**Comment by tomkel** [comment]
Here's a gif of what happens. Because I'm only swiping once, it should navigate to the second div. In the react dev tools it shows that the `currentIndex` state of SwipeableViews is `1`, which confirms that it is treating all 3 divs as one index.

![aa](https://i.imgur.com/JTXbZ2C.gif)

**Comment by oliviertassinari** [comment]
> confirms that it is treating all 3 divs as one index

Yes, it's his. Hence my second question.
Why using this style?
```js
  slide: {
    minHeight: 100,
  },
```

**Comment by tomkel** [comment]
Because that was in the source code for the [demo](https://github.com/oliviertassinari/react-swipeable-views/blob/master/docs/src/demo/DemoAxis.js). 

Anyway, changing it to something else like `height: 100` doesn't have any effect.

**Comment by oliviertassinari** [comment]
You also need to provide a height to the `containerStyle` property.
E.g. https://github.com/oliviertassinari/react-swipeable-views/blob/master/docs/src/demo/DemoAxis.js#L7.

**Comment by romainwn** [comment]
I know it is a closed issue, but the expected result is the following : if we swipe once, then it treats only one div ?
I'm trying to do the exact same thing, except I want to deal div per div, and not the 3 at the same time
