### ISSUE TITLE
Swiping broken between 0.7.6 and 0.7.7

### ISSUE THREAD

**Issue by janhartmann** [oliviertassinari/react-swipeable-views#158]
Hi

I've just updated my dependencies on react-swipeable-views, from 0.7.6 to 0.7.8 which broke my x-axis swiping on my nested react-swipeable-views. I then downgraded to 0.7.7, the issue still persists. Downgrading to 0.7.6 and the issue is gone.

I have a feeling it must have something do with commit https://github.com/oliviertassinari/react-swipeable-views/commit/5551ac90c5f65a2fbf54f6aaf3b0688c37799aa9

My application consists of one big swipe-able view (on the y-axis). The swipe-able view contains nested swipe-able view which is now broken. The nested swipable view is swiping on the x-axis.

Swiping the outer swipeable view (which scrolls on the y-axis) works just fine - but its the nested x-axis which is no longer working?

Please note that the transitions (e.g. auto-play) works just fine. Just swiping on a touch display is broken.

Any ideas?

**Comment by oliviertassinari** [comment]
Right, I was able to reproduce the behavior locally. I'm gonna have a look at it.

**Comment by janhartmann** [comment]
Awesome! I really appreciate your work! The library is fantastic! :-)
