### ISSUE TITLE
Handle slide content width changes

### ISSUE THREAD

**Issue by ashl1** [oliviertassinari/react-swipeable-views#159]
Before making any changes and doing any PR I open this Issue to discuss on how to do it better.

1. We has a GMD List inside the Swipeable view inside Paper.
2. We want to animate changes on list (adding or deleting new items). Of course, we want the Paper to change the height to be match the content.
3. Also we want to synchronously changes in list elements height and Swipeable view height with [GMD transition](https://material.google.com/motion/duration-easing.html#duration-easing-natural-easing-curves).

As I can see the ```<div>``` container which handles height correspond to ```<Motion>``` component. So the question is how to provide different height and transition to it?

**Comment by oliviertassinari** [comment]
@ashl1 Sorry, but I'm not answering Material-UI issue here. Regarding animating the height of the `SwipeableView` you can use one of the following property:
- `style`
- `className`
- `containerStyle`
- `slideStyle`
