### ISSUE TITLE
React native support

### ISSUE THREAD

**Issue by oliviertassinari** [oliviertassinari/react-swipeable-views#16]
It would be great to make this work on react-native too.

**Comment by NickNothom** [comment]
Would also really like to see this! 

I have noticed that after my app has been running for a bit, tab switching becomes very laggy on my Android device. Swiping up and down within each tabs remains smooth. And swiping back and forth while keeping my finger on the screen seems to work okay after a few seconds.

But when I swipe between tabs it gets choppy sometimes. Reinstalling the app fixes the issue for a bit.

**Comment by oliviertassinari** [comment]
> I have noticed that after my app has been running for a bit, tab switching becomes very laggy

Do you think we have some memory or node leak?
