### ISSUE TITLE
Why are the the non-current views not hidden

### ISSUE THREAD

**Issue by galki** [oliviertassinari/react-swipeable-views#160]
This is especially noticeable on mobile when every view has different a height, and every view thus inherits the height of the highest view. This results in a huge blank space.

**Comment by oliviertassinari** [comment]
Could you provide a reproduction test case?
If you are targeting the browser environment, you can use this playground: http://www.webpackbin.com/V10kOcV6-.

**Comment by galki** [comment]
Sure. Please check http://www.webpackbin.com/4ye_XPSTb
Notice the white space within the border.

On Wed, Sep 28, 2016 at 8:27 PM, Olivier Tassinari <notifications@github.com

**Comment by oliviertassinari** [comment]
Thanks,  that makes much more sense. Well, that's the expexted default behavior.
That's linked to the implementation approach used.
You have two way to solve it.
1. You can set a fix height with the styles properties.
You can have a look at the demo source code.
2. You can use the `animateHeight` property.  Again, have a look at the demos.

**Comment by galki** [comment]
Thanks.

On Thu, Sep 29, 2016 at 4:32 PM, Olivier Tassinari <notifications@github.com
