### ISSUE TITLE
Child element horizontal padding adds to parent view height

### ISSUE THREAD

**Issue by galki** [oliviertassinari/react-swipeable-views#161]
In the image the yellow button has horizontal padding. This swipeable view is one of eight, each with each own yellow button. It looks like each button's horizontal padding adds to the overall height of the swipeable views parent, resulting in the big white space under the button. If I add more padding to any element (say add more buttons), this space will increase.
![swipableview](https://cloud.githubusercontent.com/assets/7866221/18939662/cbc1af36-863c-11e6-86bd-0f98d18405cc.jpg)

**Comment by oliviertassinari** [comment]
Same here. Some source code / playground would help understanding the issue

**Comment by galki** [comment]
It was an unrelated css issue. Sorry for that.
