### ISSUE TITLE
iOS can't scroll vertically on swipeable view

### ISSUE THREAD

**Issue by galki** [oliviertassinari/react-swipeable-views#163]
The pink area (swipeable view) does not allow vertical scrolling of the window on an iPhone5. Is there a way to force it?

![test](https://cloud.githubusercontent.com/assets/7866221/18981869/d1ab5bc8-871c-11e6-9da6-23a175b0fe18.jpg)

http://www.webpackbin.com/NJOns1wa-

**Comment by oliviertassinari** [comment]
> does not allow vertical scrolling

Are you refering to the inertial scrolling of iOS?

**Comment by nasredin** [comment]
same for me 0.7.9, ipad not scrolling 0.7.8 is ok

**Comment by oliviertassinari** [comment]
It's most likely linked to https://github.com/oliviertassinari/react-swipeable-views/commit/e187f317144f42d892a901dc9208d6a170732497#diff-fb00d0b037b3caf7a015eac7e03a3593R317.
Yeap, I have only noticed the issue on iPad so far.
