### ISSUE TITLE
[browser] Support Pointer Events

### ISSUE THREAD

**Issue by ghost** [oliviertassinari/react-swipeable-views#164]
This component  don't work in IE Windows Phone because they use PointerEvent 

Please support PointerEvent
https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/dev-guide/dom/pointer-events/

https://www.w3.org/TR/pointerevents/

![pointer](https://www.w3.org/TR/pointerevents/pointer.png)

**Comment by oliviertassinari** [comment]
Right, that would be good to support Windows Phone. However, that's not a priority for me.
That represent a very low fraction of the overall traffic (1,20 %). I would accept a PR to fix it.
But I won't work on it.

**Comment by simonwatt** [comment]
It makes sense that you don't want to work on something with such low usage, however I think the documentation is inaccurate (and should be updated) as it shows that Edge is supported when it's not actually responding to touch gestures.

**Comment by oliviertassinari** [comment]
Based on https://github.com/oliviertassinari/react-swipeable-views/issues/183#issuecomment-280537197, we will most likely have to handle `touch-action` dynamically to prevent scrolling.

**Comment by oliviertassinari** [comment]
Ok, I have found a [Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent) section in the Web APIs | MDN.
The `PointerEvent` implementation isn't ready for prime time. Many browsers are lagging behind.
Implementing it here would only increase bundle size. Also, [the Windows Phone platform is dying](https://www.theverge.com/2017/7/11/15952654/microsoft-windows-phone-end-of-support).
