### ISSUE TITLE
How can I swipe from last one to first one

### ISSUE THREAD

**Issue by zhouzhongyuan** [oliviertassinari/react-swipeable-views#169]
I know I can slide like this: 1 -> 2->3     3->2->1

How about 3->1 ?

**Comment by ChengGC** [comment]
I also need

**Comment by oliviertassinari** [comment]
You can use the `virtualize` HoC with the `slideCount` property.

**Comment by zhouzhongyuan** [comment]
@oliviertassinari  Sorry, I think I didin't say it clearly.

I have only three items: 1, 2, 3 . I use the autoPlay.

What I want :  it plays like 1 -> 2 -> 3 -> 1 -> 2 -> 3 -> 1 -> 2 -> ……

The importance : when in "3", how can go to "1"?
                            (BUT Now, when in  "3", I only can go back to "2")

What I want is  just like a [bootstrap carousel] (http://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_carousel&stacked=h)

![Carousel](https://qiita-image-store.s3.amazonaws.com/0/15444/5ecfa708-ea40-58de-28de-5b9ac5d6ab55.gif)

**Comment by oliviertassinari** [comment]
> What I want is just like a bootstrap carousel

In that case, use the `virtualize` with a proper `renderSlide` property fonction. There is some boilerplate at stake here. If it's a common pattern, we could provide an helper.

**Comment by zhouzhongyuan** [comment]
@oliviertassinari  Thanks.
