### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "react-display-name"

### ISSUE THREAD

**Issue by neekey** [oliviertassinari/react-swipeable-views#17]
Hi, I encountered this error, when using babel-loader with webpack, and I found that the .babelrc did depend this plugin: 

```
{
  "env": {
    "development": {
      "plugins": [
        "react-display-name",
        "react-transform"
      ],
      "extra": {
        "react-transform": {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
          }, {
            "transform": "react-transform-catch-errors",
            "imports": ["react", "redbox-react"]
          }]
        }
      }
    },
    "production": {
    }
  }
}

```

but it seems like the "babel-plugin-react-display-name" is not specified in "dependencies".

**Comment by oliviertassinari** [comment]
It's here https://github.com/oliviertassinari/react-swipeable-views/blob/master/package.json#L45.
If you make babel parse the source code of this project. You have to install it on your project too.

**Comment by neekey** [comment]
Yes, I figured this out by doing exactly as what you pointed out, it works. 

Maybe document this in case others running into the same issue?

**Comment by oliviertassinari** [comment]
> Maybe document this in case others running into the same issue?

Sounds like a great idea.
I feel like it's an issue with babel.

**Comment by oliviertassinari** [comment]
Done https://github.com/oliviertassinari/react-swipeable-views/commit/afcef71f71aa54075e49660e241148455a5fa354

**Comment by neekey** [comment]
good work!
