### ISSUE TITLE
[Virtualize] camera - sticky views

### ISSUE THREAD

**Issue by gastonmorixe** [oliviertassinari/react-swipeable-views#170]
Hi,

I'd love to use VirtualizeSwipeableViews, but one of the children Views is the Camera (iOS).

This Camera view has to be reused and not initialized/deinitialized each time it will appear/disappear.

How can I make a child view stay initialized/mounted not removed/killed?

Thank you

**Comment by oliviertassinari** [comment]
What about providing a `left` and a `right` property to render some slides on the edges?
