### ISSUE TITLE
Add callback when swipe animation is complete

### ISSUE THREAD

**Issue by vincentsels** [oliviertassinari/react-swipeable-views#171]
It would be nice to have a callback available similar to `onChangeIndex` but which only triggers when the swipe animation completes. You'd probably use the [`onRest`](https://github.com/chenglou/react-motion#--onrest---void) callback from react-motion. Might be a good name to use in your API too (alternatively, [swipe.js](https://github.com/thebird/Swipe) uses `transitionEnd`).

Just the current index would be sufficient as a parameter (from a quick look at the code it looks like it would be more difficult to also include the previous index).

The reason I believe this would make sense is that you typically use some cpu (rendering, drawing) upon switching index (certainly when you virtually build views), which results in long/skipped frames during the swipe animation. Doing these calculations *after* the animation finishes would still use the same cpu and long frames, but at least the user wouldn't notice them as much.

**Comment by oliviertassinari** [comment]
I agree, that sounds like a good property to have.

**Comment by vincentsels** [comment]
Thanks for the quick response and implementation!

Unfortunately I realize now that this alone doesn't solve the intended problem. When using a virtual component, the `slideRenderer` will still be triggered by `onChangeIndex` - and it's this that uses the cpu and causes the long frames during the animation. Additionally, having the component's internal state change at `onChangeIndex`-time and then changing application state at `onTransitionEnd` time causes very weird behavior.

Maybe a better approach would be some kind of switch instead, which toggles when the component's state should be changed and the callback should be called: on swipe end, or on transition end. For instance an optional boolean property `changeIndexOnTransitionEnd`.

**Comment by oliviertassinari** [comment]
@vincentsels Could you open another issue with what you are trying to achieve and what's not working? Thanks!
`onTransitionEnd` could help in other circumstances.
