### ISSUE TITLE
"Don't call PropTypes" warning in console

### ISSUE THREAD

**Issue by abuddiga** [oliviertassinari/react-swipeable-views#172]
Hi, we're seeing the following warning in console, coming from `Virtualize` and `SwipeableViews`. Looks like it's happening because these components' PropTypes are wrapping React's PropTypes, generating a false positive: https://facebook.github.io/react/warnings/dont-call-proptypes.html. The link includes a description of how to fix, but not sure if that example is completely relevant here? Wanted to bring to your attention though.

<img width="673" alt="screen shot 2016-10-19 at 1 01 04 pm" src="https://cloud.githubusercontent.com/assets/4003102/19535685/9cf8210a-95fd-11e6-86db-0e5faffa79a4.png">

**Comment by oliviertassinari** [comment]
What version are you using. I have no idea where this warning is coming from.

**Comment by abuddiga** [comment]
Sorry @oliviertassinari should have included that originally. We are using the following:

```
"react-swipeable-views": "0.7.10",
"react-swipeable": "3.1.0",
"react": "0.14.8",
"react-motion": "0.4.5"
```

**Comment by oliviertassinari** [comment]
I'm closing this issue. I believe that something is wrong on your side. Makes sure you don't wrap the component nor that you have two versions of React installed.
