### ISSUE TITLE
[Virtualize] Custom (slower) springConfig is jumpy

### ISSUE THREAD

**Issue by jardakotesovec** [oliviertassinari/react-swipeable-views#174]
My use case is closest to Demo 8, so I also tried successfully to reproduce there. Simply just using some springConfig that is slower than the original settings - result is that during the animation it suddenly jump to the end state. These parameters are very slow..  but same issue is with anything slightly slower than original. 

I have been changing the slides using keyboard (arrow keys).

So here is snippet from customized DemoVirtualized.

``` jsx
          <VirtualizeSwipeableViews
            springConfig={{
              stiffness: 100,
              dumping: 30
            }}
            index={this.state.index}
            onChangeIndex={this.handleChangeIndex}
            slideRenderer={slideRenderer}
          />

```

Any idea whats going wrong? Let me know if you can't reproduce.

Thank you.

**Comment by oliviertassinari** [comment]
That's most likely linked to https://github.com/oliviertassinari/react-swipeable-views/issues/171.
I have an [hard coded](https://github.com/oliviertassinari/react-swipeable-views/blob/master/src/virtualize.js#L8) timeout to 500ms.

**Comment by oliviertassinari** [comment]
I have just fixed a related issue on the `browser` and `native.animated`: 34b5c1838a624609ff3a335559440b9a288b5245.
Before:
![bug](https://cloud.githubusercontent.com/assets/3165635/19837850/62be405e-9ec3-11e6-9318-ef94b4ac96c3.gif)

After:
![fix](https://cloud.githubusercontent.com/assets/3165635/19837853/7349cea2-9ec3-11e6-9dae-9e9f1490ee01.gif)

**Comment by jardakotesovec** [comment]
@oliviertassinari Just tried the new release, but still has that jumpiness that I described in initial description. Just to point out I am using keys in this case to go to the next slide - it slides nicely but shortly before the end it just jump to the final position.

Can you reproduce on example from initial description?

**Comment by oliviertassinari** [comment]
@jardakotesovec Could you post a full example into a different issue? That would help. Thanks!

**Comment by jardakotesovec** [comment]
@oliviertassinari I can, but I would copy&paste exactly the same description, because its still exactly the same issue I reported here, so reopening I think would be less confusing.

With regards to full example - I am using `DemoVirtualize.js` from `react-swipeable-views/docs/src/Demo`. And just adding springConfig with slower settings than its the default. And than using arrow keys to move between slides.

**Comment by oliviertassinari** [comment]
Solved in https://github.com/oliviertassinari/react-swipeable-views/commit/5eeb421be1072a92068d65ef1eecfacb28fbfe01.

**Comment by jardakotesovec** [comment]
@oliviertassinari Thanks!

**Comment by oliviertassinari** [comment]
@jardakotesovec That was a different issue, I have opened https://github.com/oliviertassinari/react-swipeable-views/issues/184 for investigating a better solution.
