### ISSUE TITLE
nested axis x component with more than one children behaving not as expected

### ISSUE THREAD

**Issue by jasan-s** [oliviertassinari/react-swipeable-views#176]
Not sure if this is the intended behavior but when I create a nested x-axis component within a y-axis component and the nested x-axis component has multiple children. The switch between outer y-axis component is restricted to only work when swiped on area not covered by the nested x-axis component. 

Check out this http://www.webpackbin.com/EkTmBCD1M and try swiping up on any List A item. however swiping on any List B item registers fine.

**Comment by oliviertassinari** [comment]
I confirm, something weird is going one here.
