### ISSUE TITLE
animateHeight={true} -> issue with overflow

### ISSUE THREAD

**Issue by noabyuna** [oliviertassinari/react-swipeable-views#177]
When the swipeview is initialized with the property animateHeight={true} the the swipeable container behaves as expected: It has the perfect size to fit the content.
But once some list you output withing that container gets highter (e.g. states changes and the map function returns more <li/> elements) the height doesn't change accordingly. You have to swipe to another swipecontainer and then come back again to see the correct height.

Is there an event which I can trigger to recalculate the height once my content changes?

**Comment by oliviertassinari** [comment]
Here is a related issue #144.

**Comment by noabyuna** [comment]
Thanks for the quick reply. I would much rather see the height of the container get updated than dealing with a overflow auto scrollbar :/

**Comment by torte** [comment]
Having the same problem. I basically load the content of each container in the list of swipable containers, after the swipable views has been rendered the first time. If the `animateHeight` property is set to `true` the first views does not render correctly. I tried to hack this and set the `animateHeight` to `false` the first time I load the component and then change it to `true` once I do the first swipe, but this results in weird jumps on the page once I set the property to `true`. Hope this can be fixed soon. Thx.

**Comment by oliviertassinari** [comment]
> I would much rather see the height of the container get updated than dealing with a overflow auto scrollbar

That wasn't working before this change.
Dynamic content height are definitely not supported right now.
You can add an `overflow-y: auto;` style to the slides that are going to have a greater height.
I have no plan regarding improving this point.
I'm not sure what's the best approach is.

**Comment by DaveSpivey** [comment]
This isn't ideal, but I used a callback for any event affecting the height to call forceUpdate() on the component that renders SwipeableViews. Made even hackier by the fact I had to put it in a setTimeout so it would wait for a child's height transition to complete before re-rendering and recalculating height. Works, but makes me a little sad.

**Comment by oliviertassinari** [comment]
@DaveSpivey Any idea how we could improve this *dirty* hack? Maybe exposing a callback trigger.

**Comment by Nopik** [comment]
I was pretty happy with this component, but since I discovered this issue, it is a show-stopper and I'll have to find some alternative ;(

**Comment by oliviertassinari** [comment]
@Nopik Or you could help fixing it :)

**Comment by Nopik** [comment]
Yeah, trying to, actually ;) In my case force refreshing the whole container should work. If the container would expose some callback, I can call it to, after my content changes. Not ideal, but will do the job.

`heightLatest` is already in the state, and there is `updateHeight` method, though its argument makes it extremely hard to use from client code. It should be easy to expose more convenient method to the client, as you know all the nodes (can remember array of refs, not doing that at the moment) and index of currently selected node. So, argumentless `updateHeight` should be quite easily possible.

Then, client should call that after content change, and it theoretically should work, if I didn't overlooked something.

Also, having such method available in context would be great, too, so there would be no need to remember refs on client side and pass update callback through possible large number of prop layers.

And indeed, when I did a quick and dirty new function (which would have height as a single argument and `setState` it to `heightLatest`), exposed it via context and called from child deep in the hierarchy, the height nicely animated to the correct value. Interestingly, even if I provided too high value, like `2000`, the container height updated to the correct value (`565` in my test case). I guess, extra update was there.

Adding it in a proper way (not requiring a height as an argument, but having an array of refs & taking the height of the correct one), would solve the problem for me.

**Comment by Nopik** [comment]
So, for now, taking an advantage that there is extra update in meantime, I modified my function to set latest height to zero, and being argumentless. So, it is easy to call from client code, and the resulting effect on screen is exactly what I want.

That should definitely be improved later on to cleaner version & proper algorithm described above, but for now it does the trick. I'll try to fork and issue PR for it - as the change is additive, it wont break any existing code, but for those in need it will be a help.

**Comment by Nopik** [comment]
Issued https://github.com/oliviertassinari/react-swipeable-views/pull/279

**Comment by Nopik** [comment]
Btw. it seems that setting height to 0 will actually animate it from current height to zero, then to the desired height. Setting it to currentHeight + 1 gets rid of that effect.
