### ISSUE TITLE
In mobile web, I can't slide to the first one using touch event 

### ISSUE THREAD

**Issue by kimown** [oliviertassinari/react-swipeable-views#178]
First, thank your guys for this project, this is an awesome slide component  I needed. 

But I have a problem, this is my custom code from Demo 7 autoplay

``` jsx
      <div style={styles.root}>
        <AutoPlaySwipeableViews index={index} onChangeIndex={this.handleChangeIndex} interval={1000} autoplay={true}>
          <div style={Object.assign({}, styles.slide, styles.slide1)}>
            slide n°1======
          </div>
          <div style={Object.assign({}, styles.slide, styles.slide2)}>
            slide n°2==============
          </div>
          <div style={Object.assign({}, styles.slide, styles.slide3)}>
            slide n°3=======================
          </div>
        </AutoPlaySwipeableViews>
        <Pagination
          dots={3}
          index={index}
          onChangeIndex={this.handleChangeIndex}
        />
      </div>

```

In PC, it works well, I don't neet touch event,  slide n°3 can swipe to slide n°1.
![reactswipe](https://cloud.githubusercontent.com/assets/7932380/19711742/71781900-9b6a-11e6-92ad-1c82b34ab27b.gif)

 But in mobile web, I use touch event. I swipe to last one: slide n°3, then I can't swipe to the first slide: slide n°1, and slide n°1 also can't swipe to slide n°3 using touch event , is it a bug ?

I have found similar issues, https://github.com/oliviertassinari/react-swipeable-views/issues/169, https://github.com/oliviertassinari/react-swipeable-views/issues/22
 but they seems different from my problem.

**Comment by oliviertassinari** [comment]
@kimown How is #169 different from your use case? I believe that's the same one.
I feel like we should be adding a Demo for it. What do you think?

**Comment by kimown** [comment]
@oliviertassinari Awesome, loop mode is a common function in slide component, thanks.

**Comment by oliviertassinari** [comment]
Here is an example of implementation with 3 different slides:
```js
import React from 'react';
import SwipeableViews from 'react-swipeable-views';
import virtualize from 'react-swipeable-views/lib/virtualize';
import mod from 'react-swipeable-views/lib/utils/mod';

const EnhancedSwipeableViews = virtualize(SwipeableViews);

function slideRenderer(params) {
  const {
    index,
    key,
  } = params;

  switch (mod(index, 3)) {
    case 0:
      return (
        <div key={key}>
          {'slide n°1'}
        </div>
      );

    case 1:
      return (
        <div key={key}>
          {'slide n°2'}
        </div>
      );

    case 2:
      return (
        <div key={key}>
          {'slide n°3'}
        </div>
      );

    default:
      return null;
  }
}

const DemoHocs = () => (
  <EnhancedSwipeableViews slideRenderer={slideRenderer} />
);

export default DemoHocs;
```

This API has some *pros* and *cons*

### Pros

- Rendering an arbitrary high number of slides isn't going to have a negative impact on performance. We have majored the complexity.
- We have a better control on the React lifecycles rendering process.
E.g. We could add an extra performance optimization layer by caching answer of the `slideRenderer` callback property.

### Cons

- There is more boilerplate in the API.
- The API is less user-friendly.

**Comment by steezeburger** [comment]
I was able to get this to work with your exact setup, and I sort of got it to work by passing in my pre-made views (React components), but I get some errors because the keys are not unique (the keys are built somewhere else when I create my views). I was able to get the slides working, but they are not actually circular. 

I tried many things including React.cloneElement (which was very non performant). Do you have any ideas here?

I also noticed that it simply doesn't work if I don't include the `slideCount` prop on my virtualize HOC. I don't fully understand what slideCount does. Can you elaborate on this?

**Comment by oliviertassinari** [comment]
> I don't fully understand what slideCount does.

It's adding two boundaries. The index can go above `slideCount` and under `0`.

> there are times where it will not allow me to continue the scrolling the views.

Do you have a screen recording showing it? If you do, could you post it on a new issue so we can investigate it further?

**Comment by yoadsn** [comment]
I think I can shine some light on this.
When swiping to the left (for example) very fast, you could swipe fast enough that `onTransitionEnd` has no chance to be called and so `setWindow` is not called either.
In that case if you reach the last rendered slide, for some reason (I'm not sure yet) rendering is not taking place for additional slides.
You have to slide right, wait for the transition to end, and then start swiping left again.
I would speculate it has something to do with this change:
https://github.com/oliviertassinari/react-swipeable-views/commit/c34e5dd4488a3c7600583f5187f45281d60bb93f

**Comment by wysj** [comment]
I meet the same problem.
I want to how, how to solve the loop mode in autoPlay  component.

**Comment by wysj** [comment]
You can ues  'autoPlay(virtualize(SwipeableViews))' this way to solve you problem.

**Comment by wwwebman** [comment]
But what if have dynamic Teasers? `switch/case` smells for me in this case. How it can be solved for such case?

**Comment by scurrilus-funke** [comment]
For those who looking for a solution for dynamic infinit loop without switch case. Just use a small calculation. Get index subtract it with your data length and multiply it with how often data length take place in your current index.

**Example:** 
const dataIndex= Math.abs(index - data.length * Math.floor(index / data.length));
const dataIndex= Math.abs(6 - 4 * Math.floor(6 / 4))
const dataIndex= Math.abs(2 * 2)
const dataIndex = Math.abs(2 * 1)
const dataIndex = 2

The dataIndex can be use selecting your data entry. data[dataIndex].title

`import React from "react";
import SwipeableViews from "react-swipeable-views";
import { virtualize } from "react-swipeable-views-utils";

const VirtualizeSwipeableViews = virtualize(SwipeableViews);

const MediaCardCarousel = () => {
  const data = [
    {
      title: "Test A"
    },
    {
      title: "Test B"
    },
    {
      title: "Test C"
    },
    {
      title: "Test D"
    }
  ];
  const slideRenderer = ({ key, index }) => {
    const dataIndex = Math.abs(
      index - data.length * Math.floor(index / data.length)
    );
    return <div key={key}>{`slide: ${data[dataIndex].title}`}</div>;
  };
  return (
    <VirtualizeSwipeableViews
      slideRenderer={slideRenderer}
      enableMouseEvents
      className={classes.slide}
    />
  );
};

export default MediaCardCarousel;`

**Comment by WillSquire** [comment]
Worth mentioning `mod` is now in `import { mod } from 'react-swipeable-views-core'`.
