### ISSUE TITLE
Prevent swiping in one direction? 

### ISSUE THREAD

**Issue by marchaos** [oliviertassinari/react-swipeable-views#179]
Hi, is it possible to prevent swiping in one direction, so you can only swipe forward for example?

**Comment by oliviertassinari** [comment]
By controlling the component, you could override the user interaction when they try to move in the opposite direction.
Alternatively, you could remove slide as user move in one direction. However, you might notice one issue when doing so with moving forward as #152 try to address.

**Comment by oliviertassinari** [comment]
Actually, the first option is probably the best one as it's gonna provide a better user feedback regarding the forbidden direction.
I have modified the [DemoTabs](https://github.com/oliviertassinari/react-swipeable-views/blob/master/docs/src/demo/DemoTabs.js) to get it working.
```jsx
  handleChangeIndex = (index) => {
    const oldIndex = this.state.index;
    this.setState({
      index,
    }, () => {
      if (index < oldIndex) {
        this.setState({
          index: oldIndex,
        });
      }
    });
  };
```
![oct -31-2016 23-37-09](https://cloud.githubusercontent.com/assets/3165635/19874081/f9374ed6-9fc2-11e6-96d5-752099373f2b.gif)

**Comment by Asthonishia** [comment]
@oliviertassinari Any possibility to completly disable touch swipe ? ( PS : your demo link is KO now )
