### ISSUE TITLE
IE10 support problem

### ISSUE THREAD

**Issue by kimown** [oliviertassinari/react-swipeable-views#180]
I have tested in the major browser, like edge, ie(version>=11), chrome,firefox, safari,
It works properly.But in IE10, 

slide 1:
![deepinscreenshot20161027105746](https://cloud.githubusercontent.com/assets/7932380/19753032/508b0142-9c34-11e6-81cd-85ef8ee3b6ec.png)

slide 2:
![deepinscreenshot20161027105734](https://cloud.githubusercontent.com/assets/7932380/19753038/5ac23d10-9c34-11e6-89d5-dd68917c1320.png)

Flex layout isn't fully supported in IE10, can you give some suggestions? or we should list supported browsers in README.md.

**Comment by oliviertassinari** [comment]
IE10 was supported with an earlier version of React. By investing time, that could be done.
But that's 0.3% of the market share. I won't work on it.

You are right, we should add this limitation in the README.md 👍 . I'm on it.

**Comment by oliviertassinari** [comment]
Alternatively, we could be following [slick](https://github.com/kenwheeler/slick) solution with the `floating: left`. However, that layout approach is slower than the flexbox one on modern browser.

**Comment by Ixl123** [comment]
@kimown I had to make this library to work on IE 10 there is an easy workaround which works for me you basically have to add the special IE 10 flexbox classes to the container ( I made a pull request for that #334  )

```
.react-swipeable-view-container {
        display: -ms-flexbox;
      }
 .react-swipeable-view-container > div {
          -ms-flex-negative: 0;
      }
```
