### ISSUE TITLE
[proposal] Expose a friendly API for circular slides

### ISSUE THREAD

**Issue by oliviertassinari** [oliviertassinari/react-swipeable-views#181]
### The problem

Following this #178 issue, I have realized that the API to implement circular slides isn't that great.
The trade-off behind it is exposed [here](https://github.com/oliviertassinari/react-swipeable-views/issues/178#issuecomment-257539715).

### The solution

For a low number of slides, where performances isn't an issue, we could expose an API quite similar to the `SwipeableViews`. We would be using `virtualize` under the hood.
E.g.
```jsx
import React from 'react';
import SwipeableViewsCircular from 'react-swipeable-views/lib/Circular';

const MyComponent = () => (
  <SwipeableViewsCircular>
    <div>
      slide n°1
    </div>
    <div>
      slide n°2
    </div>
    <div>
      slide n°3
    </div>
  </SwipeableViewsCircular>
);
```
I'm not sure yet if an HoC is better than a component.

**Comment by kimown** [comment]
Thank you!   :+1:

**Comment by knipferrc** [comment]
Any updates on this?
