### ISSUE TITLE
Material UI onChange fires SwipeableViews onChange and assigns that value to its index

### ISSUE THREAD

**Issue by jronSomers** [oliviertassinari/react-swipeable-views#182]
Hey, I am trying to use your very neat library and I have some text fields inside a tab with their own generic onChange method. Below is an example of what i pretty much have going for me right now.

```jsx
constructor(props, context){
        super(props, context);
        this.state = {
            currentTabIndex: 0, // 0 is the tab1 tab
            txtField1: ''

        };
        this.handleTxtFieldChange = this.handleTxtFieldChange.bind(this);
        this.handleTabChange = this.handleTabChange.bind(this);
}
// Im using this because i have a ton of text fields and this is a way to generically bind each text field with its variables name in the state.
handleTxtFieldChange(event){
        event.preventDefault();
        this.setState({
            [event.target.name] : event.target.value
        });
    }
handleTabChange(event){
        this.setState({
            currentTabIndex : event.target.value
        });
    }
render() {
        return (
            <div>
                <Tabs
                value={this.state.currentTabIndex}
                onChange={this.handleTabChange}
                >
                    <Tab label="tab1" value={0} />
                    <Tab label="tab2" value={1} />
                </Tabs>
                <SwipeableViews
                index={this.state.currentTabIndex}
                onChange={this.handleTabChange}
                >
                    <div>
                        <TextField
                        name="txtField1"
                        onChange={this.handleTxtFieldChange}
                        value={this.state.txtField1}
                        floatingLabelText="Database Name"
                        floatingLabelStyle={Styles.floatingLabelStyle}
                        floatingLabelFocusStyle={Styles.floatingLabelFocusStyle}
                        />
                    </div>
                </SwipeableViews>
            </div>
```

It is something along those lines and for some reason I am getting this error:
warning.js:36 Warning: Failed prop type: Invalid prop `index` of type `string` supplied to `SwipeableViews`, expected `number`.
    in SwipeableViews (created by ....)

I looked in the debugger and it was trying to switch to index 'a' or whatever you decided to type in in the handleTabChange method.

I'm not sure if this is Material UI's problem or what. I had a similar issue with something they had a while back (i was using mui 15.4) that they fixed in their most recent version (16.1). But now, it is doing something similar with the swipeable views library.
Here is the link: https://github.com/callemall/material-ui/issues/2189

I also had a handleTabChange method exaclty like what Material UI's demo had and it still gave me the same error. This also breaks the swiping functionality and you can't switch in between the tabs manually. 

Sorry if this isn't your problem but its my best guesstimate.

**Comment by oliviertassinari** [comment]
There is no `onChange` property on the `SwipeableViews` component. Use `onChangeIndex`.
