### ISSUE TITLE
Smooth quick swipe (unbounded swiping?)

### ISSUE THREAD

**Issue by steezeburger** [oliviertassinari/react-swipeable-views#186]
Has anyone been able to create a swipeable view that is unbounded? What I mean by that is, you can swipe and it will keep scrolling until the user touches again or it slows to stop, the timing presumably determined by some variable in the physics engine.

I've played around with the dampness and stiffness settings, but it still snaps to each single view. 

I understand this library uses react-motion under the hood, which is a physics spring implementation. Maybe what I'm asking about isn't currently possible with each view being a spring.

**Comment by oliviertassinari** [comment]
Sounds like you are looking for some inertial scrolling.
It's quite done the other way around now.
I mean, we set a target position and the transition is following some physic rules to get there.

**Comment by oliviertassinari** [comment]
I'm closing. It's out of the scope of the library.
