### ISSUE TITLE
GridLike: swipe on the x and y axis at the same time

### ISSUE THREAD

**Issue by dnecklesportfolio** [oliviertassinari/react-swipeable-views#187]
is it possible to swipe on the x and y axis at the same time?
like say i have a grid i want to explore

**Comment by oliviertassinari** [comment]
@dnecklesportfolio It's not possible. You can only nest swipeable views. One would be on the `x` axis while the other one would be on the `y` axis. I never had this use case in mind when designing this component.

**Comment by antsav** [comment]
really need a nested swipable view on y axis inside line of x views
like so: 
```
|   1   |   2   |   3  |
        |   2a  |
        |   2b  |
```

right now if I put 
```
<SwipeableViews>
   <div id='1' />
   <SwipeableViews axis='y'>
      <div id='2' />
      <div id='2a' />
      <div id='2b' />
   </SwipeableViews>
   <div id='3' />
</SwipeableViews>
```

it's kind of makes what i want and on position 2 vertical slide is present, but all children are stacked in first vertical slide and bottom 2 slides are just blank. 

any walk around to solve this ?

**Comment by oliviertassinari** [comment]
@antsav I'm not sure to follow the issue. I think that we should move the discussion to another issue. This one is about a new feature.
A live reproduction example with an image showing what's wrong would be great.

**Comment by oliviertassinari** [comment]
@dnecklesportfolio I'm closing the issue as I think it will require too much effort to implement. Also, it doesn't fit into the vision of the project. I'm closing.
