### ISSUE TITLE
How do I use it to make pages swipe vertically ?

### ISSUE THREAD

**Issue by moussasarr** [oliviertassinari/react-swipeable-views#188]
I have used for horizontal swipe. Not sure however how to implement vertical swiping with it ? I am not sure I understand the axis proporties. If there are the key to a vertical swipe, can you provide an example where you set the axis properties ?

**Comment by oliviertassinari** [comment]
Is this example enough https://github.com/oliviertassinari/react-swipeable-views/blob/master/docs/src/demo/DemoAxis.js?

**Comment by moussasarr** [comment]
Perfect. Thanks for your fast response.
