### ISSUE TITLE
Nested bindKeyboard not working as expected

### ISSUE THREAD

**Issue by pbellon** [oliviertassinari/react-swipeable-views#189]
As in #131 I try to use nested SwipeableViews but here using bindKeyboard utility function. However I think that the keys events are fired on both parent & child views which trigger swipe on parent element (A) when the expected behavior would be to trigger swipe on child (B) until we reach its last slide. 

![image](https://cloud.githubusercontent.com/assets/1018824/20342278/1bd19946-abea-11e6-8e1c-db99b81d1053.png)

I think this can easily be fixed by adding a boolean property `nested` to `BindKeyboard` component which would implement this behavior. At least that's the way I imagine it but maybe there's a better way to do that.  I will try to implement this behavior and submit a pull-request if you think that's a good idea.

**Comment by pbellon** [comment]
This is more complicated than expected because the issue goes in both ways. B also needs to know if it can start to handle events (i.e when it is visible) otherwise even if we're not in the slide containing B, slides will change when a key is pressed.

**Comment by oliviertassinari** [comment]
Have you investigated the `preventDefault` option on the event? I think that we should be able to address the issue that way.

**Comment by pbellon** [comment]
That what I thought first but I didn't succeed from having the event being caught by parent SwipeableView (A). I tried to call `event.preventDefault` from the `handleKeyDown` function in [bindKeyboard](https://github.com/oliviertassinari/react-swipeable-views/blob/master/src/bindKeyboard.js#L57) but it wasn't stopping propagation (`stopPropagation` is not helping either)

**Comment by oliviertassinari** [comment]
@pbellon Oh, you are right. This problem is much more interesting to solve than I thought of.
It's even harder when we realize that only nested displayed `SwipeableViews` should handle the keystroke. That mean we should have `slave` and `master` keystroke handler.
I see two ways to address this issue:
- The simplest one is on your side. You wrap the root `Swipeable` with the `bindKeyboard` HoC.
You then control all your `Swipeable` components. It's now your responsibility to handle the *root* `onChangeIndex` callback correctly to update  the right index.
- A more elegant one is at the library level. We would definitely need to rely on the context.
Each slide should inject a context bus event that notifies when it became visible and when is not.
The `bindKeyboard` HoC would also inject a context bus event. That will be used to determine which `<BindKeyboard />` component should be the master and control the child ones.

**Comment by pbellon** [comment]
Thanks for the detailed response. I will head toward option 1 :+1:

**Comment by pbellon** [comment]
I've been able to implement option 1. However the issue #131 is still not possible to fix with a similar method. I'm not sure that there can be a simple fix anyway for this similar issue: when we reach the last slide of a nested swipeable view, swiping to next slide should trigger swipe in parent view (A). 

This can be done but you have to swipe outside of child view (B). Maybe I didn't understand something in the fix you made in #131 but I don't see how to fix that.

**Comment by oliviertassinari** [comment]
> However the issue #131 is still not possible to fix with a similar method. When we reach the last slide of a nested swipeable view, swiping to next slide should trigger swipe in parent view (A). You can swipe in the parent view but you have to swipe outside of the child (B) view.

That should be working. Can you provide a reproduction test case with http://www.webpackbin.com/.

**Comment by pbellon** [comment]
This is not beautiful at all but I've been able to reproduce the issue: http://www.webpackbin.com/N1wi7xhbG

**Comment by pbellon** [comment]
I've been able to reproduce it [here](http://www.webpackbin.com/N1wi7xhbG) but only in one way: It works when I want to go on previous parent's slide but not in the opposite direction (from 2.3 to 3).

**Comment by oliviertassinari** [comment]
> but not in the opposite direction (from 2.3 to 3).

I confirm, that sounds like a regression. I'm gonna fix it.

**Comment by oliviertassinari** [comment]
@pbellon That should be good with fe6bca6c86246b960a34b0b31ca26f0a4b8e23c0.

**Comment by pbellon** [comment]
Excellent :+1: 
Thanks a lot!

**Comment by oliviertassinari** [comment]
I'm closing this issue as I don't see much value in option 2.
I don't want to bloat that lib for a use case modt people won't need. Thanks for raising that issue.
