### ISSUE TITLE
Cannot read property 'children' of null

### ISSUE THREAD

**Issue by echenley** [oliviertassinari/react-swipeable-views#19]
I am using the "Tabs with Slide Effect" pattern [here](http://www.material-ui.com/#/components/tabs) inside of a dialog. When the dialog closes, it throws the error `Cannot read property 'children' of null`. Looking at the code at [L198](https://github.com/oliviertassinari/react-swipeable-views/blob/master/src/index.js#L198), `slide` is expected to be `undefined` but in my case it is `null`.

```js
// ...
  getHeightSlide(index) {
    const slide = this.slides[index];
    // the line in question
    if (slide !== undefined) {
      const child = slide.children[0];
      if (child !== undefined) {
        return child.clientHeight;
      }
    }
    return 0;
  },
// ...
```

**Comment by oliviertassinari** [comment]
Intereseting.
Following the doc
> Note that when the referenced component is unmounted and whenever the ref changes, the old ref will be called with null as an argument. This prevents memory leaks in the case that the instance is stored, as in the first example. Also note that when writing refs with inline function expressions as in the examples here, React sees a different function object each time so on every update, ref will be called with null immediately before it's called with the component instance.

Note that when the referenced component is unmounted and whenever the ref changes, the old ref will be called with null as an argument. This prevents memory leaks in the case that the instance is stored, as in the first example. Also note that when writing refs with inline function expressions as in the examples here, React sees a different function object each time so on every update, ref will be called with null immediately before it's called with the component instance.

https://facebook.github.io/react/docs/more-about-refs.html

Alright, I should fix this!

**Comment by echenley** [comment]
@oliviertassinari That should do it, thank you!

One sort of tangentially related issue with this and material-ui, since I notice you work on both :wink:. The transform used here breaks any fields that require a fixed overlay (i.e. SelectField). The fixed overlay will be positioned covering the first slide and will be unclickable for any other slide. This I think is due to the width of the slide container being fixed and allowing the slides to overflow.

A quick fix is to add `style={ { transform: 'translate3d(0,0,0)' } }` to each slide. That creates a new context for the fixed overlay to attach to.

**Comment by oliviertassinari** [comment]
Could you try https://github.com/oliviertassinari/react-swipeable-views/pull/21 for the original issue,

**Comment by oliviertassinari** [comment]
> fixed overlay

I'm not sure I follow. What do you consider as a `fixed overlay`?

**Comment by echenley** [comment]
That PR fixes the original issue!

By "fixed overlay" I'm referring to the backdrop which you can click to dismiss the popup. It has `position: fixed` and is intended to fill the viewport. However, because this component uses `transform: translate3d()`, the backdrop of the `SelectField` component is affected by the following behavior: http://stackoverflow.com/questions/15194313/webkit-css-transform3d-position-fixed-issue.

To recreate the issue, put a select field inside of a swipeable view. Click the field and try to click away to close it. It will work inside of the first slide (if you click inside of the slide itself), but it will not work for any other slides since these are overflowing the container which the backdrop is filling. If you inspect the backdrop, it will be positioned over the first slide only, no matter which slide it originated from.

One way to fix that is to add `transform: 'translate3d(0,0,0)'` to each slide to create a new local coordinate system. It might also work to avoid overflowing slides out of the [flex container](https://github.com/oliviertassinari/react-swipeable-views/blob/master/src/index.js#L249) and set it's width to `100% * number_of_slides`, and set each child's width to `100% / number_of_slides`.

**Comment by oliviertassinari** [comment]
I see, thanks for the explanation. I'm gonna try to reproduce this issue.

**Comment by oliviertassinari** [comment]
https://github.com/callemall/material-ui/pull/2150 was merged to address your issue with the SelectField.
Just wait the next release.

**Comment by echenley** [comment]
:+1: Great, thank you so much!
