### ISSUE TITLE
Slide properties disappearing when re-rendering after a route 

### ISSUE THREAD

**Issue by abelovic** [oliviertassinari/react-swipeable-views#190]
I'm having an issue with slide height. It works great if you first load the page but if I go to another page (I'm using react-router 3.0.0) and come back it seems like only the first slide works as expected. Here is a simple sample of my swipeable view with some arbitrary heights and colors:

```jsx
<SwipeableViews 
    index={this.state.slideIndex}
    animateHeight={false}
    style={{height: 500, background: '#dedede'}}
    containerStyle={{height: '100%'}}
    onChangeIndex={ (value) => this.setState({slideIndex: value}) }>

    <div className="slide" style={{background: '#ff0000'}}>

        <div className="slide-content" style={{height: 250}}>
            Slide 1
        </div>
    </div>

    <div className="slide" style={{background: '#ff00ff'}}>

        <div className="slide-content" style={{height: 1000}}>
            Slide 2
        </div>
    </div>

    <div className="slide" style={{background: '#0000ff'}}>

        <div className="slide-content" style={{height: 2000}}>
            Slide 3
        </div>
    </div>
</SwipeableViews>
```

Now if you come back to this page all the props on slides 2 & 3 are gone (slides 2 and 3 don't have the purple and blue background but instead the grey one from the root). This does work correctly on a refresh i.e. first load. 

This is causing issues where I am trying to use height inside the slides (for example trying to use a custom scrollbar).

Is this a bug or am I doing something wrong?

**Comment by oliviertassinari** [comment]
I don't get it, that seems to work fine: http://www.webpackbin.com/E10lR9IbG.

**Comment by oliviertassinari** [comment]
I'm closing it. I don't have enough information to reproduce it. Feel free to update the playground 👍 .

**Comment by abelovic** [comment]
@oliviertassinari - I just put together a more complex sample and can't reproduce it either :( There must be something else going on in my app that is not obvious. If I do find an issue with this component (it is awesome btw) I will let you know.

http://www.webpackbin.com/EynCRTIZf

PS I have never used webpackbin before - its very cool!
