### ISSUE TITLE
Use hammer.js as for hanlde touch events

### ISSUE THREAD

**Issue by just-boris** [oliviertassinari/react-swipeable-views#195]
[Hammer.js](http://hammerjs.github.io) is a library that provides you a consistent way to handle touch gestures across all devices, including desktop.

Also, you may find useful a react-wrapper for it: https://github.com/JedWatson/react-hammerjs

That issue was created as follow up to [the comment in another issue](https://github.com/oliviertassinari/react-swipeable-views/issues/3#issuecomment-247000198)

**Comment by oliviertassinari** [comment]
@just-boris I'm not sure to understand the underlying issue. What do you want to achieve in the end?

**Comment by just-boris** [comment]
Exactly the same as @giladbr said:
> is there any chance this component would be adjusted to support "swiping" with the mouse on desktop?

Hammer.js will emit consistent events for you, so you don't need to worry about differences in platforms. Mouse drags on desktop will be converted into touch events as well. Also, I believe that issues like #164 will also be fixed, but it needs more precise check

**Comment by oliviertassinari** [comment]
Interesting, my only concern with this approach is regarding the build size and introducing a large dependency.

**Comment by j6k4m8** [comment]
I think I agree with this — the benefit of using a standardized library like hammer I _think_ outweighs the weight of the library. (Hammer is pretty well-vetted, too — so no possibility of it disappearing or changing API dramatically!)

Right now I'm trying to find workarounds to get this library to work with mouse-events. Having native hammer support would be awesome.

**Comment by oliviertassinari** [comment]
@wub Thanks for you point of view. I'm closing it for #254.

**Comment by giladbr** [comment]
Try [react-slick](https://github.com/akiran/react-slick). Very powerful, a lot of options, has swiping and many other abilities. Documentation a little lacking which may lead to integration problems, but we used it successful and boosted our site's user experience.
