### ISSUE TITLE
how continuous slide

### ISSUE THREAD

**Issue by Gmonking** [oliviertassinari/react-swipeable-views#200]
how make it continuous slide. 

eg.
tab1 => tab2 => tab3 => tab1 => tab2 ...   or   tab1 => tab3 => tab2 => tab1 => tab3 => tab2 ...

**Comment by mikehobi** [comment]
Take a lot at the virtualize example:

https://github.com/oliviertassinari/react-swipeable-views#example-with-virtualize

**Comment by oliviertassinari** [comment]
@mikehobi Thanks for the link, it can be implemented today, I'm closing this issue for #181.
