### ISSUE TITLE
Any way to go to specific slide when using Virtualize HOC?

### ISSUE THREAD

**Issue by steezeburger** [oliviertassinari/react-swipeable-views#201]
I've implemented the infinite swipe like so:

```jsx
const EnhancedSwipeableViews = virtualize(SwipeableViews);
...
slideRenderer = ({ index, key }) => {
    const { categoryCards } = this.state;
    // # of slides
    const slideLength = categoryCards.length;
    // some arithmetic to calculate index of slide
    const slideIndex = mod(index, slideLength);
    // grab slide we want
    const Slide = categoryCards[slideIndex];
    return { ...Slide, key };
}
...
<EnhancedSwipeableViews slideRenderer={this.slideRenderer}
                        resistance={true} />
```

I'm having trouble coming up with a clever way to to a specific index. I've tried calling slideRenderer directly, but this didn't seem to work. I looked through the code a bit but was having a hard time understanding how the slideRenderer worked. It looks like it loops through every index on each swipe? 

Edit: also, I believe this is in the same vein, is there a way to simply rerender the current card? I have some fancy filtering occurring and even though I recreate my swipeable cards, the sliderenderer is not called so it looks like my filters are not being applied even though the data has actually changed.

**Comment by oliviertassinari** [comment]
> I'm having trouble coming up with a clever way to to a specific index.

Have you tried the `index` property?

> Is there a way to simply rerender the current card?

Is the parent component actually rerendered? I haven't added any pure logic, nor caching calls to `slideRenderer` yet. That should be working.

**Comment by steezeburger** [comment]
Doh, `index` property works. Forgive me, I thought I had scoured the documentation.

As for the second part, it does not seem to be working this way. The parent does in fact update, but the slides do not get rerendered (nor does `slideRenderer` get called).

**Comment by steezeburger** [comment]
Closing this till I do more research into my rendering issue, but wanted to say thanks for this great library and for your quick replies to issues!

**Comment by oliviertassinari** [comment]
> The parent does in fact update, but the slides do not get rerendered (nor does slideRenderer get called).

If you find out what's going on, let me know. Thanks.
