### ISSUE TITLE
[virtualize] May hit the "last slide" when swiping fast to the left

### ISSUE THREAD

**Issue by yoadsn** [oliviertassinari/react-swipeable-views#204]
Hey,
Created this bin http://www.webpackbin.com/4kydqm7mf.
I added large padding on the slider component so slide "before" and "after" are also visible.
this shows the lagging in rendering and eventually arriving at a "last slide" which should not happen.
And here is a short screen capture of this behavior:
![capture2](https://cloud.githubusercontent.com/assets/1684709/21041957/1596e65c-bdf7-11e6-9078-0c1919ed0bf3.gif)

**Comment by oliviertassinari** [comment]
I'm adding #152 to the conversation as an early attempt to address the issue.

**Comment by yoadsn** [comment]
In the meanwhile and for readers of this problem, as @oliviertassinari suggested on #152 using a bigger 'overscanSlideCount' at the moment would make it harder to "reach the last slide" within the animation time and so would reduce the probability of this problem to occur.

**Comment by yoadsn** [comment]
@oliviertassinari Reading the suggestion, which makes sense but also is a big effort. I wonder, if just to overcome this bug there could be a workaround. After all, if the `onTransitionEnd` callback would have been called the `setWindow` would resolve the problem.

Is it too ugly to create a timer which is scheduled upon every index change and cleared when `onTransitionEnd` is called or when another index change is invoked - and if this timer is gets to fire (after a delay which is say 1.5X the animation delay) we can use that to just do a `setWindow` that would "add" the missing slides.

I think it's OK to arrive at an end, and "add" the missing slides after some time.. this would give the impression of lazy loading to the user and may even be more elegant then actually trying to have slides coming in from the left no matter the speed and distance of swipe..

It's a naaive suggestion but I would take that without thinking twice over the existing behavior.

**Comment by oliviertassinari** [comment]
> Is it too ugly to create a timer

That was my first implementation, but then I had issues like this one to fix #174.
I'm still not sure how we should be solving that issue.
http://www.apple.com/ approach is interesting. I'm gonna investigate https://github.com/animatedjs/animated.

**Comment by oliviertassinari** [comment]
> eventually arriving at a "last slide"

That should be fixed with 9eee35972d5be26fd0f1419a54b60da3170ae1ee.

**Comment by oliviertassinari** [comment]
> using a bigger overscanSlideCount at the moment would make it harder to "reach the last slide"

I feel like adding an `overscanSlideCountLeft` property would be the simplest fix for that issue.
I can only think about two alternatives:
- Implementing that logic https://github.com/oliviertassinari/react-swipeable-views/pull/152#issuecomment-249381126 on all the platform, that's quite some work
- making each slide absolute positioned. That's basically what [react-virtualized](https://github.com/bvaughn/react-virtualized) is doing. But that raise some other issues. That layout needs some specific care as no longer determined by the children.

**Comment by yoadsn** [comment]
> I feel like adding an overscanSlideCountLeft property would be the simplest fix
With some grief, I tend to agree.
The next best thing is absolute positioning - I will dive deeper into "react-virtualized" to see how it's implemented there.
