### ISSUE TITLE
0.8.3 Duplicate module name: react-native-vector-icons

### ISSUE THREAD

**Issue by mschipperheyn** [oliviertassinari/react-swipeable-views#207]
I use react-native-vector-icons directly in my project. After upgrading to 0.8.3, I got this

	Failed to build DependencyGraph: @providesModule naming collision:
	  Duplicate module name: react-native-vector-icons
	  Paths: /[...]/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /[...]/node_modules/react-swipeable-views/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

	This error is caused by a @providesModule declaration with the same name across two different files.
	Error: @providesModule naming collision:
	  Duplicate module name: react-native-vector-icons
	  Paths: /[...]/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /[...]/node_modules/react-swipeable-views/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

	This error is caused by a @providesModule declaration with the same name across two different files.
		at HasteMap._updateHasteMap (/[...]/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:159:13)
		at p.getName.then.name (/[...]/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:134:31)
	~
	Process terminated. Press <enter> to close the window

**Comment by oliviertassinari** [comment]
I don't have any `react-native-vector-icons` reference in the project. I'm wondering what's going on.

**Comment by oliviertassinari** [comment]
I have published `react-swipeable-views-native`.
