### ISSUE TITLE
Why isn't react-motion included in the package.json?

### ISSUE THREAD

**Issue by williamle8300** [oliviertassinari/react-swipeable-views#208]
I'm not a pro at using npm... but why isn't react-motion included as a "dependency"? That would make it installation more streamlined wouldn't it?

**Comment by oliviertassinari** [comment]
What you proposed was the original solution. But, react-motion is only a peer dependency for the browser platform. It simpler removing it
Have a look at https://github.com/oliviertassinari/react-swipeable-views/issues/100
