### ISSUE TITLE
[question] Dynamically disable swiping

### ISSUE THREAD

**Issue by sprelewicz2441** [oliviertassinari/react-swipeable-views#211]
My question is - is there a way to disable it dynamically? 

I am using it in conjunction with hammer.js. When I detect a pinch touch action, I want to disable any swipe views, and only allow more pining unless they are on a single slide view

**Comment by oliviertassinari** [comment]
Have you tried controlling the component and rejecting the `onIndexChange` callback when it's not relevent?

**Comment by oliviertassinari** [comment]
I'm not sure what you want to achieve.
We are also exposing the `onTouchStart` / `onTouchMove` / `onTouchEnd` callbacks.
They can be used if you need a lower level API. I'm closing this question.
