### ISSUE TITLE
react-native should not be a dependency

### ISSUE THREAD

**Issue by mschipperheyn** [oliviertassinari/react-swipeable-views#212]
Your package.json lists react-native as a dependency leading to a naming conflict. You should probably consider listing react-native as an engine in package.json

**Comment by oliviertassinari** [comment]
> dependency leading to a naming conflict

What naming conflict are you refering to?
Do you want to submit a PR?

**Comment by mschipperheyn** [comment]
You use react-native and react as direct dependencies which means they get downloaded in the react-swipeable-views node_modules folder. This can lead to problems, and in my case is. What you should do is remove these from the dependency list, since they are already in the environment. 

React-native for instance references react as a "peerDependency", not as a "dependency"

**Comment by oliviertassinari** [comment]
> This can lead to problems, and in my case is.

What's your issue?
I think that we should be releasing the native version under a different npm package to simplify things.

**Comment by mschipperheyn** [comment]
Well, I first got errors with react-native complaining about duplicate modules. I then removed the react-native library that existed in react-swipeable-views/node_modules folder. That solved that.

**Comment by oliviertassinari** [comment]
I have published `react-swipeable-views-native`

**Comment by emaillenin** [comment]
@oliviertassinari material-ui/docs is using `react-swipeable-views` (https://github.com/callemall/material-ui/blob/master/docs/package.json). So the naming conflict will occur when you run `material-ui/docs` in react native. This is the error:

```
Error building DependencyGraph:
 Error: Naming collision detected: /Users/lenin.rajasekaran/codebases/material-ui/docs/node_modules/react-swipeable-views/node_modules/react-native/Libraries/Renderer/src/renderers/shared/stack/event/eventPlugins/TouchHistoryMath.js collides with /Users/lenin.rajasekaran/codebases/material-ui/docs/node_modules/react-native/Libraries/vendor/react/browser/eventPlugins/TouchHistoryMath.js
    at HasteMap._updateHasteMap (/Users/lenin.rajasekaran/codebases/material-ui/docs/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:123:13)
    at /Users/lenin.rajasekaran/codebases/material-ui/docs/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:94:28
    at tryCallOne (/Users/lenin.rajasekaran/codebases/material-ui/docs/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/lenin.rajasekaran/codebases/material-ui/docs/node_modules/react-native/node_modules/promise/lib/core.js:123:15
    at flush (/Users/lenin.rajasekaran/codebases/material-ui/docs/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

Similar issues - https://github.com/d-a-n/react-native-webbrowser/issues/2#issuecomment-246318298

**Comment by oliviertassinari** [comment]
> So the naming conflict will occur when you run material-ui/docs in react native

It's not suppose to be runned with react-native. But upgrading the dependency should fix that issue.

**Comment by quadsurf** [comment]
@mschipperheyn i tried doing as you suggested, with:
`"engine": {
    "react": "15.3.1",
    "react-native": "0.32.1"
  },`

but get the following:
npm WARN react-native-orientation@1.17.0 requires a peer of react-native@>=0.5 but none was installed.
npm WARN react-native-popover@0.2.0 requires a peer of react-native@>=0.4.4 but none was installed.
[and many other 3rd-party libraries that are peer dependent on react-native in node_modules]
Error: Cannot find module '.../node_modules/react-native/local-cli/cli.js'
