### ISSUE TITLE
React Native: "Unable to resolve module react-swipeable-views-utils"

### ISSUE THREAD

**Issue by binchik** [oliviertassinari/react-swipeable-views#215]
Hi, thanks for your work!

I updated the react-swipeable-views to 0.9.1 and changed the import statements to: 

```jsx
import { virtualize } from 'react-swipeable-views-utils';
import SwipeableViews from 'react-swipeable-views-native';
```

The packager is unable to resolve `react-swipeable-views-utils` module. I am using the native version.

I also tried to install `react-swipeable-views-utils` as a separate package, the packager is unable to resolve `react-addons-shallow-compare` then. Installing the shallow-compare module gives me an "Unable to resolve `keycode`" error.

**Comment by oliviertassinari** [comment]
Oups, I haven't moved the dependencies in the right packages.

**Comment by oliviertassinari** [comment]
Should be fixed by https://github.com/oliviertassinari/react-swipeable-views/commit/fd266a1f91e1ecc217fd71256abd908067b04654.

**Comment by oliviertassinari** [comment]
I confirm, I have tried it, it's 💯 % fixed.

**Comment by habib786** [comment]
Still having this issue, can you guide me?

**Comment by yacut** [comment]
@habib786 please try to clear cache and reinstall npm packages:

```sh
watchman watch-del-all
rm -rf ./node_modules
rm -rf ~/.rncache
yarn install
```
