### ISSUE TITLE
Should install react-swipeable-views-utils in order to use virtualize? (after the package changes)

### ISSUE THREAD

**Issue by yoadsn** [oliviertassinari/react-swipeable-views#217]
Now that the packages are separate.
According to the documentation it is unclear - When wanting to use "virtualize" (for example) - does one needs to 
`npm i --save react-swipeable-views-utils`
?
The "utils" package is not a dependency of "core" or the top level package...

Thanks for clearing it up!

**Comment by oliviertassinari** [comment]
The graph of dependencies between the packages is the following:
- 1: `react-swipeable-views-core` (core modules shared between the different packages)
- 2: `react-swipeable-views` **[1]** (browser implementation of the `<SwipeableViews />`)
- 3: `react-swipeable-views-native` **[1]** (native implementation**s** of the `<SwipeableViews />`)

- 4: `react-swipeable-views-utils` **[1]** (Higher order Component that can be used with the three different implementations available)

> Should install react-swipeable-views-utils in order to use virtualize?

Yes, you should. The native users are forced to do it right, for the browser users, I have kept the [old modules](https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views/src/autoPlay.js), just adding a deprecation comment.
But it looks like I have forgotten to add `react-swipeable-views-utils` in  https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views/package.json#L25 to make it work 🙈 .

**Comment by oliviertassinari** [comment]
I'm gonna
- document what each packages is for
- Add a deprecation warning when importing the old HoC packages
- Add the missing dependency
