### ISSUE TITLE
[Autoplay] Problem with onChangeIndex event / controlled

### ISSUE THREAD

**Issue by sylvainbaronnet** [oliviertassinari/react-swipeable-views#218]
hello,

When I use `onChangeIndex` on the `AutoPlaySwipeableViews`, the autoplay stop working (even if I do nothing onChangeIndex), `onSwitching` works fine...

**Comment by oliviertassinari** [comment]
Could you provide a reproduction example. That would help. Thanks :).

**Comment by oliviertassinari** [comment]
Actually, I think that I get your issue. I'm considered the component controlled as soon as a `onChangeIndex` property is provided: https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views-utils/src/autoPlay.js#L139-L145.
I think that it should be the `index` that trigger that behavior.

**Comment by sylvainbaronnet** [comment]
yes for me it doesn't make sense to assume the component is "controlled" since `onChangeIndex` is just an event. My guess is we can just remove the else and do the setState everytime.

I'm not sure how (or if) you should detect the component is controlled, maybe an explicit method like `stopAutoplay` is enough

**Comment by sylvainbaronnet** [comment]
Thank you, can you publish a new version ?

**Comment by oliviertassinari** [comment]
I'm gonna do that tomorrow.

**Comment by danmatlam** [comment]
Can I set a timer on autoplay?... Im using it, it´s awesome but still lookin for time setting.
