### ISSUE TITLE
Infinite swipe support?

### ISSUE THREAD

**Issue by pke** [oliviertassinari/react-swipeable-views#22]
Would it be difficult to add infinite swipe support? Like wrap around?

**Comment by oliviertassinari** [comment]
As responded here https://github.com/brentvatne/react-native-scrollable-tab-view/issues/44 for react-native.
I would say that you can use https://github.com/orgsync/react-list on top of the `SwipeableView` component.

**Comment by jardakotesovec** [comment]
@pke I would be also interested in infinite swipe support (meaning that last slide goes to first one and vice versa) - have you managed to solve it?

**Comment by pke** [comment]
not yet @jardakotesovec. I am working on other parts of the app, atm. Will report back here if I find a solution.

**Comment by dbuarque** [comment]
+1

**Comment by jjhargreaves** [comment]
+1

**Comment by ambewas** [comment]
Just to provide a temporary solution for anyone looking at this; I've managed to implement this infinite swipe using the onSwitching callback.

Note that this only works if you set `resistance` prop to true. Otherwise the index passed in `onSwitching` will never go below/above the lower/upper slide index .

~~~
  _handleSwitching(index, moveState) {
    // check if we are moving the last tab further. If so, we want to scroll back to the first slide.
    // and vice-versa.
    const trigger = .1; // don't trigger slide change on small move
    const furtherThanLastTab = index > (this.props.children.length - 1 + trigger);
    const furtherThanFirstTab = index < (0 - trigger);

    switch (moveState) {
    case 'move':
      // save sliding behaviour on upper scope
      if (furtherThanLastTab) {
        slidingFurtherThanLastSlide = true;
      } else {
        slidingFurtherThanLastSlide = false;
      }

      if (furtherThanFirstTab) {
        slidingFurtherThanFirstSlide = true;
      } else {
        slidingFurtherThanFirstSlide = false;
      }
      break;
    case 'end':
      if (slidingFurtherThanLastSlide) {
        this._setActiveTab(0);
      } else if (slidingFurtherThanFirstSlide) {
        this._setActiveTab(this.props.children.length - 1);
      }
      break;
    default:
      break;
    }
  },
~~~

In `_setActiveTab` I'm saving an index to the state; which is passed to the `index` prop on <SwipeableViews>

**Comment by theogravity** [comment]
Unclear where `slidingFurtherThanLastSlide` should be defined? looks like it'd be an instance member

**Comment by theogravity** [comment]
also i think this can be simplified

```
      if (furtherThanLastTab) {
        slidingFurtherThanLastSlide = true;
      } else {
        slidingFurtherThanLastSlide = false;
      }

      if (furtherThanFirstTab) {
        slidingFurtherThanFirstSlide = true;
      } else {
        slidingFurtherThanFirstSlide = false;
      }
```

to

```
          this.slidingFurtherThanLastSlide = Boolean(furtherThanLastTab) || Boolean(furtherThanFirstTab)
```

**Comment by theogravity** [comment]
I ended up creating the instance vars for `slidingFurtherThanFirstSlide` and `slidingFurtherThanLastSlide` and simplified 

```
      // save sliding behaviour on upper scope
      if (furtherThanLastTab) {
        slidingFurtherThanLastSlide = true;
      } else {
        slidingFurtherThanLastSlide = false;
      }

      if (furtherThanFirstTab) {
        slidingFurtherThanFirstSlide = true;
      } else {
        slidingFurtherThanFirstSlide = false;
      }
```

to

```
        this.slidingFurtherThanLastSlide = Boolean(furtherThanLastTab)
        this.slidingFurtherThanFirstSlide = Boolean(furtherThanFirstTab)
```

**Comment by ambewas** [comment]
I declared `slidingFurtherThanLastSlide` outside the component scope, but your solution looks good as well, I'll try it out later!

**Comment by oliviertassinari** [comment]
I have tag this issue as a priority. I more or less know how to address it. I will try to find some time to work on it. I'm gonna have a look at the `react-virtualize' API to provide a clean API.

**Comment by jadus** [comment]
Great ! Any idea when we can test this ? I have to deal with hundreds of slides and will have to use virtualized if I want it to work.

**Comment by oliviertassinari** [comment]
@jadus I have just started. I plan to provide it as an HOC with the following API:
```js
/**
 * Responsbile for rendering a row given an index.
 * ({ index: number }): node.
 */
slideRenderer: PropTypes.func.isRequired,

/**
 * Number of rows in list.
 */
slideCount: PropTypes.number.isRequired,

/**
 * Number of slide to render above/below the visible bounds of the list.
 */
overscanSlideCount: PropTypes.number.isRequired,
```
