### ISSUE TITLE
Tab content disappearing when it has seen once on firefox mobile

### ISSUE THREAD

**Issue by wethil** [oliviertassinari/react-swipeable-views#220]
I have four tabs and four content connected. When i use chrome mobile, everything is okay but on firefox mobile, tab content is disappearing after 20 seconds and doesn't appear until i touch to screen.  There is no problem on firefox desktop. Thanks for help.

**Comment by oliviertassinari** [comment]
Could you provide a reproduction test case, using a tool like http://www.webpackbin.com/ ? That would help a lot, thanks.

**Comment by oliviertassinari** [comment]
I'm closing the issue, missing a reproduction test case so I can investigate.
