### ISSUE TITLE
[virtualize] will cards outside of viewport appear instantly or is there a delay

### ISSUE THREAD

**Issue by dnecklesportfolio** [oliviertassinari/react-swipeable-views#227]
I am using the virtualized rsv. I believe any cards not in the viewport will not be rendered. So if I shrink the entire grid the ones off screen should come into view right or will there be a delay when it appears on screen.

The shrinking of the grid simulates a ZOOM OUT effect where the user will be see able to the cards on the grid. Think of it is viewing One checker square to viewing several squares at once.

Thoughts?

**Comment by oliviertassinari** [comment]
I don't understand, that's the issue?

**Comment by dnecklesportfolio** [comment]
Actually, I just noticed that my issue is similar to #204, (instead of moving on the x axis, my project appears in both axis a checkerboard grid. I will look at the suggestion you gave him and see if it works for me.. And I will also create a code sample. I guess you can close it for now.
