### ISSUE TITLE
Using negative positioning causes elements to not be swipeable 

### ISSUE THREAD

**Issue by scoot1585** [oliviertassinari/react-swipeable-views#228]
So the issue is that basically if you use negative positioning on an element, the parent element will not be swipeable right, because it thinks it should be able to natively scroll.  

The problem code is here https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views/src/SwipeableViews.js#L113 more specifically  `element.scrollWidth > element.clientWidth`

If you have negative right positioning (absolute, relative, or negative margin) it will make the parent's scrollWidth greater than the clientWidth.  Having negative left doesn't affect scrollWidth

Below is my sample code where you can't swipe from slide 2 to slide 3 if you try swiping on the tab list nav items box at the top.  In the below scenario, the tablist scrollWidth is 305px and the clientWidth is 290px causing it to think it is natively scrolling, but it isn't.  I even had a second example of the issue where i had to -1px for image alignments, which again broke it.

```js

const styles = {
    slideContainer: {
        height: 100,
    },
    slide: {
        padding: 15,
        minHeight: 100,
        color: '#fff',
    },
    slide1: {
        backgroundColor: '#FEA900',
    },
    slide2: {
        backgroundColor: '#B3DC4A',
    },
    slide3: {
        backgroundColor: '#6AC0FF',
    },
    slide2tab: {
        position: 'relative',
    },
    slide2tabnav: {
        position: 'absolute',
        top: -15,
        left: -15,
        right: -15,
        height: 30,
        backgroundColor: '#3f3'
    }
};

render(
    <SwipeableViews>
        <div style={Object.assign({}, styles.slide, styles.slide1)}>
            slide n°1
        </div>
        <div style={Object.assign({}, styles.slide, styles.slide2)}>
            <div className="tablist" style={Object.assign({}, styles.slide2tab)}>
                <div className="tablist-nav" style={Object.assign({}, styles.slide2tabnav)}>
                    Nav items
                </div>
                <div className="tablist-content">
                    Nav content
                </div>
            </div>
        </div>
        <div style={Object.assign({}, styles.slide, styles.slide3)}>
            slide n°3
        </div>
    </SwipeableViews>,
    document.getElementById('root')
);
```
I wasn't sure how to quickly fix this without breaking more functionality for native scrolling, but let me know if you need anything else from me.

**Comment by oliviertassinari** [comment]
@scoot1585 Thanks for raising that issue. Following http://stackoverflow.com/questions/16688571/getting-a-divs-scrollwidth-when-it-has-an-absolute-positioned-child-div, I couldn't find any better solution than disabling the feature in that case.
