### ISSUE TITLE
Unable to resolve module on React Native

### ISSUE THREAD

**Issue by florianbepunkt** [oliviertassinari/react-swipeable-views#231]
Using RN 0.40.0 and installing via `npm install --save react-swipeable-views-native`
 I get the following error

Unable to resolve module 'react-swipeable-views' from ..

Installing directly from this repo also fails.

**Comment by oliviertassinari** [comment]
Do you have the stack trace? That would help, thanks!

**Comment by florianbepunkt** [comment]
this might be related to the install instructions:

on github it reads `npm install --save react-swipeable-views-native` while on npm it reads `npm install --save react-swipeable-views`

which one is correct? the former throws the error descrbibed above, the latter throws a different error when importing and using the component (see screenshot below)
![simulator screen shot 15 01 2017 17 01 21](https://cloud.githubusercontent.com/assets/8314202/21964010/48affa5a-db44-11e6-99c2-85950faaf34e.png)

**Comment by oliviertassinari** [comment]
`npm install --save react-swipeable-views-native` is correct have a look at the [package structure](https://github.com/oliviertassinari/react-swipeable-views#packages-stucture) for more detail.

**Comment by florianbepunkt** [comment]
@oliviertassinari Alright, thank you!
