### ISSUE TITLE
Touch Move Lag

### ISSUE THREAD

**Issue by Phaze1D** [oliviertassinari/react-swipeable-views#232]
You seem to have place a setState() inside your touch move event. 

`this.setState({
      displaySameSlide: false,
      isDragging: true,
      indexCurrent: index,
    }, () => {
      if (onSwitching) {
        onSwitching(index, 'move');
      }
    });
`

This tends to cause some very laggy touch event, especially with large views. I haven't seen all the code but you could add a `if(!this.state.isDragging) {...}` so that it is only called once during the touch move events.

**Comment by oliviertassinari** [comment]
> You seem to have place a setState() inside your touch move event.

We use that `setState` to update the view. That's a tradeoff use to simplify the implementation.
We could be more performance by using a data binding between the move events and the applied style.
Adding a *pure* logic in the slide view solve 80% of the performance issue. Try that first.
If that still not acceptable, try the `virtualize` Higer-order Component.
And if that still not good enough. A pull request is welcome 😄 .

**Comment by aostrander-source** [comment]
@oliviertassinari I am beginning to run into this performance issue as well. I see you recommend using "pure logic" in the [documentation](https://react-swipeable-views.com/getting-started/usage/#performance-on-browser) as well, but I'm not certain what you mean by that. Would you consider adding an example?
