### ISSUE TITLE
Unable to set view to 100% height

### ISSUE THREAD

**Issue by hackingbeauty** [oliviertassinari/react-swipeable-views#233]
Hello,

I am unable to set each swipeable view to a height of 100%.  I would like each swipeable view to have the height of its container.

Is there a way to do this?

**Comment by oliviertassinari** [comment]
Did you had a look at the source code of the demos? For instance the [DemoSimple](https://github.com/oliviertassinari/react-swipeable-views/blob/master/docs/src/demo/DemoSimple.js).

**Comment by hackingbeauty** [comment]
In the source code for DemoSimple, minHeight is 100 which sets a value of 100px for min-height on the swipeable view.

However, I need the swipeable view to have a height of 100%, the full height of the container.

Is there another demo that demonstrates how to do this?

**Comment by oliviertassinari** [comment]
> I need the swipeable view to have a height of 100%

I don't see where it's the issue. You can add a `height: 100%` or apply the height of the container to the slide themselves. Have a look at the properties documentation/DOM structure/source. You should be able to customize anything you need.

**Comment by idangozlan** [comment]
I bumped into the same issue.
Is there any way to set style of the root element? (the one that holds the `overflow-x: hidden`)?

**Comment by idangozlan** [comment]
nvm, find `style` attribute of the `SwipeableViews`

**Comment by FunMiles** [comment]
I don't know why this was closed before a solution was given.
I have a solution for those who find this thread from a google search and still are puzzled:

There is another useful property to `SwipeableViews`: `containerStyle`. Setting `containerStyle={ {height: '100%'} }` will get you the container to be full height.
