### ISSUE TITLE
onTransitionEnd not firing in Firefox

### ISSUE THREAD

**Issue by hannesj** [oliviertassinari/react-swipeable-views#234]
The event name reported by dom-helpers does not exist in Firefox, and standard `transitionend` should be used instead.

See https://github.com/react-bootstrap/dom-helpers/issues/17 for more details

**Comment by stevewillard** [comment]
Ran into this issue too. Is there a version that I can downgrade to, which react-swipeable-views works in Firefox?

**Comment by oliviertassinari** [comment]
@stevewillard You can revert back to `v0.9.3`.

**Comment by oliviertassinari** [comment]
It should be fixed now.

**Comment by hannesj** [comment]
I think you would need to merge and release #237 in order to guarantee that the issue is fixed. Eg. yarn will not update dependencies unless specifically instructed.

**Comment by oliviertassinari** [comment]
I'm on it.

**Comment by stevewillard** [comment]
Thank you!
