### ISSUE TITLE
animateHeight after swipe

### ISSUE THREAD

**Issue by seleckis** [oliviertassinari/react-swipeable-views#235]
Is it possible to set animateHeight after slide has finished swiping, not while swiping? May be some delay or whatever?

**Comment by oliviertassinari** [comment]
We don't provide any API to do that. I guess it could be hacked away by adding a [transition-delay](http://www.w3schools.com/cssref/css3_pr_transition-delay.asp) property. I'm not sure how it's gonna behave.

**Comment by seleckis** [comment]
The problem is, that on iPhone swipe animation is a bit twitchy when animateHeight is set. So I'm looking for solution for this issue.

**Comment by oliviertassinari** [comment]
I'm closing that issue. Feel free to post the solution here if you find one. Hopefully, that will help others.

**Comment by damianobarbati** [comment]
@seleckis how did you solve this?

**Comment by seleckis** [comment]
> @seleckis how did you solve this?

Dropped swipeable-views and implemented own solution using react-use-gestures hook useDrag and css.
