### ISSUE TITLE
[proposal] Apply a more precise transform value

### ISSUE THREAD

**Issue by tomvdv** [oliviertassinari/react-swipeable-views#236]
CSS transforms are rounded to whole percentages (https://github.com/oliviertassinari/react-swipeable-views/blob/f5bca0ce61e34919e6e88c660978d531df9e4263/packages/react-swipeable-views/src/SwipeableViews.js#L723). 
While this is negligible for small displays, the larger the display, the more jittery the drag becomes. For example, across a 1024px axis the minimum increment size is ~10px, which can be perceived as a low frame-rate when dragging slowly. 

A more precise transform value (even just 1 decimal point) greatly improves the user experience.
The current demos apply highly accurate percentage values, suggesting that this is a regression.

**Comment by oliviertassinari** [comment]
@tomvdv I'm all in to remove that `Math.round`. I don't think that we need it.
