### ISSUE TITLE
Flow error

### ISSUE THREAD

**Issue by echenley** [oliviertassinari/react-swipeable-views#240]
![screen shot 2017-02-07 at 6 00 42 pm](https://cloud.githubusercontent.com/assets/6344219/22717238/86af431a-ed5f-11e6-8433-2883e26ae8a2.png)

React Swipeable Views version: 0.10.5
Flow version: 0.38.0

Temporary fix is to add `.*/node_modules/react-swipeable-views/.*` to the [ignore] section in .flowconfig

**Comment by oliviertassinari** [comment]
I have been disabling flow lately as not providing a good enough value/cost ratio.
Oups, I'm gonna fix that issue. It's coming from that [line](https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views/src/SwipeableViews.js#L33).
