### ISSUE TITLE
rtl support

### ISSUE THREAD

**Issue by sstubbs** [oliviertassinari/react-swipeable-views#243]
This does not seem to work properly when direction is set to rtl.

**Comment by leMaik** [comment]
To reproduce this, just visit http://oliviertassinari.github.io/react-swipeable-views/ and add `direction: rtl` to the body. It looks fine at first, but try swiping to a different tab.

**Comment by sstubbs** [comment]
I can confirm I get the same issue.

**Comment by oliviertassinari** [comment]
I have reproduced the issue. I don't see better option than advising users to use the direction reverse property. Does that work for you?

**Comment by sstubbs** [comment]
I have tried adding axis={['x-reverse']} with direction rtl and it still seems to be broken.

**Comment by sstubbs** [comment]
I get similar behaviour with axis={"y"} and axis={"y-reverse"} even with direction set to ltr. It seems to show them all on first slide then nothing on the next two. I wonder if this is related.

**Comment by oliviertassinari** [comment]
The following example seems to work fine:
```jsx
// @flow weak

import React from 'react';
import SwipeableViews from 'react-swipeable-views';

const styles = {
  root: {
    direction: 'ltr',
  },
  slide: {
    padding: 15,
    minHeight: 100,
    color: '#fff',
    direction: 'rtl',
  },
  slide1: {
    backgroundColor: '#FEA900',
  },
  slide2: {
    backgroundColor: '#B3DC4A',
  },
  slide3: {
    backgroundColor: '#6AC0FF',
  },
};

const DemoRTL = () => (
  <SwipeableViews axis="x-reverse" style={styles.root}>
    <div style={Object.assign({}, styles.slide, styles.slide1)}>
      slide n°1
    </div>
    <div style={Object.assign({}, styles.slide, styles.slide2)}>
      slide n°2
    </div>
    <div style={Object.assign({}, styles.slide, styles.slide3)}>
      slide n°3
    </div>
  </SwipeableViews>
);

export default DemoRTL;
```
![fevr -15-2017 23-53-44](https://cloud.githubusercontent.com/assets/3165635/22999102/072fc4c6-f3da-11e6-98a9-2bd803956eec.gif)


I think that I'm gonna have to set `direction: 'ltr',` internally and let users handling the right properties on their side. Would that work for you? I can't see a better solution.

**Comment by leMaik** [comment]
@oliviertassinari Is there a way to only set the direction for the root element and apply the inherited direction to the slides so that it wouldn't be required to re-specify the direction?

**Comment by sstubbs** [comment]
I confirm setting the direction of the root to ltr and the slides to rtl works.

**Comment by oliviertassinari** [comment]
@leMaik I think that you can try the `containerStyle` property.

**Comment by aliamiri1380** [comment]
i have a `<body>` with a `direction:rtl` property
and here i added a className `.swipper` (or whatever) to `<SwipeableViews>` tag and added this part in css file

```
.swipper, .swipper .react-swipeable-view-container{
        direction: ltr !important
}
```
then all fixed
