### ISSUE TITLE
Add option to disable scroll check in getDomTreeShapes

### ISSUE THREAD

**Issue by scoot1585** [oliviertassinari/react-swipeable-views#244]
So the problem I mentioned in #228 is still a problem for me.  The example I gave I meant to be more of an example, than the literal use case for the problem.  So below I'll detail the issues and then what I propose for a fix (spoiler alert, it is in the title)

1. Checking the element's position using `element.style.position` will only work if the style is inline.  My style, and I assume other peoples', will be assigned via CSS properties.  And because of that, you will have to instead use getComputedStyle() to get whether an element is truly absolute positioned.
2. Even if problem 1 is fixed, it may be a absolute positioned after pseudo element that may be causing the incorrect calculation as a sibling.  and would not be triggered in your catch because it is not in the DOM tree that you will traverse up.  It is a sibling to what you clicked in and so you would never have found that absolute positioned item that is causing the "scroll like" values.

ex for problem 2 if the ::after pseudo elements were absolute positioned with negative values like #228 talked about and you tried swiping on collapsible <content> it won't work:
```
div#con
	div#collapsible
		div#collapseHeader
		div#collapseContent
			<content>
			::after
	div#collapsible
		div#collapseHeader
		div#collapseContent
			<content>
			::after
```

So based on those two situations, I think it just comes down to, I want full responsibility for whether this check should even happen.  I 100% know I wont have scrolling situations and so I just want to disable this check.  I've already done a simple test locally and always just defaulting to true here https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views/src/SwipeableViews.js#L155 and it worked fine

So I hope you can add in a configuration option like `disableDomTreeShapeCheck` or something similar and leave the responsibility for not having content scrolling to the developer.

Let me know if you have any questions!

**Comment by oliviertassinari** [comment]
> something similar and leave the responsibility for not having content scrolling to the developer.

That sounds like a good idea to add a `ignoreNativeScroll` property that would ignore native scroll.
That would solve your issue, but more important, that's a behavior that user might expect.

**Comment by scoot1585** [comment]
thanks for the quick fix! appreciate it
