### ISSUE TITLE
[virtualize] [question] renders all slides, not just current + overscan?

### ISSUE THREAD

**Issue by tconroy** [oliviertassinari/react-swipeable-views#253]
Hey there,

Fantastic components, really enjoying this! Thank you for providing it to the community. :)

This is likely a simple misunderstanding on my part, but I'm having an issue with the virtualized SwipeableViews. 

I only want to render the current slide + the immediate previous/next slides (overscan). However, I noticed as you continue to swipe, all previous slide indexes remain in the DOM.

see this ( very simplified ) demo:

```jsx
import React from 'react'
import SwipeableViews from 'react-swipeable-views'
import { virtualize } from 'react-swipeable-views-utils'

const VirtualizeSwipeableViews = virtualize(SwipeableViews)

function slideRenderer ({ index, key }) {
  switch (index) {
    case 0:
      return (
        <div key={key}>
          First slide!
        </div>
      )
    case 1:
    return (
      <div key={key}>
        Second slide!
      </div>
    )
    case 2:
    return (
      <div key={key}>
        Third slide!
      </div>
    )
    case 3:
    return (
      <div key={key}>
        Fourth slide!
      </div>
    )
    case 4:
    return (
      <div key={key}>
        Fifth slide!
      </div>
    )
    case 5:
    return (
      <div key={key}>
        Sixth slide!
      </div>
    )
    case 6:
      return (
        <div key={key}>
          Seventh slide!
        </div>
      )
  }
}

class HomeView extends React.Component {
  state = {
    index: 0
  }
  handleChangeIndex = (index) => {
    this.setState({ index })
  }
  render () {
    return (
      <VirtualizeSwipeableViews
        resistance
        index={this.state.index}
        onChangeIndex={this.handleChangeIndex}
        slideRenderer={slideRenderer}
        slideCount={7} // total number of slides
        overscanSlideCount={1} // number before/after current to render
      />
    )
  }
}

export default HomeView
```

Say I swipe to index 3, I would expect only index 2, 3 and 4 to be rendered to the DOM -- the current slide, +1/-1 from overscan.

However, index 0, 1, 2, 3, and 4 are rendered.

Again, this is probably a simple configuration issue on my end, but I'm curious to hear how I would go about implementing this behavior?

Thank you again for a great library! :-)

**Comment by oliviertassinari** [comment]
Thanks for the example!
The seen behavior is indeed the expected one.

![fevr -24-2017 13-50-59](https://cloud.githubusercontent.com/assets/3165635/23304141/79e08a36-fa98-11e6-9e62-efa1ddd99aea.gif)

We have at most 5 slides rendered. We have the following snapshot once we change the current display slide:
1. a [left offset](https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views-utils/src/virtualize.js#L9)
2. the right overscan slide
3. the old current slide
4. the new current slide
5. the right overscan slide

Once the transition is finished, you get 4 slides with the following snapshot:
1. a [left offset](https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views-utils/src/virtualize.js#L9)
2. the right overscan slide
3. the current slide
4. the right overscan slide

That extra first slide is deeply linked to #204. I think that we should allow users to customize the left and right `overscanSlideCount` independently.

**Comment by oliviertassinari** [comment]
I'm closing it for #204.
