### ISSUE TITLE
[browser] Support Mouse Events

### ISSUE THREAD

**Issue by artsx** [oliviertassinari/react-swipeable-views#254]
Hello, your demos don't work under firefox 51.0.1 mac and Safari 9 mac desktop.
Is this normal? Because you say that these browsers are supported.
Only clicks on tabs and bullets work

No worries for chrome

![fevr -24-2017 13-33-16](https://cloud.githubusercontent.com/assets/7711803/23303677/c17cff58-fa95-11e6-803b-26ff257169e8.gif)

**Comment by oliviertassinari** [comment]
The component is only intended for touchscreens. We don't handle mouse events nor pen ones.
#164 suggest supporting the Pointer Events API. It's quite a new API not supported [everywhere](https://developer.mozilla.org/en-US/docs/Web/Events/pointerdown). 

This issue sounds to me as a feature request: make the swipe work with a mouse.

**Comment by artsx** [comment]
Yes it's a good idea, I had not thought it was only for touchscreens.

It would be appreciable also to have a props which allows to add the dots automatically also :P

Thanks for your quick return !

Nice plugin !
