### ISSUE TITLE
[browser] Native scroll prevented on iOS Safari

### ISSUE THREAD

**Issue by jmheik** [oliviertassinari/react-swipeable-views#257]
On iOS Safari native scroll gets blocked by call of event.preventDefault() when scrolling direction is same than swipe direction and momentum scrolling is enabled (-webkit-overflow-scrolling: touch;).  

This can be reproduced by adding "WebkitOverflowScrolling: 'touch'" to styles of third slide container of demo 9 in documentation.

Probably fix involves ensuring that event.preventDefault() would not be called until native scroll detection is done.

**Comment by oliviertassinari** [comment]
It was fixed with #389.
