### ISSUE TITLE
[browser] Native scroll does not work on last slide unless resistance property is on

### ISSUE THREAD

**Issue by jmheik** [oliviertassinari/react-swipeable-views#258]
Native scroll detection uses `indexCurrent` and `index` to determine scroll direction. Unless resistance property is on, they are equal on the last slide which fails tests in `findNativeHandler` even when last slide would otherwise be scrollable.

Issue can be reproduced by removing `resistance` property from demo 9 of documentation.

On my tests `pageX` and `startX` seemed to be useful replacements for `indexCurrent` and `index` to fix the issue.

**Comment by rehnarama** [comment]
I submitted a pull request for this issue. If anyone need a quick fix for this issue I published this fix at https://www.npmjs.com/package/react-swipeable-views-iss258
