### ISSUE TITLE
Native scroll validation

### ISSUE THREAD

**Issue by TCMiranda** [oliviertassinari/react-swipeable-views#26]
Hello!

Anyone knows if it would be possible to validate if there is any native scroll before starting scrolling the swipeable views?

Ex:
![nscrol](https://cloud.githubusercontent.com/assets/10077439/12313606/30a9ef6c-ba50-11e5-89e7-fbe2d38a09c5.gif)

PS: The example above is using react-swipeable-views without the "event.preventDefault" at handleTouchMove.

Thanks!!

**Comment by oliviertassinari** [comment]
Well, that sounds like a valid use case :+1:.
I will try to have a look.

**Comment by TCMiranda** [comment]
@oliviertassinari thanks!

Did you found anything about it?
Until now my only solution was to use nested native horizontal scroll instead of css transforms, which is a totally different approach :neutral_face:

**Comment by oliviertassinari** [comment]
> Did you find anything about it?

i hadn't time to look at it.

**Comment by oliviertassinari** [comment]
Sorry, I have completely forgotten this issue.

> if it would be possible to validate if there is any native scroll before starting scrolling the swipeable views?

Yes, I think so.

During the `handleTouchStart`, we could traverse up the DOM tree from the event target to the `SwipeableViews` root element. If we find a node containing a scroll bar, we could ignore this event.

**Comment by TCMiranda** [comment]
Hey, thanks for getting back to this.

I am actually using the package even with the issue I mentioned.. 
We didn't had time to focus on it too.

It seems a good plan to ignore the event if a horizontal scrollbar is found.
But it would be better to ignore it only if the element is in the middle of the scrollable area. Handling the touch move would be required though...

So, I feel like I can help you with this in the next week, if that's ok.

Thanks!

**Comment by oliviertassinari** [comment]
> But it would be better to ignore it only if the element is in the middle of the scrollable area.

You are right, I was looking at how Google weather handles this point.
The parent scroll container claims the scroll when the child element scroll is on the edge and the velocity of the movement is high enough.
