### ISSUE TITLE
integrating listview within each tab for react-native

### ISSUE THREAD

**Issue by jasan-s** [oliviertassinari/react-swipeable-views#264]
I want to render data list 500+ with avatars for each tab(4tabs) would I use virtualize HOC or list view within this component for react native? Has anyone used this component for rendering list view with hundreds of entries?

**Comment by oliviertassinari** [comment]
I think that you are on you own here. The react native version is less popular than the web one.
I haven't seen much how people are using it.
Have you tried nesting the SwipeableViews? But it depends on the feature you are looking for.
