### ISSUE TITLE
[android] ScrollView performance

### ISSUE THREAD

**Issue by knapeto** [oliviertassinari/react-swipeable-views#265]
Hi,

I got under the hood optimizations, and I think that is not the best ScrollView selected component, if the user has 5 sheets and more. I suggest instead ScrollView components used ListView. ListView has more performance for such a case plugin.

Thanks, Knapeto

**Comment by oliviertassinari** [comment]
Hi, thanks for digging into the performance of the component. Did you manage to get a working version with the `ListView`?

Notice that we have another implementation using a *animated.js* that could perform better as well as a *virtualize* Higher order Component to handle a large amount of slides.
