### ISSUE TITLE
Swiper not moving to first slide.

### ISSUE THREAD

**Issue by rakesh5987** [oliviertassinari/react-swipeable-views#267]
Please tell me how to move swiper to first slide when a button is tapped. I have a swiper with more than two views and next button also. Initially swiper works good but when i press next button, views are changed but control remains at the same page as previous. I want to start swiper again from the initial slide.

**Comment by oliviertassinari** [comment]
You need to control the component with the `index` and the `onChangeIndex` properties.

**Comment by rakesh5987** [comment]
Hi,
Thanks for Quick reply.
I think you did not get my issue.
My issue is If I am on 5th slide. I have a button that should move me to first slide. But I am unable to find such method to move to first slide using that button.
Please provide me a solution so I can use to move to first slide from any other slide.

**Comment by oliviertassinari** [comment]
Changing the index from `5` to `1` after a click event should do what you are describing.
