### ISSUE TITLE
Bullets

### ISSUE THREAD

**Issue by raphaguasta** [oliviertassinari/react-swipeable-views#268]
Hello guys!

I saw a nice example of Swipeable with dots in here in ['Demo 7](http://oliviertassinari.github.io/react-swipeable-views/)'. I searched in the docs/files and didn't find the implementation of these dots.

Do we have plans to implement it? I think is something default in the web, it's would be very nice!

_I've studied some react swipe libs to implement in my project, and i prefer react-swipeable-views, congratulations! :)_

**Comment by oliviertassinari** [comment]
The source code is right here https://github.com/oliviertassinari/react-swipeable-views/blob/master/docs/src/demo/DemoAutoPlay.js#L59-L63. Feel free to copy the component for your own needs 😄 .
