### ISSUE TITLE
[Question] Why this doesn't use react-virtualized under the hood?

### ISSUE THREAD

**Issue by rafayepes** [oliviertassinari/react-swipeable-views#269]
I'm just curious. react-virtualized seems like a very solid project. Is there any particular reason this project was not implemented as an extension on top of react-virtualized ?

**Comment by oliviertassinari** [comment]
That's a good question. I know that @bvaughn has been looking for a carousel use case of his *react-virtualized* project.

Originally, when I started the project, react-virtualized wasn't a thing.
I believe that using react-virtualized under the hood would mean animating the scroll position over a transformation of an element. Actually, we could implement a scroll control of the component without react-virtualized, then integrating react-virtualized to provide the same feature as the `virtualize()` Higher-order component.
That would mean pretty much doing the same thing as I have done with native, trying out two implementation
- [Animated.js](https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views-native/src/SwipeableViews.animated.js) (Browser implementation is very close)
- [ScrollView](https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views-native/src/SwipeableViews.scroll.js) (Conceptually close to what you are suggesting)

I'm also really curious how well can [react-native-web](https://github.com/necolas/react-native-web) of @necolas brings the native implementation into the web.

**Comment by bvaughn** [comment]
>  Actually, we could implement a scroll control of the component without react-virtualized, then integrating react-virtualized to provide the same feature as the virtualize() Higher-order component.

I made an animator wrapper component that you might be interested in a month or so ago because someone asked how they might do it. It's [here](http://plnkr.co/edit/1S9UT7?p=info) if you'd be interested. Could probably be improved upon. 😄

I would love to see a carousel built on top of react-virtualized. If you're interested in trying it, and I could be of any help, I'd be happy to!

**Comment by oliviertassinari** [comment]
No need to keep the issue open.

**Comment by bvaughn** [comment]
Agreed 😄
