### ISSUE TITLE
Swipe views up and down

### ISSUE THREAD

**Issue by dcworldwide** [oliviertassinari/react-swipeable-views#27]
Is it possible that we could extend the lib to support swiping up and down?

I'm looking into the source now but am not sure where to begin. My use case is to swipe views left to right, then swipe up to show the present slides details, then swipe down to go back to the left to right swipe flow. 

Happy to fork and try it out, but keen to know your thoughts first

**Comment by tconroy** [comment]
👍 to this, looking for a similar feature myself.

**Comment by oliviertassinari** [comment]
I have done a first implementation for the browser platform.

**Comment by oliviertassinari** [comment]
As I believe the feature is requested for this platform, I'm closing the issue.
