### ISSUE TITLE
delayed rendering

### ISSUE THREAD

**Issue by wayofthefuture** [oliviertassinari/react-swipeable-views#270]
We have a considerable size multi-component slide view. The problem is that the render function is called for all components when the swipeable is first rendered. We would like to just render 1 view component at a time. Has anyone thought of adding a "delayRendering" boolean option to postpone rendering until the slide becomes active? Then, for each subsequent slide it would basically slide a blank page, resulting in smoother sliding on older slower phones, then the page renders when it's completed loading. May have a slight delay, but currently our large components make the swipeable unusable.

Thanks.

**Comment by oliviertassinari** [comment]
> The problem is that the render function is called for all components when the swipeable is first rendered.

I have been implementing a logic to only rendering the displayed slide during the initial render then the other.

> Has anyone thought of adding a "delayRendering" boolean option to postpone rendering until the slide becomes active?

That's actually a good idea, some of those optimizations are done inside react-virtualize.
I think that users should be able to handle it on their side. I have been implementing something like that at @doctolib. But sure, we could backed that into the component, for instance, we could expose an Higher-order component with that logic as I think that it can be shared with the native implementation (I'm assuming you are using the browser one).
Have you tried using the `virtualize()` Higher-order component? I have been building it for that use case.

**Comment by wayofthefuture** [comment]
Haven't tried that. I will take a look. Why not just put a component in between the Swipeable component and the View with a prop called "shouldRender" or something, then use componentWillReceiveProps to trigger a render. The component that sits in between can render a blank page (total views - 1, blank pages). On index change can change the prop, then set a timeout equal to the slide time ms in componentWillReceiveProps, triggering a render at the end of the slide, and it should work right?

**Comment by oliviertassinari** [comment]
@wayofthefuture That's an alternative, let me know the solution you end up using. It would be great for other ending up in that thread or even for publish a new module with that responsibility.
