### ISSUE TITLE
Could that be combined with react-router?

### ISSUE THREAD

**Issue by pke** [oliviertassinari/react-swipeable-views#274]
I wonder if that could be combined with any routing component like ie `react-router`?
I'd guess `virtualized` is a good starting point but I can not wrap my head around it just yet.

```jsx
<Route path="/about" component={AboutContainer}>
  <Route path="info" component={AboutInfo}/>
  <Route path="terms" component={AboutTerms}/>
  <Route path="privacy" component={AboutPrivacy}/>
</Route>
```

The `AboutContainer` would render the tab bar and underneath should be the swipeable views. Depending on the route the tabs index should be correctly set (I have figured that out).

I guess in my `VirtualizeSwipeableViews` renderer func I could figure out the current route (if Swipeviews would pass in some more props I set on it and that are not understood and handled by swipeview)

```jsx
<VirtualizeSwipeableViews rendererProps={ location: this.props.location } renderer=pageRenderer/>
``` 

or even better if the renderer itself could be a component

```jsx
<VirtualizeSwipeableViews
  renderer={<PageRenderer location={this.props.location} route={this.prop.route}
/>
```

Then the render component could just use `route.component` to render the component.

Bonus points: Support async component loading inside the render function/component.

Does this make sense?

**Comment by oliviertassinari** [comment]
If you are looking for a react-router@3 integration example, you can have a look at my project.
Here is the [routes](https://github.com/oliviertassinari/SplitMe/blob/master/src/main/router/routes.js#L119) and the [render](https://github.com/oliviertassinari/SplitMe/blob/master/src/main/account/detail/Detail.js#L205).

I'm not sure how that could be elegantly combine with react-router@4, I haven't tried out.
Regarding `virtualized`, I would rather use that component when you need to render a large number if slides, for instance a [gallery](https://www.doctolib.fr/dentiste/boulogne-billancourt/laurence-addi/pictures) on mobile.
I hope that help. Feel free to submit your solution, hopefully that would help others.

**Comment by oliviertassinari** [comment]
I'm closing.

**Comment by sbusch** [comment]
Just found this: https://github.com/sanfilippopablo/react-swipeable-routes (not tested)
