### ISSUE TITLE
Support a transformation function for implementing custom transition

### ISSUE THREAD

**Issue by pke** [oliviertassinari/react-swipeable-views#275]
I'd like to give my Cordova app a native feel with backswipe.

The basic setup would be that the app starts with one view. When the user navigates to another route, the swipe view would then contain 2 views. The old view at index 0 (A) and the new view on index 1 (B).
When the user now swipes to the right on the view B this would basically result in view B being popped from the routing stack (like with browser history back).

While I have not figured out yet, how to remove view B once the user swiped back I wanted to ask how this whole setup could work if view B in itself also supports swiping (using a tabbar/pivot).
The natural behaviour would be that if the user is on the view B's first swipe view and keeps swiping right the View A should come into view.

Is that supported yet? The swipe event of view B should be forwarded to View A if view B cannot act on it.

**Comment by oliviertassinari** [comment]
Sounds like you are looking for a *swipe to go back* implementation, close to what iOS is doing.
That's definitely something not supported. I'm not sure if we want to go into that direction.

However, I guess that it would be good if users could provide a transformation function for each slide (taking an index and a slide number as input and outputting a style). That would have an important implication on the library.

**Comment by oliviertassinari** [comment]
Actually, I think that it's more of a documentation issue. The underlying API is already available: `onSwitching` callback.
