### ISSUE TITLE
add root and container style alterable

### ISSUE THREAD

**Issue by menelike** [oliviertassinari/react-swipeable-views#28]
Thanks for this great library. Currently only styles for slides can be passed trough props. 
In my case I need to change the style from root, which isn't an easy task since those styles are hard coded. I would be great if we could change all styles trough props.

**Comment by oliviertassinari** [comment]
Can't you use the `style` property to apply a style to the container?
What do you think about passing all the property like style to the root component, and rename the curent `style` property to `containerStyle`?

**Comment by oliviertassinari** [comment]
Fix with https://github.com/oliviertassinari/react-swipeable-views/commit/1cfc7685f6e617c6e5a6632e729f74a86554bb53.

**Comment by menelike** [comment]
works like a charm, thanks a lot @oliviertassinari. Great work!
