### ISSUE TITLE
[Question] Demo #2 how to use button to swipe next?

### ISSUE THREAD

**Issue by BennyHoang** [oliviertassinari/react-swipeable-views#281]
Hi,
I am wondering if there are any code examples on demo #2 ?
I am looking for a way to have a button inside the swipable view to swipe to next view.

The demonstration is from this page: https://oliviertassinari.github.io/react-swipeable-views/

Many thanks

**Comment by oliviertassinari** [comment]
You can find all the demos in that [folder](https://github.com/oliviertassinari/react-swipeable-views/tree/master/docs/src/demo).

**Comment by BennyHoang** [comment]
Thank you @oliviertassinari
