### ISSUE TITLE
Get swipedirection

### ISSUE THREAD

**Issue by christianeide** [oliviertassinari/react-swipeable-views#288]
Is it possible to get the direction of the swipe? Without calculating from index and indexLatest.

I just need to know if the user is swiping/swiped right or left, and I need to know this before onChangeIndex is called.

**Comment by oliviertassinari** [comment]
> Without calculating from index and indexLatest.

That's a one line logic. That sounds really simple. What do you have in mind?

**Comment by oliviertassinari** [comment]
Have you tried `onSwitching`?

**Comment by christianeide** [comment]
What I want to do is to be able to swipe on a parent container, and then reveal/swipe inn a child container over the parentcontainer.

![reactswipe](https://cloud.githubusercontent.com/assets/15894115/25917029/0fd15b38-35c7-11e7-95f4-e4d8fdfced8c.png)

I can think of two ways to do this: 
1. Let the parent be child nr 1 and then be able to not swipe away the parentcontainer, only swipe the child over the top of the already existing parent. I couldnt find a way to do this?

2. Place the parent in its own < SwipeableViews> and use the swipe event to toggle the index state of the child between 0 and 1. Im currently doing the switch on the onTransitionEnd. This works, but it will toggle between 0 and 1 on all swipeevents in all directions, not just the way you . So it doesnt feel like a native swipe. Any better ideas?


```
handleShowEkstraData() {
    this.setState({swipeIndex: 1 - this.state.swipeIndex}); //Toggles between the states
  }


  render() {
    return (
      <div>
              <SwipeableViews 
              animateTransitions={false} 
              onTransitionEnd={this.handleShowEkstraData} >
                 <MyComponent  />
              </SwipeableViews>

              <SwipeableViews 
              index={this.state.swipeIndex} 
              onChangeIndex={this.handleShowEkstraData} >
                    <div></div>
                    <div className="fane" onClick={this.handleShowEkstraData}>Sidetest</div>
              </SwipeableViews> 
      </div>
      )
}


```

Any suggestions is appreciated!

**Comment by oliviertassinari** [comment]
Did you try nesting two `SwipeableViews`? I'm not sure to understand the result you are looking for. My be you have a video?

**Comment by christianeide** [comment]
Take a look at this quick video i made: https://youtu.be/G_GL9h-Uzqo

Im swiping the grey div (className="fane") over MyComponent. So MyComponent triggers the swipe in of the grey div, but doesent move it self. This works, but as you can see from the video, I can swipe in all directions to trigger change. Now I just toggle the animation in and out regardless of the direction you are swiping.

**Comment by oliviertassinari** [comment]
That's a complex use case, that I haven't anticipated when designing the component. Have you considered nesting two `<SwipeableViews />`?

**Comment by christianeide** [comment]
Hi again. Tried to nest two `<SwipeableViews />` without any luck. In my test that would mean that the parent also would swipe, which I dont want. Do you have any other suggestions?

**Comment by oliviertassinari** [comment]
@christianeide I have never pushed the component that far. Honestly, I don't have time to look at it in detail. Still, I would love to get the answer, that could help other!
