### ISSUE TITLE
React Native: Virtualized SwipeableView not reloading slides when an index is given

### ISSUE THREAD

**Issue by MonsieurBlutbad** [oliviertassinari/react-swipeable-views#289]
Hi,

When I set any value but undefined for index on VirtualizeSwipeableViews the slideRenderer function is not getting called and no slides beyond the initial ones (based on the overscanSlideBefore and overscanSlideAfter settings) are getting rendered. So when I set an index of i.e. 4 I can swipe from Slide 2 to Slide 7. When I do not set the index or set it to undefined everything is working as it should.  

The following code replicates the issue:

```jsx
import React, { Component } from 'react';
import { AppRegistry, View, Text } from 'react-native';
import SwipeableViews from 'react-swipeable-views-native';
import { virtualize } from 'react-swipeable-views-utils';

const VirtualizeSwipeableViews = virtualize(SwipeableViews);

export default class MyApp extends Component {
    getSlideRenderer(slide) {
        return (
            <View key={slide.key}>
                <Text>Slide #{slide.index}</Text>
            </View>
        )
    }

    render() {
        return (
            <VirtualizeSwipeableViews
                index={0}
                slideRenderer={this.getSlideRenderer.bind(this)}
                slideCount={10}
            />
        )
    }
}

AppRegistry.registerComponent('MyApp', () => MyApp);

**Comment by oliviertassinari** [comment]
Hey, setting the `index` property is making the component *controlled*, you need to handle the change event. Here is [an example](https://github.com/oliviertassinari/react-swipeable-views/blob/3cda85bca6adea08525e3e222596cbc3b7f4a7c6/docs/src/demo/DemoVirtualize.native.js#L82-L86). That should fix your issue. Let me know if you find others.

**Comment by MonsieurBlutbad** [comment]
That did it, thank you very much!
