### ISSUE TITLE
Is there any way to prevent lazy loading?

### ISSUE THREAD

**Issue by nirlendu** [oliviertassinari/react-swipeable-views#296]
Hi! I was wondering if it's possible to disable lazy loading for all slides?

**Comment by oliviertassinari** [comment]
We could add a property for that.

**Comment by torte** [comment]
:+1: 

Assuming that this is related to `isFirstRender` state in the `SwipeableView` component and how it is used. The problem we are facing is that this will not render all views when doing server-side rendering. We should be able to overwrite that behavior somehow.

**Comment by zhantx** [comment]
Hi there, I created a PR to fix this issue #306

**Comment by oliviertassinari** [comment]
Regarding the feature. I'm curious. What's the use case? Why would someone want to render all the slides on the server. Is it SEO related?

**Comment by nirlendu** [comment]
I can just say for my use case. I'm looking for SSR for a page, and it looks ugly if one slide appears first and the rest loads once the js files are compiled by the browser.

**Comment by torte** [comment]
Our primary reason is SEO as you already guessed. We could work around this not using `SwipeableViews` when on server-side, but then we need add custom code just for this.
