### ISSUE TITLE
Rendering child through props in SwipeableViews ?

### ISSUE THREAD

**Issue by piyushchauhan2011** [oliviertassinari/react-swipeable-views#297]
Hi @oliviertassinari , I was wondering if it's possible to render `{child}` elements using a props which contains array of `DOM` elements. The use-case would be ability to do `CRUD` using a button which will make `SwipeableViews` to dynamically increase-decrease the length of the number of child elements.

Not sure how to make that work, any hints ? I tried to use `redux` to integrate a workflow for doing `CRUD`, don't know how to render the children properly as the dragging just stick to initial view for some reason after updating the `count` and `map` in render.

**Comment by oliviertassinari** [comment]
Yes, you can do such thing. `<SwipeableViews />` should behave like a regular `<div />`. Same problem, same solution, just use an array of child as children.
