### ISSUE TITLE
[Native] ScrollView not working in with react-swipeable-views-native 0.12.2

### ISSUE THREAD

**Issue by AlanFoster** [oliviertassinari/react-swipeable-views#299]
With version 0.12.2 of react-swipeable-views-native it is not possible to scroll vertically within a scroll view element, however it works with 0.12.1 and below

# Before

> yarn add react-swipeable-views-native@0.12.1

ScrollView works as expected:

![app](https://cloud.githubusercontent.com/assets/1271782/26755193/4477a876-4880-11e7-9b16-ad69b7275bca.gif)

# After

> yarn add react-swipeable-views-native@0.12.2

ScrollView does not work, but it's possible to accidentally move horizontally:

![app](https://cloud.githubusercontent.com/assets/1271782/26755235/3cb3ad64-4881-11e7-8921-68f03c4c6200.gif)

---

The code demonstrating this issue can be found:

https://github.com/AlanFoster/react-native-swiping-performance/commit/5d62e373e6d90c5c045d64ca8523e79f622e1c4e

**Comment by oliviertassinari** [comment]
That sounds like a regression introduced by #293 in order to support the Modal mode.

**Comment by jkallunki** [comment]
I had the same issue but got it fixed in my project for now by using this:
`import SwipeableViews from 'react-swipeable-views-native/lib/SwipeableViews.scroll';`
