### ISSUE TITLE
We should support every main browser

### ISSUE THREAD

**Issue by oliviertassinari** [oliviertassinari/react-swipeable-views#3]
I have to check this.

**Comment by twidi** [comment]
Also on desktop with the mouse?

**Comment by oliviertassinari** [comment]
> Also on desktop with the mouse?

We could have this feature but I dont' think that it sounld be the default behavior.

**Comment by twidi** [comment]
Yes I understand but now this is unusable on desktop browsers if there is no tabs attached, so it cannot be used for apps that should work on mobile and desktop :(

FYI here on Firefox desktop I have the message "You need a touch device to swipe between the 3 slides.", but in chrome I don't.

By the way it was just a suggestion, I love what you did!

PS: last year I made a draft of something like that with hammerjs so it worked with mouse and touch, but I don't know if it is possible for you with the libs you use

**Comment by oliviertassinari** [comment]
> but in chrome I don't.

Do you have a touch screen? My guess is that Chrome handles it better than Firefox.

> By the way it was just a suggestion, I love what you did!

Thank! Feel free to submit a PR if you need this feature. It should be straitghtforward. However, as said, I think that there is an UX issue with this behavior. I don't want it enabled by default.

**Comment by twidi** [comment]
Ahah you know what? I totally forgot one of my screen had touch features!

So when moving the chrome window on the touch-enabled screen, it works like a charm with a finger but not the mouse.
And for firefox, yes, it doesn't work, even on the touch screen :( BUT of course in "responsive design mode" and when "simulate touch events" is activated, it works, with fingers or mouse.

About the PR, yes I'll see, when I'll integrate your lib, if I can do something ;)

**Comment by giladbr** [comment]
Following this discussion, is there any chance this component would be adjusted to support "swiping" with the mouse on desktop? Maybe utilizing hammer.js/react-hammer?
 This would be of great use and I found no other react component that supports that.

**Comment by oliviertassinari** [comment]
@giladbr That's another topic. Could you open an issue for this? That sounds fair, we could add it under a specific enable property.

**Comment by oliviertassinari** [comment]
A support section was added in the docs https://github.com/oliviertassinari/react-swipeable-views#browser-2. I think that we can close that issue now.
