### ISSUE TITLE
[0.12.3] onChangeIndex gives the previous index instead of the current

### ISSUE THREAD

**Issue by MaxInMoon** [oliviertassinari/react-swipeable-views#302]
Controlled with `index` or not,  `onChangeIndex` of `<SwipeableViews />` always gives me the previous slide index instead of the current.

**Comment by oliviertassinari** [comment]
Do you have a reproduction example?

**Comment by MaxInMoon** [comment]
#### How to reproduce

1 - Create a app with [create-react-app]()
2 - Add folowing code in App.js:
```jsx
import React, { Component } from 'react';
import SwipeableViews from 'react-swipeable-views';
import './App.css';

class App extends Component {

  onSwipeableViewChanged = (e, value) => {
    console.log(value);
  }

  render() {
    return (
      <div className="App">
        <div className="App-header">
          <h2>Welcome to React</h2>
        </div>
        <div className="App-intro">
          <SwipeableViews onChangeIndex={this.onSwipeableViewChanged}>
            <div className="swipeableView">
              View 1
            </div>
            <div className="swipeableView">
              View 2
            </div>
            <div className="swipeableView">
              View 3
            </div>
          </SwipeableViews>
        </div>
      </div>
    );
  }
}

export default App;
```
3 - And padding to test easily:
```jsx
.swipeableView {
  padding: 6em 4em;
}
```

**Comment by oliviertassinari** [comment]
We don't give access to the `event`

| Name | Type | Default | Platform | Description |
|:-----|:-----|:--------|:---------|:------------|
| onChangeIndex | function(index, indexLatest) | | all | This is callback prop. It's call by the component when the shown slide change after a swipe made by the user. This is useful when you have tabs linked to each slide. |

**Comment by MaxInMoon** [comment]
@oliviertassinari seems obvious now, sorry for my low discerning, thanks
