### ISSUE TITLE
Is it possible to add loading bar on bottom of Swipe for autoplay?

### ISSUE THREAD

**Issue by Shadowman4205** [oliviertassinari/react-swipeable-views#305]
Any suggestion how i can implement this fuctionality?

**Comment by oliviertassinari** [comment]
You could do something close to the [Demo 7](https://github.com/oliviertassinari/react-swipeable-views/blob/9e29d8a2d10e6363ac6b60ce8e21b3b8c6669a78/docs/src/demo/DemoAutoPlay.js) of the documentation:
<img width="335" alt="capture d ecran 2017-07-05 a 13 44 29" src="https://user-images.githubusercontent.com/3165635/27862947-23bcb68c-6188-11e7-8a9c-ce682f5eea0f.png">
