### ISSUE TITLE
first view scrolling when the second view scrolling

### ISSUE THREAD

**Issue by Liqiankun** [oliviertassinari/react-swipeable-views#307]
![bug](https://user-images.githubusercontent.com/11532418/28149637-bfc459b0-67c1-11e7-8101-364f95203c37.gif)

**Comment by Liqiankun** [comment]
@oliviertassinari Need your help! 😄

**Comment by oliviertassinari** [comment]
Fix the height of the parent of the slides. I have this [example](https://github.com/oliviertassinari/SplitMe/blob/20da586c4b1450d8450fbc9c5b07eed0455aced9/src/main/account/detail/Detail.js#L206). Also, the demos of the documentation illustrate how to do it. It's Demo n°3.

**Comment by Liqiankun** [comment]
Thank you man! @oliviertassinari  I got it done!

**Comment by Liqiankun** [comment]
@oliviertassinari Height is find now. When I scroll second view the first view's contentOffSize still change!

**Comment by Liqiankun** [comment]
@oliviertassinari  Finally I fixed it! Thanks man!

**Comment by oliviertassinari** [comment]
That looks great :)

**Comment by Liqiankun** [comment]
I got another issue! 
this is my code
```
          <SwipeableViews
            animateHeight
            index={index}
            onChangeIndex={index => this.setState({ index })}
          >
            {categories.map((category, index) => {
              return (
                <ProductTab banners={category.banners} products={category.products} loadMore={() => this.props.loadMoreProducts('0')} showActionBar={index === 0} />
              )
            })}
          </SwipeableViews>

//here is ProductTab
        <div style={{display: 'flex', height: containerHeight}}>
          {views}
        </div>
```
When I click first cell to the detail, then back. It shows well. 
![wechatimg7](https://user-images.githubusercontent.com/11532418/28197190-d252e350-6887-11e7-9aea-62f110a41e94.jpeg)
After the the fifth It shows this way. the Banner is hidden(banner is also using react-swipeable-views )
![wechatimg6 1](https://user-images.githubusercontent.com/11532418/28197296-778d5f76-6888-11e7-9e6c-77376cf554bf.jpeg)

**Comment by oliviertassinari** [comment]
Sorry, I'm not sure I can help.

**Comment by Liqiankun** [comment]
@oliviertassinari Thank you all the same!
