### ISSUE TITLE
contentOffset is not available on Android

### ISSUE THREAD

**Issue by eugenehp** [oliviertassinari/react-swipeable-views#308]
https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views-native/src/SwipeableViews.scroll.js#L278 

So when you set index using
```
<SwipeableView index={index}/>
```
it won't set it to defined index.

**Comment by eugenehp** [comment]
@oliviertassinari I pushed something that worked for me in emulator. Let me know if you need further explanation on what I'm trying to do here.

**Comment by oliviertassinari** [comment]
Thanks for looking into it!
