### ISSUE TITLE
Mutating styles

### ISSUE THREAD

**Issue by yepnamesjames** [oliviertassinari/react-swipeable-views#31]
Looks like the same error as [here](https://github.com/facebook/react/issues/4877) is coming from React-Swipeable-Views. I believe it stems from this code producing NaN sometimes:
```
const translate = -interpolatedStyle.translate;

return (
  <div
    style={Object.assign({
      WebkitTransform: `translate3d(${translate}%, 0, 0)`,
      transform: `translate3d(${translate}%, 0, 0)`,
      height: interpolatedStyle.height,
    }, styles.container, containerStyle)}
  >
    {childrenToRender}
  </div>
);
```

Here is the exact error:
```
Warning: `div` was passed a style object that has previously been mutated. Mutating `style` is deprecated. Consider cloning it beforehand. Check the `render` of `Motion`. Previous style: {WebkitTransform: "translate3d(NaN%, 0, 0)", transform: "translate3d(NaN%, 0, 0)", height: NaN, display: "-webkit-box; display: flex"}. Mutated style: {WebkitTransform: "translate3d(NaN%, 0, 0)", transform: "translate3d(NaN%, 0, 0)", height: NaN, display: "-webkit-box; display: flex"}.
```

**Comment by oliviertassinari** [comment]
Could this be an issue react motion?

**Comment by yepnamesjames** [comment]
I'm not sure about React-Motion, but the warning can be avoided as long as we insure that none of those values in the object equal NaN. If I have time, I will console log to see what kind of values are reaching it.

The odd thing to me is that it is a warning, but it stopped the component from rendering. I was able to downgrade this component temporarily to get it to work.

**Comment by oliviertassinari** [comment]
> I was able to downgrade this component temporarily

What version of `react-motion` and `react-swipeable-views` is affected? And what version is fixing it?

**Comment by yepnamesjames** [comment]
react-motion@0.3.1 and react-swipeable-views@0.3.6 are good.
react-motion@0.4.0 and react-swipeable-views@0.4.0 are bad.

**Comment by oliviertassinari** [comment]
I wasn't able to reproduce this issue :/.

**Comment by yepnamesjames** [comment]
Me either!
