### ISSUE TITLE
Unknown prop `disableLazyLoading` on <div> tag. Remove this prop from the element

### ISSUE THREAD

**Issue by rizkiandrianto** [oliviertassinari/react-swipeable-views#310]
I try to update, but why I got this?

**Comment by oliviertassinari** [comment]
No clue :/

**Comment by rizkiandrianto** [comment]
well, trying to reproduce your sample code will cause this too in my case.
is the react version (or other depedencies) will affect this?

**Comment by oliviertassinari** [comment]
I'm closing as I'm not able to reproduce on the demo/documentation.
