### ISSUE TITLE
bindKeyboard fails when index is specified

### ISSUE THREAD

**Issue by MattKetmo** [oliviertassinari/react-swipeable-views#316]
Hello,

I noticed when you use the `index` prop on a `BindKeyboardSwipeableViews` component, this disable the `bindKeyboard` effect. 
For instance on the demo 10 if you add a `index={1}` on https://github.com/oliviertassinari/react-swipeable-views/blob/master/docs/src/demo/DemoKeyboard.js#L27 then you can't use your keyboard to navigate between slides.

**Comment by oliviertassinari** [comment]
That's expected, you are making the component controlled. You need to listen for the change event to update the index value.
