### ISSUE TITLE
Keyboard focus still switches to other views when disabled

### ISSUE THREAD

**Issue by ernani** [oliviertassinari/react-swipeable-views#317]
I have 3 tabs and 3 of them has focusable elements.
When using TAB to alternate, they behave the same as being swiped.
Can this be disabled? I am not sure if that could be possible. Thanks anyhow!

**Comment by oliviertassinari** [comment]
We could add third argument to the `onChangeIndex` with some meta data, for instance, the reason behind the event. With that feature, you can filtre out TAB based events.
