### ISSUE TITLE
React@16

### ISSUE THREAD

**Issue by BonnieWeb** [oliviertassinari/react-swipeable-views#318]
project dependencies {"react": "16.0.0-alpha.12","react-native": "0.47.1","react-swipeable-views": "^0.12.5"}
import SwipeableViews from 'react-swipeable-views';
import AutoPlay from 'react-swipeable-views-utils/lib/autoPlay';
const AutoPlaySwipeableViews = AutoPlay(SwipeableViews);
render: <View>
            <AutoPlaySwipeableViews>
                  <Image style={styles.slide}
                          source={require("./img/img1.jpg")}>
                  </Image>
                   <Image style={styles.slide}
                          source={require("./img/img2.jpg")}>
                  </Image>
              </AutoPlaySwipeableViews>
</View>
 Error:Expected a component class,got[object Object];
please help me,thanks!

**Comment by oliviertassinari** [comment]
We don't support react@16 yet. We need to upgrade the peer dependencies.
