### ISSUE TITLE
Issue with slideIndex and removal of items

### ISSUE THREAD

**Issue by andrzey** [oliviertassinari/react-swipeable-views#32]
Imagine I have three items in a list and two slides in each item. I then select my item2 and slide it to the left to show more controls like a delete button. If I then delete item2, I am left with two items in my list which is fine. The problem is that item3 that now is item2 after I deleted one item have its slideIndex set to the same as the item that was deleted from the list. How can I refresh the list of items so that every item have its slideindex set to 0?

**Comment by oliviertassinari** [comment]
Would using the `index` property work?

**Comment by andrzey** [comment]
Unfortunately that doesnt solve the issue.

**Comment by funkyeah** [comment]
Is this really a bug? Seems like this is a state management issue. Each item in the list needs to be given a unique identifier and the state/index of each swipeable should be associated with that identifier. Then when an item is deleted from the list the state is not tied to its position in the list. If you want to reset the index of all slides after an event like pressing of a delete button then that should be done from the list controller.

**Comment by oliviertassinari** [comment]
> The problem is that item3 that now is item2 after I deleted one item have its slideIndex set to the same as the item that was deleted from the list.

@funkyeah Oh, you are right, I have overlooked this sentence. That's proving that it's working fine.
Thanks 👍 .
