### ISSUE TITLE
How to use this with a Grid?

### ISSUE THREAD

**Issue by storrisi** [oliviertassinari/react-swipeable-views#321]
Don't know if it possible, i would like to use this to swipe the columns of a MultiGrid component of react-virtualized

**Comment by oliviertassinari** [comment]
I have no clue, let us know if it's possible :).

**Comment by storrisi** [comment]
Done! I'll post here the solution if you want

**Comment by oliviertassinari** [comment]
Yeah, I'm always happy to hear more about how people use this lib! We could even use it to add a demo in the docs.
