### ISSUE TITLE
is it possible? let swipe view  adjust to it‘s own height

### ISSUE THREAD

**Issue by keith890303** [oliviertassinari/react-swipeable-views#322]
Suppose my screen height 100px,I have two views left's height 500px and right's 100px.
then first load page show the left view  everything is ok
then  swipe first view up maybe scroll top 200px ,  
1、 swipe to left 50% do not relax you finger, you can see left view 50% right view 50% ,but right view's 50% was blank (that not my want )
#  (I hope right view will scroll top 0)
2、change to right view ,now it's has a scroll bar because it's height was 500px (left view's height)
# (I hope right view's height was 100px without scroll bar )

how can I resolve this two problems,thanks in advance !!!

**Comment by oliviertassinari** [comment]
We have a demo with the expected result. Have a look at them.

**Comment by PardeepWildnet** [comment]
@oliviertassinari  can you please provide the link for example where i can see expected result.
Thanks

**Comment by oliviertassinari** [comment]
@PardeepWildnet It's the demo n°3 in the docs and this one in the source https://github.com/oliviertassinari/react-swipeable-views/blob/5835f94383ddbc7d16baea4df8404d3f70262830/docs/src/demo/DemoScroll.js

**Comment by PardeepWildnet** [comment]
As per this demo, I am able to set static height of content let's say its 100 in this case, but i want to set height as per content size not static. 

For example content for tab1 is of 400px height and for tab2 its 50px
so height should be 400px and 50px respectively not 400px for both.

I hope you get my point.
