### ISSUE TITLE
Unit testing for touch events

### ISSUE THREAD

**Issue by Schlesiger** [oliviertassinari/react-swipeable-views#326]
I am trying to add unit testing for touch events in my project. I am using Jest and Enzyme. I'd like to simulate a "swipe" on the `react-swipeable-views` component and test that the `onSwipe` function is called appropriately.

I've found a similar example in this blog post and PR for `react-swipeable`:
http://www.hartzis.me/test-touch-events-react/
https://github.com/dogfessional/react-swipeable/pull/59

I included [events.js](https://github.com/dogfessional/react-swipeable/blob/master/src/__tests__/helpers/events.js) in my project and tried using it with `react-swipeable-views` but the simulated actions didn't seem to trigger the `onSwipe` function.

Is there already an established method for unit testing swipe actions with `react-swipeable-views`?

**Comment by oliviertassinari** [comment]
@Schlesiger We have many [unit tests](https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views/src/SwipeableViews.spec.js) in the repository that are testing different swipe feature. I'm not sure they are high level enough for you, but alternatively, you can always simulate a `onChangeIndex` event.

**Comment by Schlesiger** [comment]
Thanks! The test I am attempting is more "blackbox" than the examples; I am avoiding `.instance()`.

Here's a rough example of what I am trying:

```js
const DrawerContent = ({
  currentDrawer,
  drawers,
  onSwipe,
}) => {
  return (
    <SwipeableViews
      index={drawers[currentDrawer] ? currentDrawer : 0}
      onChangeIndex={(index) => {
        onSwipe(index);
      }}
    >
      {
        drawers.map((drawer) => {
          return (
            <div key={drawer.name}>
              {drawer.name}
            </div>
          );
        })
      }
    </SwipeableViews>
  );
};
```

```js
test('Select 2nd tab', () => {
  const whenDrawerSelect = jest.fn();

  const content = shallow(
    <DrawerContent
      currentDrawer={0}
      drawers={[{name: 'drawer1'}, {name: 'drawer2'}]}
      onSwipe={whenDrawerSelect}
    />
  );

  content.simulate(
    'touchStart',
    {touches: [{
      pageX: 50,
      pageY: 0,
    }]}
  );
  content.simulate(
    'touchEnd',
    {touches: [{
      pageX: 100,
      pageY: 0,
    }]}
  );

  expect(whenDrawerSelect).toBeCalledWith(1);
});
```

However, the function `whenDrawerSelect` is never called. I have also tried `content.child().simulate` without effect.

**Comment by oliviertassinari** [comment]
That's close to an e2e tests. You can't use `shallow` for that. You need to mount the component. Honestly, I have never been writing such test while using the component multiple times. I can't see what value this test can potentially bring.

**Comment by oliviertassinari** [comment]
On the other hand, I still have an opened issue to run such test on the browser. Butt I have never found the time to work on it. Unit tests and manualy testing the demo website have been enough soo far.

**Comment by oliviertassinari** [comment]
https://github.com/oliviertassinari/react-swipeable-views/issues/136

**Comment by Schlesiger** [comment]
Rats. I didn't know `shallow` would prevent this. I can't use `mount` in my case because I have nested components relying on HOC context. If start initializing HOC's, the test complexity goes way up and I may as well just run a full e2e test - exactly what I wanted to avoid. I was trying to improve coverage but perhaps this case isn't worth the effort.

As far as the `react-swipeable-views` project is concerned, I can't say whether broader e2e is required. My project has several "touch" libraries involved and I do think additional testing is valuable to ensure interoperability. I will be trying Nightwatch for "full" e2e testing. I can comment back here with working examples if you like.

**Comment by oliviertassinari** [comment]
Always happy to see an example. That something we could take advantage of later.
