### ISSUE TITLE
use it as nested swipe 

### ISSUE THREAD

**Issue by saurabhsinha** [oliviertassinari/react-swipeable-views#33]
hi,
I tried using this component as nested swipe. But while swiping the child it was triggering the parent swipe too.. Any idea how to fix this issue. 
It would be great if you post a fix or doc how to do this .. 
something like this

```jsx
<div parent swipe>
    <div child swipe>
    </div>
</div>
```

**Comment by oliviertassinari** [comment]
Interesting issue. I think that we can fix it by calling `preventDefault` and by checking that the event wasn't prevented before handling it.

**Comment by saurabhsinha** [comment]
hi can you be more specific, I mean where to check that the even prevented before or not..

**Comment by oliviertassinari** [comment]
Fix with https://github.com/oliviertassinari/react-swipeable-views/commit/335c5dce319afbb779435eb736d485c5b91be637. Have a look at the demo n°6.
