### ISSUE TITLE
scrollable(swipeable)-tabs

### ISSUE THREAD

**Issue by tOke3i** [oliviertassinari/react-swipeable-views#332]
Hi! Is it possible to use  your plugin with such functionality ? If yes. How? 
![swipeable](https://user-images.githubusercontent.com/16651056/29774977-29ff3282-8c0c-11e7-9b10-bd4e9bf43250.gif)

**Comment by oliviertassinari** [comment]
No, it wasn't designed for this use case.

**Comment by tOke3i** [comment]
it would be cool if  you add it because sometimes the amount of tabs can be more than 10 for example it looks not so good. Are you going to add functionality? Thank you for your answer! @oliviertassinari

**Comment by oliviertassinari** [comment]
@tOke3i There is no plan to add this feature. I don't think that it fits into the vision of the project. Let us know if you find a solution, that could potentially help others.
