### ISSUE TITLE
Jest show me: TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by skumblue** [oliviertassinari/react-swipeable-views#336]
Hi, 

When I run Jest in some file with **react-swipeable-views**, the console show me:
`TypeError: Cannot read property 'addEventListener' of null`

How can I solve this?

Thanks!

**Comment by oliviertassinari** [comment]
What version of flow are you using? What's the complete error message? What version of the lib are you using?

**Comment by skumblue** [comment]
@oliviertassinari I use **^0.12.8** version, and this is the complete message error:

<img width="883" alt="screen shot 2017-09-03 at 10 47 55 am" src="https://user-images.githubusercontent.com/3875593/30003548-49504f6c-9095-11e7-8c86-ed46008d1e6b.png">

**Comment by oliviertassinari** [comment]
@skumblue Oops, for one moment, I have mixed jest and flow in my mind.
Sounds like you are mounting a component without having the browser environment variables. Add them and you should be good. For instance, here is our setup.
https://github.com/oliviertassinari/react-swipeable-views/blob/3c03bd4f19f9a525f71de732309bbdfd96e2c4c1/test/dom.js#L8-L26

**Comment by skumblue** [comment]
I solve this mount whit enzyme:

`import { mount } from 'enzyme';`
`const wrapper = mount(<MyComponent />);`

Thanks!

**Comment by ManuSevenval** [comment]
I got the exact same error message with the current version of react-swipeable-views.
the snippet by @oliviertassinari did not solve the issue for me.
Are there any other hints I could try besides using enzyme's mount ?

**Comment by gratiaa** [comment]
I also had a similar problem.
I was testing using storyshot from storybook.
In my case, `shallow` rendering from Enzyme also works well.

**Comment by oliviertassinari** [comment]
@gratiaa I believe the issue comes from the `shallow` API of enzyme that run the `componentDidMount()` hook. This hooks try to access an undefined reference:
https://github.com/oliviertassinari/react-swipeable-views/blob/5047f04011d4fd6818823789e96ca12c29ced596/packages/react-swipeable-views/src/SwipeableViews.js#L260-L263
You can disable this behavior with the [`disableLifecycleMethods`](https://github.com/airbnb/enzyme/blob/7a97af4c02961c0a0d055149970db3e07af733b7/docs/api/shallow.md) flag:
https://github.com/oliviertassinari/react-swipeable-views/blob/4c887c9bd0694ca85a239413d5e6eae5935a84b8/packages/react-swipeable-views/src/SwipeableViews.spec.js#L589

**Comment by gratiaa** [comment]
@oliviertassinari 
Thank you for your reply 😸 didn't know the flag exists...
But in my storyshot testing code, i just use `shallow` rendering from enzyme
and it worked well, no need to add `disableLifecycleMethods` flag.
My testing code is like this:

```js
initStoryshots({
  test: ({ story, context }) => {
    const storyElement = story.render(context)
    const shallowTree = shallow(storyElement)
    expect(toJson(shallowTree)).toMatchSnapshot()
  },
})
```

**Comment by rohithZE** [comment]
> @gratiaa I believe the issue comes from the `shallow` API of enzyme that run the `componentDidMount()` hook. This hooks try to access an undefined reference:
> https://github.com/oliviertassinari/react-swipeable-views/blob/5047f04011d4fd6818823789e96ca12c29ced596/packages/react-swipeable-views/src/SwipeableViews.js#L260-L263
> 
> 
> You can disable this behavior with the [`disableLifecycleMethods`](https://github.com/airbnb/enzyme/blob/7a97af4c02961c0a0d055149970db3e07af733b7/docs/api/shallow.md) flag:
> https://github.com/oliviertassinari/react-swipeable-views/blob/4c887c9bd0694ca85a239413d5e6eae5935a84b8/packages/react-swipeable-views/src/SwipeableViews.spec.js#L589

I get this problem when i'm using react-test-renderer. When react-swipeable-views is called **function addEventListenerEnhanced(node, event, handler, options) {** is being called as part of component life cycle methods with node being null initially. As a result node.addEventListener fails.
Is there any work around for this?

**Comment by oliviertassinari** [comment]
We have the same problem with Material-UI, check how it's handled there. It's about telling react test render how to handle the DOM nodes.

**Comment by MilePaor** [comment]
@rohithZE  have you found solution for this problem?

**Comment by MilePaor** [comment]
> > @gratiaa I believe the issue comes from the `shallow` API of enzyme that run the `componentDidMount()` hook. This hooks try to access an undefined reference:
> > https://github.com/oliviertassinari/react-swipeable-views/blob/5047f04011d4fd6818823789e96ca12c29ced596/packages/react-swipeable-views/src/SwipeableViews.js#L260-L263
> > 
> > You can disable this behavior with the [`disableLifecycleMethods`](https://github.com/airbnb/enzyme/blob/7a97af4c02961c0a0d055149970db3e07af733b7/docs/api/shallow.md) flag:
> > https://github.com/oliviertassinari/react-swipeable-views/blob/4c887c9bd0694ca85a239413d5e6eae5935a84b8/packages/react-swipeable-views/src/SwipeableViews.spec.js#L589
> 
> I get this problem when i'm using react-test-renderer. When react-swipeable-views is called **function addEventListenerEnhanced(node, event, handler, options) {** is being called as part of component life cycle methods with node being null initially. As a result node.addEventListener fails.
> Is there any work around for this? @oliviertassinari

@rohithZE Have you found solution for this problem?

**Comment by MilePaor** [comment]
Yes, shallow rendering fix issue with jest testing.

**Comment by madhusmitapalai** [comment]
I am using an NX monorepo, and now I am trying to run unit testing, but I am getting the following error.
And also I have used the Antd components .
How could I resolve this issue ....;
Any suggestions.....;


**_TypeError: Cannot read properties of undefined (reading 'addListener')_**
