### ISSUE TITLE
How can config the count of image to show?

### ISSUE THREAD

**Issue by skumblue** [oliviertassinari/react-swipeable-views#337]
Hi, I use react-swipeable-views 0.12.8 in my webapp.

This is my case, I have 3 images.

In the mobile version is ok:
<img width="224" alt="screen shot 2017-09-04 at 1 27 27 pm" src="https://user-images.githubusercontent.com/3875593/30033985-f8e9da6c-9174-11e7-80df-15034994ba7c.png">

But I want that in my desktop version show me the 3 images at same time:
<img width="627" alt="screen shot 2017-09-04 at 1 25 34 pm" src="https://user-images.githubusercontent.com/3875593/30034119-a63965f2-9175-11e7-9542-80be2549c66d.png">

Here an example with *react-slick*. In this library, the **responsive** config works:
https://jsfiddle.net/2w7jr06z/

I hope you can help me, thanks!

**Comment by oliviertassinari** [comment]
You could be using something like a [`withWidth()`](https://github.com/callemall/material-ui/blob/6262a4eaad2eccfd02049e17ed15bdd976c1276b/src/utils/withWidth.js) Higher order Component to change the shape of the children based on the current width of the screen.
