### ISSUE TITLE
Prevent Infinite Scroll 

### ISSUE THREAD

**Issue by Olivr3** [oliviertassinari/react-swipeable-views#338]
The following code is not setting the height for the views. 
```
const WINDOW_HEIGHT = { maxHeight: '90vh' }
<SwipeableViews
            style={WINDOW_HEIGHT}
            index={this.state.slideIndex}
            onChangeIndex={value => this.handleChange(value)}
          >
            {this.props.children}
          </SwipeableViews>
```
How can I access `react-swipeable-view-container` class so that I can add the max-height property?

![screenshot from 2017-09-05 09-45-11](https://user-images.githubusercontent.com/20702895/30052999-3c01bd2e-921f-11e7-85b9-d8b5dadb8fa8.png)

Thx in advance.

**Comment by oliviertassinari** [comment]
You can use the `containerStyle` property.

**Comment by Olivr3** [comment]
Thx! I completed missed this property.
