### ISSUE TITLE
How to change the index smooth?

### ISSUE THREAD

**Issue by studentIvan** [oliviertassinari/react-swipeable-views#340]
In the Demo on the site http://oliviertassinari.github.io/react-swipeable-views/ there is tab navigation. It using simple state index. But on my local project changing of index throws the next slide immediately. E.g. if I will use the <SwipeableViews index={ this.state.myIndex }...  and then I will use this.setState({ myIndex: 1 }) the slide with index 1 is coming immediately. Not smooth like while swipe action or like on the tabs example.

**Comment by oliviertassinari** [comment]
@studentIvan I can't help without a reproduction example. But that sounds like an issue with the usage of the lib, not the lib itself. Closing for now.

**Comment by studentIvan** [comment]
@oliviertassinari is there something like CDN for react-swipeable-views to up it to jsfiddle for example?

**Comment by oliviertassinari** [comment]
codesandbox.io and webpackbin are two great tools.

**Comment by studentIvan** [comment]
Ok, I can't implement it using codesandbox, but I also solved it on my local project. If somebody will catch the problem, the solution is
1. onComponentDidUpdate check that state index should be changed and change it on not full, e.g. 0.1 for 0 and 0.9 for 1
2. onTransitionEnd

```
onTransitionEnd={ () => { if (this.state.slideIndex % 1 !== 0) {
  this.setState({ slideIndex: Math.round(this.state.slideIndex) });
}}}
```
