### ISSUE TITLE
does lazy-load only works on first slide?

### ISSUE THREAD

**Issue by canvas103** [oliviertassinari/react-swipeable-views#342]

**Comment by oliviertassinari** [comment]
Yes, otherwise you need to use the virtualization.

**Comment by platonish** [comment]
Hi, I tried using the `virtualize` HOC as explained in this [demo](https://react-swipeable-views.com/demos/demos/#virtualize): 
```javascript
const VirtualizedSwipeableViews = virtualize(SwipeableViews);

const slideRenderer = ({ index }) => (
  {
    0: <Dash/>,
    1: <Meetings/>,
    2: <LeadStatus/>
  }[index]
);

class HomeComponent extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      screen: 0
    };
  }

  handleSwipe = value => {
    this.setState({ screen: value });
  };

  handleBottomTabSelect = (event, value) => {
    this.setState({ screen: value });
  };

  render() {
    const { screen } = this.state;

    return (
      <StyledHomeComponent>
        <AppBar />
        <VirtualizedSwipeableViews
          index={screen}
          onChangeIndex={this.handleSwipe}
          className="content-wrapper"
          overscanSlideAfter={0}
          slideRenderer={slideRenderer}
        />
        <BottomTabs value={screen} onChange={this.handleBottomTabSelect} />
      </StyledHomeComponent>
    );
  }
}
```
The second and third screens are lazy-loaded only once the user swipes left to them, so that works great. However the swipe animation goes back and forth once every time I swipe to a new screen. Here's a [screencap](https://youtu.be/08Sw434hShI). Thanks in advance!

**Comment by platonish** [comment]
I fixed this by adding a `key` prop to every element in `slideRender` (as clearly mentioned in the demo), like so:
```javascript
const slideRenderer = ({ index, key }) => {
  return(
    {
      0: <Dash key={key} />,
      1: <Meetings key={key} />,
      2: <LeadStatus key={key} />
    }[index]

  );
};
```
However I still get a warning on my console saying `Warning: react-swipeable-view: one of the children provided is invalid: null. We are expecting a valid React Element`. Also, swiping right from slide 0 tries to render slide -1, then slide -2, and so on. This is also the case in the demo: 

![image](https://user-images.githubusercontent.com/24620401/37250633-1319c0dc-2527-11e8-8cf0-4c4c2e7550ef.png)

**Comment by oliviertassinari** [comment]
@platonish Please don't comment on closed issue for a new one; 

> However I still get a warning on my console saying Warning: react-swipeable-view: one of the children provided is invalid: null. We are expecting a valid React Element.

This mean one of your children is `null`.

> Also, swiping right from slide 0 tries to render slide -1, then slide -2, and so on. This is also the case in the demo:

Yes, the virtualize HOC doesn't bound the index. You have a `slideCount` property for this.
