### ISSUE TITLE
SwipeableView inside SwipeableView auto height

### ISSUE THREAD

**Issue by ashl1** [oliviertassinari/react-swipeable-views#344]
Thank for this component.
It might be similar to #339 and #159 I use one `swipeViewInner` inside another `swipeViewOutside`. I use this configuration to show transition animations for element is opened from list.
This configuration works badly. I see that height isn't properly updated when switching between slides in `swipeViewInner`.
I tried to investigate the problem and found that the new height is set with `setState(height)` and assume the outer swipe view handle changes before new height is applied (inner view is renedered actually).

What do you suggest on this?
* Maybe we can make argument to provide custom `updateHeight()` function?
* Maybe we should run `updateHeight()` if `child.offsetHeight` is changed after each `onDidUpdate`?
* Maybe we can use props for active slide height?

I see the complexity of the problem in that the real height is set after executing "render" function. This makes cascade updating of the height more complex in case of nesting "swipeView".

**Comment by oliviertassinari** [comment]
I'm going to close the issue for #339. This is a limitation of the component. I don't want to add any more logic to handle it. Thanks for raising it.
