### ISSUE TITLE
Ignore absolutely positioned elements

### ISSUE THREAD

**Issue by warrenmcquinn** [oliviertassinari/react-swipeable-views#345]
I'm absolutely positioning some "overlay" elements on the SwipeableViews component, and I'm wondering two things: 
* Has anyone has found a way to listen to "scroll" events on those absolutely positioned elements, or
* Has anyone found a way to ignore those absolutely positioned elements when listening for "scroll" events on the SwipeableViews component? 

Thanks!

**Comment by oliviertassinari** [comment]
Elements absolutely positioned inside a slide are ignored by the native scroll handling logic:

https://github.com/oliviertassinari/react-swipeable-views/blame/5835f94383ddbc7d16baea4df8404d3f70262830/packages/react-swipeable-views/src/SwipeableViews.js#L169-#L170

I'm not sure to understand what's your question.

**Comment by warrenmcquinn** [comment]
Ok, thank you for answering my question.
