### ISSUE TITLE
"Resistance" at edges, but no vertical scrolling?

### ISSUE THREAD

**Issue by warrenmcquinn** [oliviertassinari/react-swipeable-views#346]
I'm using this component on the y-axis, and I'm wondering if anyone has figured out how to enable normal scroll behavior when on the first or last slides.

For example: on the demos page, demo 9 doesn't scroll the page when swiping down on slide nº 1 or up on nº 3. http://oliviertassinari.github.io/react-swipeable-views/

**Comment by oliviertassinari** [comment]
@warrenmcquinn You can't have both resistance effect and a vertical scrolling with the current implementation. You need to pick one. Browsers have an extra logic to handle this case. This is something we could do too.

**Comment by warrenmcquinn** [comment]
Okay, I just want vertical scrolling. I disabled resistance, and I still can't scroll vertically when on the first / last slides. 

The logic seems pretty straightforward, and I think this feature would make this code the best available view component for React.

**Comment by warrenmcquinn** [comment]
Perhaps I can explain better:

I have a SwipeableView component with height 100vh. Once the user has the component fully in view, they should be able to leave if they swipe down while on the first slide, or swipe up while on the last side.

That makes sense, no?
