### ISSUE TITLE
Prevent click on element when swiping using mouse

### ISSUE THREAD

**Issue by frendyguo** [oliviertassinari/react-swipeable-views#347]
How to prevent clicking on certain element when swiping ?

**Comment by oliviertassinari** [comment]
I don't follow, how do you end-up clicking on an element when swiping?

**Comment by frendyguo** [comment]
I have no problem on mobile device, but on a desktop view (with mouse event), whenever the starting and ending position of my mouse event is still within the element (with `onclick` event listener), it triggers the click event

**Comment by oliviertassinari** [comment]
> whenever the starting and ending position of my mouse event is still within the element

From what I understand, them mouse doesn't change enough to be considered a swipe, hence, we don't do anything.

**Comment by frendyguo** [comment]
> From what I understand, the mouse doesn't change enough to be considered a swipe, hence, we don't do anything.

But it did swiped, the only way to prevent the `click` is to swipe beyond it's container. Anyway, do you have any workaround for this ?

**Comment by hodgef** [comment]
I am having this issue as well. If you have an element with an onClick, swiping over this element will trigger the onClick, when it should not. This happens when mouse events are enabled (enableMouseEvents="true").

It seems that enableMouseEvents is triggering all onClick, onMouseUp, onMouseDown, etc events on children elements on swipe.

Any thoughts on this @oliviertassinari ?

**Comment by oliviertassinari** [comment]
@hodgef Thanks for the extra information. I better understand what's going on now. I fear it's happening at a different level of abstraction. I don't see how it could be something handled by the library. I see two options.
1. You stop the propagation of the mouse move event on the element that listens for the click event 
```jsx
    <SwipeableViews enableMouseEvents>
      <div style={Object.assign({}, styles.slide, styles.slide1)}>
        <button
          type="button"
          onMouseMove={event => event.stopPropagation()}
          onClick={() => console.log('onClick')}
        >
          slide n°1
        </button>
      </div>
      <div style={Object.assign({}, styles.slide, styles.slide2)}>slide n°2</div>
      <div style={Object.assign({}, styles.slide, styles.slide3)}>slide n°3</div>
   </SwipeableViews>
```
https://codesandbox.io/s/k56wzz4407
2. You can prune the false-positive click event:
```jsx
let currentIndex;

function App() {
  return (
    <SwipeableViews
      enableMouseEvents
      onSwitching={index => {
        setTimeout(() => {
          currentIndex = index;
        });
      }}
    >
      <div style={Object.assign({}, styles.slide, styles.slide1)}>
        <button
          type="button"
          onClick={() => {
            if (currentIndex === Math.round(currentIndex)) {
              console.log('onClick');
            }
          }}
        >
          slide n°1
        </button>
      </div>
      <div style={Object.assign({}, styles.slide, styles.slide2)}>slide n°2</div>
      <div style={Object.assign({}, styles.slide, styles.slide3)}>slide n°3</div>
    </SwipeableViews>
  );
}
```

https://codesandbox.io/s/yr27wxq19

**Comment by lsirivong** [comment]
Here's an alternative solution for anyone else coming across this.

Attempting to detect a drag on the clickable element before preventing the click handler:

```jsx
class SwipeableLink extends React.Component {
  handleMouseDown = e => {
    // store mouse position when click starts
    this.x = e.screenX;
  }

  handleClick = e => {
    const delta = Math.abs(e.screenX - this.x);

    if (delta > 10) {
      // If mouse moved more than threshold, ignore the click event
      e.preventDefault();
    }

    this.x = 0;
  }

  render() {
    return (
      <a
        href="https://github.com/oliviertassinari/react-swipeable-views/issues/347"
        onMouseDown={this.handleMouseDown}
        onClick={this.handleClick}
        style={styles.link}
        target="_blank"
        rel="noopener noreferrer"
        {...this.props}
      >
        {this.props.children}
      </a>
    );
  }
}

function App() {
  return (
    <SwipeableViews enableMouseEvents>
      {[1, 2, 3].map(i => (
        <div key={i} style={Object.assign({}, styles.slide, styles[`slide${i}`])}>
          <SwipeableLink>
            slide n°{i}
          </SwipeableLink>
        </div>
      ))}
    </SwipeableViews>
  );
}
```

https://codesandbox.io/s/4qyyo1j2mx
