### ISSUE TITLE
Unable to swipe from inside the Iframe element

### ISSUE THREAD

**Issue by frendyguo** [oliviertassinari/react-swipeable-views#348]

**Comment by oliviertassinari** [comment]
@frendyguo Do you have a reproduction example?

**Comment by oliviertassinari** [comment]
I couldn't reproduce the issue. I'm suspecting the issue is not linked to this library.

**Comment by bhar4t** [comment]
I am using  `react-swipeable-views` inside this I am using iFrame, when I want to swipe from iFrame view to another view which is not working.
