### ISSUE TITLE
How to position Floating Button Absolute/Fixed in the View(Say View2 and View3)

### ISSUE THREAD

**Issue by chattes** [oliviertassinari/react-swipeable-views#349]
Hi,
Great plugin and really handy for mobile centric apps.
I had used this and then got rid of this as I could not figure out how to position my Floating Buttons absolutely or Fixed (Bottom Right) in each of the Three Views . Any ideas how this can be achieved>

Thanks

**Comment by brason** [comment]
Why was this closed? I am wondering the same thing.

**Comment by oliviertassinari** [comment]
@brason The question seems unrelated to the lib. You can always try on StackOverflow.

**Comment by damianobarbati** [comment]
@chattes @brason this should help: https://github.com/oliviertassinari/react-swipeable-views/issues/124#issuecomment-356972288
