### ISSUE TITLE
Demo 12     Custom width of slides  is there  have some example code or  source code?

### ISSUE THREAD

**Issue by sunny628** [oliviertassinari/react-swipeable-views#352]
demo12  i want to use custorm width of slides  
is there have some example  code or  source code?
http://oliviertassinari.github.io/react-swipeable-views/

**Comment by oliviertassinari** [comment]
The source code is here https://github.com/oliviertassinari/react-swipeable-views/blob/5835f94383ddbc7d16baea4df8404d3f70262830/docs/src/demo/DemoWidth.js
