### ISSUE TITLE
When using Virtualize HOC for infinite loop, swiping works fine, but when changing the index with the previous and next button the the slides do not animate

### ISSUE THREAD

**Issue by Rilliano** [oliviertassinari/react-swipeable-views#353]
I've implemented the infinite swipe like this: 

```javascript

import SwipeableViews from 'react-swipeable-views'
import virtualize from 'react-swipeable-views-utils/lib/virtualize'
import mod from 'react-swipeable-views-core/lib/mod'
...

const EnhancedSwipeableViews = virtualize(SwipeableViews)
const slideRenderer = ({key, index}) =>  (
 <HouseCard
    key={index}
    title={props.houseTypes[(mod(index, props.houseTypes.length))].title}
    slug={props.houseTypes[(mod(index, props.houseTypes.length))].slug}
 /> )
    
...
<EnhancedSwipeableViews
  index={this.state.swipeIndex}
 onChangeIndex={this.handleChangeIndex}
 slideRenderer={slideRenderer}
/>

<ArrowNext
   key='next'
   onClick={() => this.setState({swipeIndex: this.state.swipeIndex + 1})}
>
<ArrowPrev
   key='prev'
   onClick={() => this.setState({swipeIndex: this.state.swipeIndex - 1})}
>
```

I've implemented the SwipeableView with virtualize as seen in the code above. The infinite loop works pretty good while swiping. However when i click the ArrowNext or the ArrowPrev button to go the the next or previous slide, the slides changes postiton, but the transition from the slide change is gone. The correct slide appears with no transition at all. Does someone know what the solution is to the problem?

**Comment by retrojorgen** [comment]
I am having the same issue in my project. Actually the animation stops at the third slide (3/8 slides)
Any solution to this?

**Comment by retrojorgen** [comment]
So, I think I found the issue. its in getDisplaySameSlide.js in core. 
it says 

var oldChildren = props.children[props.index]; But props.children[0] is where the list of items actually recides. so this will fail after the second slide

**Comment by oliviertassinari** [comment]
@Rilliano I have tried reproducing your issue with no luck.
```jsx
import React from 'react'
import SwipeableViews from 'react-swipeable-views'
import virtualize from 'react-swipeable-views-utils/lib/virtualize'
import mod from 'react-swipeable-views-core/lib/mod'

const EnhancedSwipeableViews = virtualize(SwipeableViews)

const slideRenderer = ({ key, index }) => (
  <div key={index}>{index}</div>
)

class Demo extends React.Component {
  state = {
    swipeIndex: 0,
  }

  handleChangeIndex = (index) => {
    this.setState({
      swipeIndex: index,
    })
  };

  render()  {
    return (
      <div>
        <EnhancedSwipeableViews
          index={this.state.swipeIndex}
          onChangeIndex={this.handleChangeIndex}
          slideRenderer={slideRenderer}
          enableMouseEvents
        />
        <button type="button"
          onClick={() => this.setState({ swipeIndex: this.state.swipeIndex - 1 })}
        >
          previous
        </button>
        <button type="button"
          onClick={() => this.setState({ swipeIndex: this.state.swipeIndex + 1 })}
        >
          next
        </button>
      </div>
    );
  }
}

export default Demo;
```

https://codesandbox.io/s/x9pl77476o

> The correct slide appears with no transition at all.

The only way I can reproduce this is by clicking very fast and repetitively on the `previous` button. It's the expected behavior when you reach the windowing edges. You can increase the windowing edges with the `overscanSlideBefore` and `overscanSlideAfter` properties.

**Comment by oliviertassinari** [comment]
@retrojorgen Sorry, your comment isn't actionable. It would be perfect if you could provide a reproduction example on codesandbox like the one I provided above.

**Comment by Jianru-Lin** [comment]
This bug happens when you put this line inside render function:

```
const EnhancedSwipeableViews = virtualize(SwipeableViews)
```

I made this mistake, and when I move it outside everything becomes fine.

😸

**Comment by ckohtz** [comment]
@Jianru-Lin Thank you!!!!
