### ISSUE TITLE
ContainerStyle Customize height  as per content size.

### ISSUE THREAD

**Issue by PardeepWildnet** [oliviertassinari/react-swipeable-views#354]
I want to set height of container for Swipeable view as per content size. As of now height is being set according to the tab having maximum content.

For example content for tab1 is of 400px height and for tab2 its 50px
so height should be 400px and 50px respectively not 400px for both.

Gone through this issue but seems not resolved yet 
* https://github.com/oliviertassinari/react-swipeable-views/issues/322#issuecomment-336091932

**Comment by PardeepWildnet** [comment]
RESOLVED !! closing this...

Just need to bound 
`animateHeight = { this.state.customizeHeight }`

with some variable and need to toggle their value to `true` on swipe and on Tab change, because if you set value of `animateHeight = { true }` this is causing issue for the first time.

**Comment by ikelee** [comment]
Did this work for you? It worked for me a couple times but its causing a crash as soon as I swipe.

**Comment by ikelee** [comment]
<SwipeableViews enableMouseEvents animateHeight={this.state.animate} onClick={this.handleClick} >  This is what I have, maybe it's requiring too much processing power? I don't really know why it's crashing

**Comment by Wgil** [comment]
Couldn't figure this out... My current behavior is that each slide is taking the height of the highest one. If I set `animateHeight` the height of each slide is adjusted fine but I don't want to animate that...

A workaround I did was to set `display: none` on the slides that are not currently visible...

**Comment by gabrigode** [comment]
Years late workaround!  🤣 

It seems using `action={(actions) => {actions.updateHeight();}}` as a prop in SwipeableViews fix the problem!
