### ISSUE TITLE
Tabs do not change when swiped

### ISSUE THREAD

**Issue by mjohnson290** [oliviertassinari/react-swipeable-views#355]
Finding an issue where the tabs are not being informed of a new currentSlide. Happens in my local environment as well as in the [demo page](http://oliviertassinari.github.io/react-swipeable-views/).

Unless I'm missing something, is there a workaround for this?

**Comment by oliviertassinari** [comment]
Oops, I should I have been messing around the demo.

**Comment by oliviertassinari** [comment]
I'm closing this issue for #358.
