### ISSUE TITLE
Having an issue calling Swipeable in JSX

### ISSUE THREAD

**Issue by kwkau** [oliviertassinari/react-swipeable-views#357]
This is the error i get when i reference the Swipeable import in my JSX code
SwipeableViews does not have any constructor or call signatures
this is how i imported SwipeableViews 
import * as SwipeableViews from "react-swipeable-views";

i tried a different import style
import SwipeableViews from "react-swipeable-views";
but i got a simillar error
SwipeableViews is not a constructor function for JSX elements

am using React version 16.0.0 with typescript version 2.5.3

**Comment by oliviertassinari** [comment]
I fear there is nothing I can't do to solve the issue. Maybe with a reproduction example, I will be able to help.

**Comment by kwkau** [comment]
@oliviertassinari  thanks for the quick response sorry for not including my code in my earlier post.
i hope you can resolve this issue for me.
import React from 'react';
import {Tabs, Tab} from 'material-ui/Tabs';
import SwipeableViews from 'react-swipeable-views';

const styles = {
  headline: {
    fontSize: 24,
    paddingTop: 16,
    marginBottom: 12,
    fontWeight: 400,
  },
  slide: {
    padding: 10,
  },
};

export class EmployeeSetup extends React.Component<any, any> {

  constructor() {
    super();
    this.state = {
      slideIndex: 0,
    };
  }

  handleChange = (value) => {
    this.setState({
      slideIndex: value,
    });
  };

  render() {
    return (
      <div>
        <Tabs
          onChange={this.handleChange}
          value={this.state.slideIndex}
        >
          <Tab label="Tab One" value={0} />
          <Tab label="Tab Two" value={1} />
          <Tab label="Tab Three" value={2} />
        </Tabs>
        <SwipeableViews
          index={this.state.slideIndex}
          onChangeIndex={this.handleChange}
        >
          <div>
            Tab 1
          </div>
          <div style={styles.slide}>
            Tab 2
          </div>
          <div style={styles.slide}>
            Tab 3
          </div>
        </SwipeableViews>
      </div>
    );
  }
}
