### ISSUE TITLE
Switch index without swiping

### ISSUE THREAD

**Issue by mxmlnsllmr** [oliviertassinari/react-swipeable-views#358]
Heyho!

First: Big thanks for creating these swipeable-views. Very gread job :)

I ran into an issue, maybe it's no issue.
I want to change the view without swiping.

Explanation:
I have 3 Screens: 
1. Details
2. Question
3. Question

With swiping I switch between these different views. 
Additionally to the possibility to swipe I have a little sticky navigation, where I want to change between the first and the second view.

Click on the first button --> index 0 should be shown
Click on second button --> index 1 should be shown

I added the index property to the <SwipeableViews> component and then get the right index from my redux-store, but this prop is only for selecting the first shown index, isn't it?

Is it possible to switch the index without swiping?

Thank you,
mxmlnsllmr

**Comment by oliviertassinari** [comment]
> Is it possible to switch the index without swiping?

Yes, it's. You need to control the component with the `index` and `onChangeIndex` property. We have a demo demonstrating it: https://github.com/oliviertassinari/react-swipeable-views/blob/3c3e9f03dcf563169e8909df9ce3217e42b44867/docs/src/demo/DemoTabs.js. But for some reason it's no longer working #355. It's most likely a regression integration with [Material-UI](https://github.com/callemall/material-ui).

**Comment by kmartinezmedia** [comment]
The onChangeIndex isn't working for me. Could it be this is why tabs are not updating when view is swiped?

**Comment by oliviertassinari** [comment]
I will look into it.

**Comment by stevewillard** [comment]
I'm also trying to use the `onChangeIndex` but it is not firing when I programmatically change the index.

**Comment by oliviertassinari** [comment]
We have an up-to-date demo in https://material-ui-next.com/demos/tabs/#full-width.

**Comment by oliviertassinari** [comment]
> The onChangeIndex isn't working for me. Could it be this is why tabs are not updating when view is swiped?

@kmartinezmedia We had an issue with a beta version of React in the documentation. I have upgraded it to the latest stable version. The demo is now working as expected.

**Comment by oliviertassinari** [comment]
>I'm also trying to use the onChangeIndex but it is not firing when I programmatically change the index.

@stevewillard `onChangeIndex` is not supposed to trigger when you change the `index`. It will fire when the user interacts with the component. This is how controlled components work.
