### ISSUE TITLE
Avoid setting state while animating

### ISSUE THREAD

**Issue by sorin-davidoi** [oliviertassinari/react-swipeable-views#362]
Thanks a lot for this component, we have been using it in https://github.com/tootsuite/mastodon/ for the past few months and it is working great 👍 

However, we have noticed that the animations can get janky on mobile devices (especially Firefox on Android - see https://github.com/tootsuite/mastodon/issues/5162 for videos, why this is happening and a possible solution). Was wondering if you would accept a patch that would avoid re-rendering the component during the animation.

**Comment by oliviertassinari** [comment]
The corresponding issue is interesting to read. Thanks for opening this issue.
The current implementation tradeoff is explained in https://github.com/oliviertassinari/react-swipeable-views#performance-on-browser. Are the slides pruning the rerendering with a PURE logic?

**Comment by sorin-davidoi** [comment]
There were some which weren't pruned, but even with pruning it takes 10-15ms (Chrome, desktop) for React to run. It still janks on mobile.

Screenshot from the dev tools while swiping (Chrome, desktop) - between 20 and 30 frame per second.
![image](https://user-images.githubusercontent.com/2109702/32253474-6448a826-be9b-11e7-9a03-ca88c5c978d7.png)

Code running on each `touchmove` event:
![image](https://user-images.githubusercontent.com/2109702/32253505-8b53c310-be9b-11e7-942d-80eb322d25c5.png)

**Comment by oliviertassinari** [comment]
I'm surprised pruning the children isn't enough. I have experienced impressive speedup with such method in the past. How many slides do you render? Going back to your question. Yes, I'm opened not to call setState during the touchmove event handling. It should be faisable.

**Comment by sorin-davidoi** [comment]
We have five slides. I'll double check to make sure I didn't miss any pruning. If not, I'll see if I avoid `setState`.

**Comment by oliviertassinari** [comment]
@sorin-davidoi Any update? Do we still need this performance improvement tip?

**Comment by sorin-davidoi** [comment]
Yes, I'd say it is still needed. I didn't miss any pruning and it still janks in Firefox on Android. Unfortunately, I don't know when I'll have time to attempt a proper fix - the small snippet I posted is not enough.
