### ISSUE TITLE
this.activeSlide is undefined, but not null

### ISSUE THREAD

**Issue by damusnet** [oliviertassinari/react-swipeable-views#365]
I am trying to use the newly introduced `updateHeight` callback #359, and am running into a weird bug.

![image](https://user-images.githubusercontent.com/433409/32472536-fe8d442a-c317-11e7-91ab-9e3ddf0111d2.png)

![image](https://user-images.githubusercontent.com/433409/32472549-0c85a86a-c318-11e7-8861-609ac6efdd24.png)

It looks like the `this` context got lost, and only now contains the `updateHeight` function. And because `activeSlide` is `undefined` and not `!== null`, the whole thing crashes with:
```
Uncaught TypeError: Cannot read property 'children' of undefined
    at Object.updateHeight (SwipeableViews.js?3723ee1:693)
```

Not sure if this is me doing something wrong, so would appreciate some help.

This is a great feature by the way, I was very happy to find it just now, and see that it was shipped just four days ago, exactly when I need it! ^^

cc @stfny222

**Comment by oliviertassinari** [comment]
Oh, we should have tested it more thoroughly. What you are describing is expected. We need to bind the method. I'm on it.

**Comment by damusnet** [comment]
Thank you Olivier, you're the best!

**Comment by oliviertassinari** [comment]
@damusnet published, thank you for taking the time to open an issue!

**Comment by damusnet** [comment]
I have verified that it works fine now! Thanks again for a great addition, and for your reactivity!
