### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by oliviertassinari** [oliviertassinari/react-swipeable-views#37]
I think that we have a memory leak somewhere. However, I can't narrow it down.

![capture d ecran 2016-02-27 a 16 29 41](https://cloud.githubusercontent.com/assets/3165635/13373715/84928a2a-dd6f-11e5-97a0-f8ca0746cf14.png)

**Comment by jardakotesovec** [comment]
@oliviertassinari I tried to use profiling on one of the demos and did not see any memory growth. How  did you achieve this result?

**Comment by oliviertassinari** [comment]
I'm using the first demo of the website. Could you post your result? I'm wondering if this isn't link to the internal of react-motion.

**Comment by jardakotesovec** [comment]
Here is demo1 from website.
![screenshot 2016-03-05 18 08 44](https://cloud.githubusercontent.com/assets/1590681/13549004/56f72614-e2fd-11e5-81f1-1902964e33c7.png)

But for memory leaks I think its easier to spot them using Profiles -> Record Heap Allocations.  Which makes pretty easy to spot something unallocated. And in case of the first demo - it occasionally just produced some V8 stuff..  Which I think does not indicate leak in your code..  But someone more educated on V8 would have to answer that.

![screenshot 2016-03-05 18 14 20](https://cloud.githubusercontent.com/assets/1590681/13549060/42f8f196-e2fe-11e5-9c4d-75eb3ca78ce3.png)

**Comment by oliviertassinari** [comment]
@jardakotesovec Oh, that's interesting! Are you saying the memory increase is directly linked to V8?

**Comment by jardakotesovec** [comment]
@oliviertassinari Yes, I think so... As described for example [here](http://www.html5rocks.com/en/tutorials/speed/v8/). V8 does optimistic optimization which sometime goes wrong and has to fall back to original (In some cases its possible to fix code to avoid these deoptimization situation).  And these 'code deopt data' in Snapshot seems to me indicating just that...  and not actual leak in your code.  But I might be wrong... :-)

**Comment by oliviertassinari** [comment]
@jardakotesovec Alright, let's close this issue, thanks :+1:.
