### ISSUE TITLE
[Browser] Virtualized swipeable views unmount and remounts all children on each swipe

### ISSUE THREAD

**Issue by stropitek** [oliviertassinari/react-swipeable-views#370]
When trying the example on the [readme](https://github.com/oliviertassinari/react-swipeable-views/#example-with-virtualize), I noticed that at each swipe all views with an index in range for being rendered were unmounted and remounted.  I would only expect the last view to be mounted and the first one to be unmounted. All other should at most be updated.

Here is a slighly modified example that logs component mounting and unmounting. And below is the output I get as I swipe from index number 4 to index number 5. 

```js
import React, {Component} from 'react';
import ReactDOM from 'react-dom';
import SwipeableViews from 'react-swipeable-views';
import {virtualize} from 'react-swipeable-views-utils';
const VirtualizeSwipeableViews = virtualize(SwipeableViews);
class Slide extends Component {
    componentDidMount() {
        console.log(this.props.index, 'did mount');
    }
    componentWillUnmount() {
        console.log(this.props.index, 'will unmount');
    }
    render() {
        const index = this.props.index;
        return <div>{`slide n°${index}`}</div>;
    }
}

const slideRenderer = ({key, index}) => {
    return (
        <Slide key={key} index={index} />
    );
};

const node = document.getElementById('app');
const root = <VirtualizeSwipeableViews slideRenderer={slideRenderer} />;
ReactDOM.render(root, node);
```
![image](https://user-images.githubusercontent.com/4118690/32995868-06e1fa68-cd7b-11e7-82df-102a2325f198.png)

**Comment by oliviertassinari** [comment]
Sorry, I couldn't reproduce your issue with the provided snippet:
https://codesandbox.io/s/00zqm7mpql

**Comment by stropitek** [comment]
Thanks for taking the time to try it out.

I was a bit confused at the beginning but then I realized I included the example in a project using preact (it uses webpack's `resolve` to replace imports from react to preact, therefore the misleading code snippet).

Here is another example using preact: https://codesandbox.io/s/jmkrl2p29

I don't know if you support preact... feel free to reopen this if you do. And sorry about the confusion!

**Comment by oliviertassinari** [comment]
Oh, it's good to see that the library works with preact :). It sounds like a preact related issue.

**Comment by bmueller-sykes** [comment]
I'm actually seeing a similar issue. Not sure if I should open a new ticket or append to this one, so I'm going to try appending to this one for now.

The code below is running as the only React component inside my top-level `App.js` component. I'm running on top of `create-react-app`, `React 15.6.2`, `react-swipeable-views 0.12.12`, `react-swipeable-views-utils 0.12.11`, and `material-ui 0.19.2`. 

Here's the entirety of the code:
```
import React, { Component } from 'react';

import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import { Tabs, Tab } from 'material-ui/Tabs';
import SwipeableViews from 'react-swipeable-views';
import { virtualize } from 'react-swipeable-views-utils';

const VirtualizeSwipeableViews = virtualize(SwipeableViews);


class Slide extends Component {
  componentDidMount () {
    console.log("MOUNT", this.props.index)
  }

  componentWillUnmount () {
    console.log("UNMOUNT", this.props.index)
  }
  render () {
    return (
      <div>
        Slide {this.props.index}
      </div>
    )
  }

}

const slideRenderer = ({key, index}) => <Slide key={key} index={index} />

export default class Swipe extends Component {

  constructor(props) {
    super(props)
    this.state = {
      slideIndex: 0
    }
  }

  handleTabChange = (index) => {
    this.setState({
      slideIndex: index
    })
  }

  render () {
    const { slideIndex } = this.state;

    return (
      <MuiThemeProvider>
        <div>
          <Tabs
            onChange={this.handleTabChange}
            value={slideIndex}
          >
            <Tab value={0} label='One' />
            <Tab value={1} label='Two' />
          </Tabs>
          <VirtualizeSwipeableViews index={slideIndex} slideRenderer={slideRenderer} />
        </div>
      </MuiThemeProvider>
    )
  }
}
```

When I run the code locally (`localhost:3000`) I see this:

MOUNT 0
MOUNT -3
MOUNT -2
MOUNT -1
MOUNT 1
MOUNT 2

...and then when I switch, I see this in the console:

MOUNT 3
UNMOUNT -3

...and switching back, I see
UNMOUNT 3
MOUNT -3

So that seems broken in two ways. First, I don't understand the multiple "MOUNT"s, and second, it seems odd that the indexes would be 3 and -3, rather than 0 and 1, (since random indices make it hard to line up with, say, an array of components to render)

**Comment by oliviertassinari** [comment]
@bmueller-sykes Have closer look at our demos. You miss the `key`.

**Comment by bmueller-sykes** [comment]
@oliviertassinari Thanks for the reply! I'm looking at the demos on this page:

https://react-swipeable-views.com/demos/demos/

...and I don't see where I'm missing the `key`. There already is one in the `slideRenderer` function (`<Slide key={key} index={index} />`). There wasn't one in my `Slide` component, but if I do add one to the `render` method:

```
  render () {
    return (
      <div key={this.props.key}>
        Slide {this.props.index}
      </div>
    )
  }
```

...I get the same behavior. In fact, if I add a `console` statement to the render method, I see that there are six initial renders with index values going from -3 to 2 (-3, -2, -1, 0, 1, 2). 

I'm probably missing something stupid, and if so, I apologize, but I can't see what I'm missing here.

Thanks!

**Comment by bmueller-sykes** [comment]
Actually, quick update, I just realized that `key` isn't even passed down to my `Slide` component, so adding a key within that component's render function isn't even possible. So I'm still stumped.

**Comment by bmueller-sykes** [comment]
Okay, again, sorry if I'm missing something simple, but something still looks broken to me. I've simplified the demo a bit, to get it more in line to your demos. Here's what I have now:

```
import React, { Component } from 'react';

import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import { Tabs, Tab } from 'material-ui/Tabs';
import SwipeableViews from 'react-swipeable-views';
import { virtualize } from 'react-swipeable-views-utils';

const VirtualizeSwipeableViews = virtualize(SwipeableViews);

const slideRenderer = ({key, index}) => {
  console.log("RENDER", key, index)
  return (
    <div key={key}>
      Slide {index}
    </div>
  )
}

export default class Swipe extends Component {

  constructor(props) {
    super(props)
    this.state = {
      slideIndex: 0
    }
  }

  handleTabChange = (index) => {
    this.setState({
      slideIndex: index
    })
  }

  render () {
    const { slideIndex } = this.state;

    return (
      <MuiThemeProvider>
        <div>
          <Tabs
            onChange={this.handleTabChange}
            value={slideIndex}
          >
            <Tab value={0} label='One' />
            <Tab value={1} label='Two' />
          </Tabs>
          <VirtualizeSwipeableViews
            index={slideIndex}
            onChangeIndex={this.handleTabChange}
            slideRenderer={slideRenderer}
          />
        </div>
      </MuiThemeProvider>
    )
  }
}
```

When the component first loads, I get this in the console:

![screen shot 2017-12-07 at 1 23 50 pm](https://user-images.githubusercontent.com/12236379/33734446-f76ab73e-db51-11e7-8ef5-f6b73e274d1d.png)

...and then, when I click on the `TWO` tab, I get this in the console:

![screen shot 2017-12-07 at 1 25 18 pm](https://user-images.githubusercontent.com/12236379/33734488-276e9e64-db52-11e7-98de-cbcc15e5ce13.png)

I think I have all the `key` props in the right places, so I'm really struggling to see what's going on here. My simple example appears to be rendering properly, but if I put a React component in the `slideRenderer` function, then it's going to mount and unmount several times during slide changes.

**Comment by oliviertassinari** [comment]
@bmueller-sykes This is expected. lifecycles hooks are different from the render calls. Sorry but I will stop answer your question.

**Comment by bmueller-sykes** [comment]
Okay, please answer one more question? (-;

So if I change the body of `slideRenderer` to this:

`const slideRenderer = ({key, index}) => <Slide key={key} index={index} />`

...and then have this:

```
class Slide extends Component {

  componentDidMount() {
    console.log("SLIDE MOUNT")
  }

  componentWillUnmount() {
    console.log("SLIDE UNMOUNT")
  }

  render () {
    return (
      <div>Slide {this.props.index}</div>
    )
  }
}
```

...then I get 6 `SLIDE MOUNT` declarations when `VirtualizeSwipeableViews` first loads. Is that expected? That seems less than ideal, especially if there were side effects like a data fetch in `componentDidMount()`.

Switching from one tab to another triggers only a single MOUNT and a single UNMOUNT, so that seems right.

Sorry to pester.

**Comment by oliviertassinari** [comment]
> then I get 6 SLIDE MOUNT declarations when VirtualizeSwipeableViews first loads. Is that expected? 

@bmueller-sykes Yes, It's.

**Comment by bmueller-sykes** [comment]
Oh, right! I'm so sorry! I get it now. Thanks so much for your patience.
