### ISSUE TITLE
Tags dd/dl/dt ignored when computing height

### ISSUE THREAD

**Issue by ecoquelin** [oliviertassinari/react-swipeable-views#38]
I have used your component and defined a slide with the following content:

`<dl>
              <dt>Reference</dt>
              <dd>Test</dd>
              <dt>Reference2</dt>
              <dd>Test2</dd>
            </dl>`

The slide height is not correctly computed and as a result ascroll bar appears. This problem doesn't occur when "simple" div/h1/p are being used.

**Comment by oliviertassinari** [comment]
I couldn't reproduce this issue. Are you applying some specific style to those elements?
I'm closing this issue.

**Comment by ecoquelin** [comment]
To be honnest, this is already far too old... I was testing react and some components like yours. Will revert back to you if starting again some work on this technology using your component.
