### ISSUE TITLE
[DISCUSSION] Commented will-change for Firefox browser

### ISSUE THREAD

**Issue by tanhauhau** [oliviertassinari/react-swipeable-views#380]
May I know the reason of commenting this [line](https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views/src/SwipeableViews.js#L53) out? What is the issue in Firefox?

**Comment by oliviertassinari** [comment]
@tanhauhau It's creating glitches.

**Comment by tanhauhau** [comment]
Can explain more about the glitches?

**Comment by oliviertassinari** [comment]
@tanhauhau I encourage you to try out without this line commented.
