### ISSUE TITLE
Poor performance on phonegap/chrome on Android

### ISSUE THREAD

**Issue by razorxan** [oliviertassinari/react-swipeable-views#381]
I really can't find a way to get this component working smoothly on my device.
It's super stuttering during swipes (and pretty much unusable) and i guess is something related to the rerendering during animations.
HoC didn't help. If you can help me understand what I am doing wrong it would be really appreciated.

Here's my component
https://codepaste.net/6ke1av

**Comment by oliviertassinari** [comment]
It should be much better with #362

**Comment by oliviertassinari** [comment]
Also from your example, you have the opportunity to prune the rendering tree of the children with a pure logic. https://github.com/oliviertassinari/react-swipeable-views#performance-on-browser

**Comment by razorxan** [comment]
can you explain me what do you mean by "pure logic" and guide me through the process?

**Comment by oliviertassinari** [comment]
> what do you mean by "pure logic"

@razorxan You have an example here
https://github.com/oliviertassinari/react-swipeable-views/blob/06dab1f6990d06913b7034b2333b299228ea9499/docs/src/demo/DemoAnimateHeight.js#L37
