### ISSUE TITLE
[Question] Incorporate pips to indicate the index of the slide?

### ISSUE THREAD

**Issue by alanbuchanan** [oliviertassinari/react-swipeable-views#397]
I suggest it may be useful to show 'pips' or 'dots' to indicate the index of the slide in the context of all the slides available, similar to how it is show in Ant Mobile's carousel: https://mobile.ant.design/components/carousel/

![screen shot 2017-11-27 at 12 15 20](https://user-images.githubusercontent.com/10364894/33266329-138c2124-d36d-11e7-8764-55c2f25fc918.png)

- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |     0.12.12    |
| React                  |    15.6.2     |

**Comment by oliviertassinari** [comment]
We have a demo with this use case. Is it enough?
https://github.com/oliviertassinari/react-swipeable-views/blob/f06e45f1d22a6ee062a3892b862bd2f834239a1d/docs/src/pages/demos/DemoAutoPlay.js#L51

**Comment by alanbuchanan** [comment]
I missed that! My mistake.
