### ISSUE TITLE
Swiper increase width of page

### ISSUE THREAD

**Issue by chrismowbray** [oliviertassinari/react-swipeable-views#399]
Using the react-swipeable-views component increases the width of the page. This has a knock on effect anywhere I use CSS flex etc...

```
import Swiper from 'react-swipeable-views';

  return (
    <Swiper>
        {props.content}
    </Swiper>
  );
```

props.content is an array of components.

**Comment by chrismowbray** [comment]
With further inspection it looks like the react-swipeable-views component is enforcing an min-width

**Comment by oliviertassinari** [comment]
Your issue has been closed because it does not conform to our issue requirements. 
Please provide a full reproduction test case. This would help a lot 👷 .
A live example would be perfect. The **codesandbox.io** template _may_ be a good starting point. Thank you!

**Comment by oliviertassinari** [comment]
I can't find any reference to minWidth. Let me know if you have more information about the issue.
