### ISSUE TITLE
RTL issue

### ISSUE THREAD

**Issue by soroushm** [oliviertassinari/react-swipeable-views#405]
i Try to use SwipeableViews in rtl but unfortunately not working as well

i figure up what is the problen in "SwipeableViews.js" line 50 direction style is hard coded "LTR" 
provide direction is unnecessary 

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  | 0.12.12  |
| React                  | 15.4.2 |
| platform               | windows|
| etc                    |         |

**Comment by oliviertassinari** [comment]
Please refer to the RTL example of the documentation. Let us know if you find an issue with it.

**Comment by soroushm** [comment]
but why ? 
i try to remove "SwipeableViews.js" line 50 direction and working fine 
why we need somethings like that ?
