### ISSUE TITLE
Virtualized swipe broken/buggy on IE 11

### ISSUE THREAD

**Issue by mrTuomoK** [oliviertassinari/react-swipeable-views#407]
Hi. Just noticed my app's virtualized swipe was broken with IE 11 which has been working for a long time now (just happened to test it with IE 11 after a while) The bug also happens on the demo-page (https://react-swipeable-views.com/demos/demos/) so the fault it's not in my app.

Appears when you change the slide multiple times (with keyboard or mouse) --> the slide changes but then the position jumps weirdly and then the correct slide is shown.

I tested an older version in my app and it works so something must have been broken at some point. Works at least on version 0.12.9 (and *-utils also 0.12.9)

I hope this will be looked into and fixed, thanks :)

Ah ... tested on Windows 10 and IE 11.1914.14393.0

**Comment by oliviertassinari** [comment]
@mrTuomoK Are you able to cherry-pick what introduced this regression? This would help a lot.

**Comment by mrTuomoK** [comment]
@oliviertassinari Haven't had time to dig into this yet :/ I'll try to figure out which versions are the last working ones...

**Comment by mrTuomoK** [comment]
OK the last working version is apparently 0.12.10 (with *-utils on 0.12.11) so something breaks after that

**Comment by oliviertassinari** [comment]
Thanks, so it's coming from this release: https://github.com/oliviertassinari/react-swipeable-views/releases/tag/v0.12.11.

**Comment by mrTuomoK** [comment]
Appears so

**Comment by mrTuomoK** [comment]
We might have something on it, but can't confirm yet.... will be back later on if it works @Sebruck

**Comment by appleJax** [comment]
I was having a similar issue, and I fixed it by disabling the `will-change` attribute on the `SwipeableViews` container component:
```js
<SwipeableViews containerStyle={{ willChange: 'initial' }}>
```

**Comment by liamqma** [comment]
Hey @mrTuomoK, I am having a similar issue. Do you have any work around?

**Comment by Tsymalyi** [comment]
I have the same problem.  
How long wait for fix ? :)

**Comment by MatteoGioioso** [comment]
Same problem here. If you need any help or tell me where to look, I could help you on this. Thanks

**Comment by teetotum** [comment]
I currently have the same IE11 issue [445](https://github.com/oliviertassinari/react-swipeable-views/issues/445) / [407](https://github.com/oliviertassinari/react-swipeable-views/issues/407) (they are really the same issue).
I tried this changeset from the open [pull request 432](https://github.com/oliviertassinari/react-swipeable-views/pull/432) and it actually fixed the IE11 issue.

**Comment by jeanpoelie** [comment]
PR #432 has been merged, I will be closing this issue, let me know if (after release) the error still occurs
