### ISSUE TITLE
Horizontal scrolling in nested component not working as expected

### ISSUE THREAD

**Issue by dola** [oliviertassinari/react-swipeable-views#408]
- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate. 
- It might however be related to issue #33.

When putting a nested component with horizontal scrolling inside a swipeable view it is not scrollable when additionally nested in an element with `overflow: hidden`.

## Expected Behavior
Scrolling in the nested element and swiping should both normally work

## Current Behavior
Horizontally scrolling in the nested component does not work at all while the swiping between slides remains working as expected.

## Steps to Reproduce (for bugs)
https://codesandbox.io/s/m7npp2rz78
And demo here: https://m7npp2rz78.codesandbox.io/

1. Open dev tools and simulate a mobile device using the device selection toolbar
2. swipe between separate slides (works as expected) [/]
3. try scrolling horizontally in the long text in the first line of the first slide => [x] does not work

Also:
1. Remove the `overflow: hidden` style from the component wrapping the text (id = `overflowWrapper`)
2. Both swiping and scrolling work as expected again

## Context
I have navigation entries on a page (i.e. a slide in the swipeable) that can grow wide. They usually fit horizontally on a page but might be cut off for narrow screen devices like an iPhone 5. Therefore I have them scrolling (I use `overflow: 'auto'`) when they are wider than the screen so they remain accessible.

## Your Environment
Tested with Chrome (63.0.3239.108 64bit) on Linux and macOS

I'll happily provide more info if any is needed.

**Comment by LaurentRos** [comment]
Hi @dola !

Did you find a solution to your problem ? How did you do it ?
I'm facing the same problem here =/

**Comment by gazpachu** [comment]
I'm also facing the same issue

**Comment by fssantos** [comment]
Guys, one way I found was adding onTouchStart={(e) => {e.stopPropagation()}} as a div props nested in the SwipeableView. It solved my problem but right now I'm getting a Chrome warning:

> [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

It's fired when SwipeableViews.js tries to make a event.preventDefault() as show below probably because it's not the best approach to solve the problem.
```
      // We are swiping, let's prevent the scroll event.
      event.preventDefault(); 
```
Actually I can't understand why SwipeableViews is receiving the event since the stopPropagation for me means a real stop propagation.

Any ideas or other approachs?

**Comment by Ephys** [comment]
> I can't understand why SwipeableViews is receiving the event since the stopPropagation for me means a real stop propagation.

I have the same issue. I think it's because react-swipeable-views uses the native DOM event handlers instead of react's synthetic events.

My solution was to do the same:


```javascript
class MyComponentWhichMustBlockTouchEventsSoItsContentIsScrollableAgain extends React.Component {
  container = React.createRef();

  componentDidMount() {
    const containerNode = this.container.current;

    if (!containerNode) {
      return;
    }

    containerNode.addEventListener('touchstart', this.isolateTouch);
    containerNode.addEventListener('touchmove', this.isolateTouch);
    containerNode.addEventListener('touchend', this.isolateTouch);
  }

  componentWillUnmount() {
    const containerNode = this.container.current;

    if (!containerNode) {
      return;
    }

    containerNode.removeEventListener('touchstart', this.isolateTouch);
    containerNode.removeEventListener('touchmove', this.isolateTouch);
    containerNode.removeEventListener('touchend', this.isolateTouch);
  }

  render() {
    return (
      <div ref={this.container}>
        {this.props.children}
      </div>
    );
  }
}
```

**Comment by phumaster** [comment]
@Ephys Thanks, you saved my life.

**Comment by jeanpoelie** [comment]
The Answer is above :) Thank you Ephys!
