### ISSUE TITLE
How to force VirtualizeSwipeableView to re-render its children?

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [oliviertassinari/react-swipeable-views#414]
Use case:
1. **A** (VirtualizeSwipeableView) displaying dates
2. **B** (SwipeableView) displaying months' names
3. the **A** is currently displaying _28_ (with the following pre-rendered dates: [_28_, _1_, _2_, _3_, _4_])
4. the **B** is currently displaying _February_

If a user now swipes the **B** to point to _March_ (which has _31_ days), the **A** will not re-render its children, since its index (_28_) has not changed.

While it is generally OK, in this particular case I need to somehow let the **A** know that its children must be re-rendered to reflect that after the item _28_ should go items _29_, _30_, and _31_.

The question: how do I do that properly?

## Your Environment
| Tech | Version |
|------------------------|---------|
| react-swipeable-views  |  0.12.12 |
| React                  | 16.2.0 |
| platform               | Google Chrome 64.0.3282.119 (Official Build) (64-bit) |

**Comment by eladonline** [comment]
I join this issue as well

**Comment by AdamLantz** [comment]
The parent component of A and B can handle the shared stated. This state can be used as the index prop of both A and B.

**Comment by caleb-harrelson** [comment]
If somebody wants to put together a codesandbox example we can play with some ways to make this work. Closing until then.
