### ISSUE TITLE
Nested swipeable-views in Safari 9.0 Mobile on iOS 9.2.1

### ISSUE THREAD

**Issue by stonerworx** [oliviertassinari/react-swipeable-views#418]
On iOS 9.2.1 with Safari 9.0 Mobile/13D15 nested swipeable-views are not working correctly. The most outer component always swipes, even when trying to swipe the inner component.
You can see this behaviour on the demo page as well.

## Expected Behavior
The inner component should swipe, not the outer one.

## Current Behavior
The outer component swipes and it is not possible to swipe the inner component

## Steps to Reproduce (for bugs)
1. use a device with iOS 9.2.1 and Safari 9.0
2. go to the demo page and scroll to "Nested"
3. try to swipe the nested component

## Context
We're trying to use a swipeable-view inside a swipeable-view.

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  | 0.12.13 |
| React                  | 16.2.0 |

**Comment by stonerworx** [comment]
I worked around it by capturing the `onTouchStart`event in the inner swipeable-view by wrapping it in another component and stopping the propagation:

```typescript
import * as React from 'react';
import SwipeableViews from 'react-swipeable-views';

interface ImageSliderProps {
  children: children: ReadonlyArray<JSX.Element>;
  className?: string;
}

export class ImageSlider extends React.PureComponent<ImageSliderProps> {
  public render() {
    return (
      <div className={this.props.className} onTouchStart={this.onTouchStart}>
        <SwipeableViews>{this.props.children}</SwipeableViews>
      </div>
    );
  }

  private onTouchStart = (e: React.TouchEvent<HTMLDivElement>) => {
    e.stopPropagation();
  };
}
```

**Comment by caleb-harrelson** [comment]
Closing due to age of OS involved.
