### ISSUE TITLE
Axis=y broken with style -webkit-overflow-scrolling: touch on iOS

### ISSUE THREAD

**Issue by malash** [oliviertassinari/react-swipeable-views#421]
- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

`Axis=y` broken with style `-webkit-overflow-scrolling: touch` on iOS.

## Expected Behavior

Scroll like example [Axis](https://react-swipeable-views.com/demos/demos/#axis).

## Current Behavior

Can not scroll at all.

## Steps to Reproduce (for bugs)

1. Use Safari on iOS (10 or 11)
2. open https://codesandbox.io/s/7jqx825mn0
3. Scroll the good case and bad case demo.

## Context

The difference between two cases is the css style `-webkit-overflow-scrolling: touch` which enabled momentum-based scrolling. 

I tried to disable [this line](https://github.com/oliviertassinari/react-swipeable-views/blob/2b8b1729e3aed9d1bfa31d2fe0cf7ecd710d8766/packages/react-swipeable-views/src/SwipeableViews.js#L449) and it [works](https://codesandbox.io/s/k9kk51ko6r)

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |  0.12.13  |
| React                  |   16.2.0      |
| platform               |   iOS (10 or 11)      |
| etc                    |         |

**Comment by matviishyn** [comment]
found one similar issue (closed) https://github.com/oliviertassinari/react-swipeable-views/issues/257

**Comment by JennieJi** [comment]
Similar issue but can trigger with any nested overflow items with `-webkit-overflow-scrolling: touch`.

Tried react-swipeable-views: 0.12.12, 0.12.18, 0.13.0
Triggerable in iOS >= 10

**Comment by JennieJi** [comment]
BTW, this temporary solution works: https://github.com/oliviertassinari/react-swipeable-views/issues/408#issuecomment-421276447

**Comment by jeanpoelie** [comment]
The Answer is above :) Thank you Ephys!
