### ISSUE TITLE
Is it possible to scroll to the top of the view on swipe?

### ISSUE THREAD

**Issue by sanfilippopablo** [oliviertassinari/react-swipeable-views#424]
- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Swiping to a previously scrolled view should reset the scroll to top. Not by default, but after setting an option.

## Current Behavior
Swiping to a previously scrolled view keeps the scroll position.

## Steps to Reproduce (for bugs)
You can preview here: https://codesandbox.io/s/n50zkl1pn4

1. Scroll slide 1.
2. Swipe to slide2.
3. Swipe back to slide 1.

**Comment by anulalbs** [comment]
Yes possible 
On  <SwipeableViews onSwitching = { this.updateScrollBars}

and on updateScrollBars function write the code to scroll the div to the top

Hope this helps

**Comment by RosarioAleCali** [comment]
@anulalbs Do you have a working example. For some odd reason I can't get onSwitching to fire.

**Comment by petercutting** [comment]
yes, onSwitching is not firing for me either. I am trying to save the scroll postion of each view so that I can restore it when returning to a view. Any code example much appreciated

**Comment by stefanbinder** [comment]
Same here... could you somehow scroll to the top?
I tried workarounds with refs, window.scrollTo, and few more, but couldn't make it work.

**Comment by sanfilippopablo** [comment]
Here's a simple way to make it work:
https://codesandbox.io/s/create-react-app-1s230
