### ISSUE TITLE
Reproduce custom width demo in codesandbox 

### ISSUE THREAD

**Issue by Alphapage** [oliviertassinari/react-swipeable-views#427]
Hello,

I'm trying to reproduce the custom width demo in codesandbox, but I am unable to get slider 2 to be between slider 1 right portion and slider 3 left portion:
https://codesandbox.io/s/y2x56plokx

What I'm getting is only slider 1 right portion with slider 2. The demo is working as expected.

I'm lost with root style, container style and slider style.

Thank you in advance for your help.

For info, the demo example link doesn't work in codesandbox because SupportTouch dependency is missing.

**Comment by vicasas** [comment]
this problem still exists, any solution?
