### ISSUE TITLE
Add support for React 16.3

### ISSUE THREAD

**Issue by rolandjitsu** [oliviertassinari/react-swipeable-views#428]
- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

With React's 16.3 official release a few weeks ago, it would be nice if this library would migrate to the new API.

## Current Behavior

Some APIs have been deprecated, `componentWillReceiveProps` being one of them (which I noticed it is used by this lib).

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |         |
| React                  |         |
| platform               |         |
| etc                    |         |

**Comment by oliviertassinari** [comment]
I agree, we need to update the lifecycles!

**Comment by henrylearn2rock** [comment]
FYI 16.9 emits this warning

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: ReactSwipableView

**Comment by caleb-harrelson** [comment]
Workaround implemented in #616, release coming soon.
