### ISSUE TITLE
react-swipeable-views interacts badly with react-beautiful-dnd on touch devices

### ISSUE THREAD

**Issue by AndrewMorsillo** [oliviertassinari/react-swipeable-views#430]
It seems as if react-swipeable-views may be eating some events needed for react-beautiful-dnd to work correctly. Here is a codesandbox illustrating the issue. You must run the demo in chrome responsive mode to see the issue. 

https://codesandbox.io/embed/ryp0mkmkzq?codemirror=1

Also see the issue logged with react-beautiful-dnd
https://github.com/atlassian/react-beautiful-dnd/issues/463

**Comment by caleb-harrelson** [comment]
Looks like there are some workarounds in that react-beautiful-dnd ticket. Closing due to the workarounds and issue's age.
