### ISSUE TITLE
Demo not working with SupportTouch use

### ISSUE THREAD

**Issue by romainquellec** [oliviertassinari/react-swipeable-views#434]
On codesandbox, the demo used with SupportTouch are broken.

`import SupportTouch from 'docs/src/modules/components/SupportTouch';`

should be

`import SupportTouch from 'react-swipeable-views';`

**Comment by romainquellec** [comment]
Same with some other demos.

**Comment by oliviertassinari** [comment]
There is no exported `SupportTouch`, it's specific to the documentation.
