### ISSUE TITLE
Typescript support for Pagination

### ISSUE THREAD

**Issue by romainquellec** [oliviertassinari/react-swipeable-views#435]
I can't use Pagination with Typescript.
I guess Types are not maintained anymore.

You can reproduce the issue here : https://codesandbox.io/s/2pr545540n

**Comment by romainquellec** [comment]
@mxl @DeividasBakanas

**Comment by oliviertassinari** [comment]
@romainquellec Your imports are incorrect.

**Comment by cescoferraro** [comment]
@oliviertassinari what are the correct imports?
the docs reference a working example at the website but fails on this codesandbox `https://codesandbox.io/s/9280p6y50p`   

it fails tright here

> import Pagination from 'docs/src/modules/components/Pagination';
