### ISSUE TITLE
showing more than one slide when container is big

### ISSUE THREAD

**Issue by loox-** [oliviertassinari/react-swipeable-views#44]
Hello, thanks for your work: I found it very useful and well done.
I am trying to reproduce in RN the following: [http://i.imgur.com/Kmgat3C.png](http://i.imgur.com/Kmgat3C.png) 
Is there any way to put active slide on center and let other slides be shown on sides,up to container's limit?

**Comment by oliviertassinari** [comment]
Hi, thanks for the feedback.

Good question, this feature isn't implemented on RN neither on the browser.
I have never investigated this use case.

**Comment by oliviertassinari** [comment]
Actually, there is a way. At @doctolib, we are adding an extra padding and allowing the overflow so slides on the edges are displayed.
