### ISSUE TITLE
Threshold not working?

### ISSUE THREAD

**Issue by TiagoSousa26** [oliviertassinari/react-swipeable-views#447]
I am playing around with the threshold, for example, I put at 1000 or 1 but it allow me to swipe fast anyway. Someone can explain me better how this parameter work and for what is it?

To do the swipe, open the responsive mode, and set as touch.
https://codesandbox.io/s/kxl6rkzv83

**Comment by oliviertassinari** [comment]
> This is the threshold used for detecting a quick swipe. If the computed speed is above this value, the index change.

@TiagoSousa26 It's not about swiping fast, it about the inertie require to trigger a onChange event.

**Comment by TiagoSousa26** [comment]
But there is a way of not doing swipe fast?

**Comment by oliviertassinari** [comment]
>  not doing swipe fast?

What does it meant?

**Comment by TiagoSousa26** [comment]
Change fast between slides with swipe.

**Comment by TiagoSousa26** [comment]
For example, you swipe and it changes one slider, but you do this pretty fast. I do a video if necessary to explain better.

**Comment by oliviertassinari** [comment]
?

**Comment by TiagoSousa26** [comment]
Sorry, I was editing the comment to provide more information.

**Comment by oliviertassinari** [comment]
> There is a way of only switch one slider every 2 seconds for example or when the animation ends? Basically, disable the swipe for a specific time.

Yes, you control the component, you also have access to the transition end events. So you should be able to build this logic on userland. Feel free to share the result, that could help others.

**Comment by TiagoSousa26** [comment]
I tried to toggle the prop `disabled` to not be able to swipe after changing slide, but it takes more time than it was supposed. For example, I set 500 miliseconds of interval and it take like 2 seconds.
