### ISSUE TITLE
custom width style and responsiveness

### ISSUE THREAD

**Issue by varenya** [oliviertassinari/react-swipeable-views#450]
The current implementation doesn't allow for a custom width for slides to be given as it messes up the indexMax calculations which basically means the user will be able to swipe through even after the total items are finished. In the demo the root element padding is manipulated to get that effect but that would only work gracefully for 1-2 items more than that the UI becomes ungraceful and constrains the consumer on the way it can be used.

## Expected Behavior

When given a slideStyle object with a custom width the edge conditions should work as expected i.e. the user should not be allowed to swipe further than the total number of items.

## Current Behavior

User is able be allowed to swipe further than the end of items basically edge cases should be handled properly when giving custom width.

## Steps to Reproduce (for bugs)

1. pass a slideStyle object with a width property.
2. Try swiping through the items
3. User will be able to swipe through the items even after the items have finished.

## Context

I need to show more than one item in the given window so tried to set a custom width but in doing that the edge cases stopped working properly. The custom width option using paddings on the root doesn't fulfill my design specifications and needed a custom width control or an option to set the number of items in a given window.
Also, responsiveness is tough to achieve through CSS with the current implementation but I think if we allow for a custom width responsiveness should be achievable 
## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |   0.12.14      |
| React                  |       16.4.1  |

Should be straightforward to reproduce if not let me know i will provide a codesandbox, I might be missing something here so please do correct me if I am wrong :-)

**Comment by oliviertassinari** [comment]
> I need to show more than one item in the given window so tried to set a custom width but in doing that the edge cases stopped working properly.

It's not something we support. The closest example we have is: https://react-swipeable-views.com/demos/demos/#custom-width.

**Comment by varenya** [comment]
Are you open to a PR to implement this?

**Comment by varenya** [comment]
okay tried to implement it but ran into a bunch of edge cases with it let me explore a bit further if I can get it done will raise a PR and you can review it. Thanks for your time.

**Comment by oliviertassinari** [comment]
@varenya Sounds like a plan :)

**Comment by varenya** [comment]
one more thing @oliviertassinari did u try throttling the touch events seems like its getting triggered too often.

**Comment by oliviertassinari** [comment]
@varenya Do we don't. The touch-move handler should be fast enough not to harm the JavaScript main thread. As far as I understand the problem, if we have two touch-move event triggered between two screens pain, it won't matter because the handling logic is very fast.

**Comment by varenya** [comment]
yeah I didn't see any lag at all,  the code is really readable and well implemented 👍
