### ISSUE TITLE
FYI: Latest babel/runtime causes a problem

### ISSUE THREAD

**Issue by mortentz** [oliviertassinari/react-swipeable-views#451]
This is just a quick FYI: 

The latest version of @babel/runtime, 7.0.0-beta.56, causes a module not found due to the line: 
var _interopRequireDefault = require("@babel/runtime/helpers/builtin/interopRequireDefault");

I fixed it by manually installing and setting the version to 7.0.0-beta.42, which is what package.json of react-swipeable-views-core requires. 

Have a nice day, and thank you for an excellent component.

**Comment by Sw0rdstream** [comment]
Same problem for me as well. 

With regards, but personally think it a bad practice to upgrade babel in a revision update.
