### ISSUE TITLE
Update index via external component

### ISSUE THREAD

**Issue by KITSTABChrisGreen** [oliviertassinari/react-swipeable-views#456]
Hi Olivier, 

I'm trying to set the swipeable view to a specific index from an external component. As I'm utilising virtualize to enable a circular swipe-able view, I found its possible to access the 'setWindow' function using the following...

```
<VirtualizeSwipeableViews ref={swipeableView => {this.swipeableView = swipeableView}} />
```

... and setting the index using... 

```
this.swipeableView.setWindow(index)
```

Though this works, the index value is not persisted such that swiping the carousel continues from `this.state.index`.
 
**Possible Solution**

Looking in to the virtualize.js code, setWindow can accept an external variable (which defaults to this.state.index) as per ...

```
setWindow(index = this.state.index) {
    ...
}
```

However as you can see, `this.state.index` is not updated.  The simplest solution is to update the index when updating the indexContainer/indexStart/indexStop. 

```
setWindow(index = this.state.index) {
      const { slideCount } = this.props;

      let beforeAhead = this.props.overscanSlideBefore;
      let afterAhead = this.props.overscanSlideAfter;

      if (slideCount) {
        if (beforeAhead > index) {
          beforeAhead = index;
        }

        if (afterAhead + index > slideCount - 1) {
          afterAhead = slideCount - index - 1;
        }
      }

      this.setState({
        index,
        indexContainer: beforeAhead,
        indexStart: index - beforeAhead,
        indexStop: index + afterAhead,
      });
    }

```

I'm happy to create a branch and submit a PR.

- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |    ^0.12.8     |
| React                  |    ^16.2.0     |
| platform               |         |
| etc                    |         |

**Comment by oliviertassinari** [comment]
@KITSTABChrisGreen `setWindow`, as all the others imperative methods are a private API. Don't use them. In your case, you can control the `index` property.
