### ISSUE TITLE
Use custom index

### ISSUE THREAD

**Issue by Jordy-A** [oliviertassinari/react-swipeable-views#458]
Any chance to get a custom index working with react-swipeable-views and Material UI tabs? Right now, it only works with integer indexes. However, the Material UI supports custom indexes:

```
<Tabs value={ value }>
    <Tab value="custom_index" label='Tab Title' />
</Tabs>
```
This doesn't work with Swipeable Views because it needs integers. It would be great if something like this works:
```

<SwipeableViews index={ value }>
    <TabContainer for="custom_index" dir={ theme.direction }>
    </TabContainer>
</SwipeableViews>
```

**Comment by Jordy-A** [comment]
@oliviertassinari isn't this possible?

**Comment by oliviertassinari** [comment]
@Jordy-A Let's keep the codebase simple.
