### ISSUE TITLE
Feature request : Autoplay & Prev/Next

### ISSUE THREAD

**Issue by sylvainbaronnet** [oliviertassinari/react-swipeable-views#46]
Hello,

Adding the possibility to autoplay would be nice

Also, prev/next method.

That would make it a more complete solution

**Comment by oliviertassinari** [comment]
> Adding the possibility to autoplay would be nice

That would be nice. I think that we could create a HOC for this behavior :+1: 

> Also, prev/next method.

I don't agree with this feature. That seems imperative and not declarative.

**Comment by sylvainbaronnet** [comment]
for prev/next maybe just an example in the doc ?

**Comment by oliviertassinari** [comment]
That would be good yes.

**Comment by oliviertassinari** [comment]
@sylvainbaronnet I'm working on the auto play feature.

**Comment by oliviertassinari** [comment]
Fix with https://github.com/oliviertassinari/react-swipeable-views/commit/da4e20e292e7694a36452f4ad114dc46d4f8c255.

**Comment by sylvainbaronnet** [comment]
This is great ! Thank you 

I don't know if I miss something but (after upgrading) I just added `autoplay={true}` to my SwipeableViews component but there's no autoplay...

**Comment by oliviertassinari** [comment]
I should be providing a better example. The auto play is provided with a High Order Component.
For now, you can have a look at the [source code](https://github.com/oliviertassinari/react-swipeable-views/blob/9471147d2120cee471944ae9268545b9aa97641e/docs/src/Demo/Demo7.js#L6) of the Demo 7.

**Comment by sylvainbaronnet** [comment]
Thanks it works with code from Demo7
