### ISSUE TITLE
The containerStyle description on the api documentation seems to be erroneous

### ISSUE THREAD

**Issue by JulioPablo** [oliviertassinari/react-swipeable-views#463]
Hello, when going thru the API documentation I noticed the containerStyle description says 
"Whether or not the auto complete is animated as it is toggled."  instead of something like, "This is the inlined style that will be applied on the container component."

![image](https://user-images.githubusercontent.com/33587721/44970603-c9371280-af0f-11e8-8564-314df84961d0.png)

**Comment by oliviertassinari** [comment]
@JulioPablo Nice finding! Something went wrong in https://github.com/oliviertassinari/react-swipeable-views/commit/2eb528add3067e2e61e3786eac89fff7e48fd654. The correct wording is
> This is the inlined style that will be applied to each slide container.

Do you want to fix it :)?

**Comment by JulioPablo** [comment]
Sure! As soon as I'm able to I'll fix it.
