### ISSUE TITLE
Don't trigger Content-Security-Policy errors due to injecting styles

### ISSUE THREAD

**Issue by taion** [oliviertassinari/react-swipeable-views#465]
- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Pages using react-swipeable-views with locked-down `style-src` should not show Content-Security-Policy errors from using react-swipeable-views.

## Current Behavior
`injectStyle` tries to inject inline styling for old browsers. IE10 at least doesn't even support `style-src`, and it's likely the sufficiently old versions of Safari don't do so either.

## Steps to Reproduce (for bugs)
This shows up immediately when disabling inline CSS with Content-Security-Policy,

## Context
This is just a slight annoyance when using locked-down CSP for styling and using this library. I think the easiest fix (per the title) is to just try-catch the style injection.

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  | 0.12.13 |
| React                  | 16.4.0 |
| platform               | OS X |

**Comment by taion** [comment]
Okay, it turns out there's no actual exception here to catch. What do you think of adding some sort of function to disable the "style injection" behavior?

**Comment by oliviertassinari** [comment]
What do you think of removing this code? I think that it's time 🚀 
https://github.com/oliviertassinari/react-swipeable-views/blob/248fec18d3a8a947662fe59bc76be6d67d40f636/packages/react-swipeable-views/src/SwipeableViews.js#L25-L26

**Comment by taion** [comment]
I'd be all for it. It's not quite 2019 yet, though.

**Comment by oliviertassinari** [comment]
Plans are made to be changed :).
