### ISSUE TITLE
react-swipeable-views-native is not updated on npm

### ISSUE THREAD

**Issue by Faolain** [oliviertassinari/react-swipeable-views#468]
- [X] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected / Current Behavior
I did `yarn added react-swipeable-views-native` and encountered `"undefined is not an object (evaluating '_reactNative.View.proptypes.style')"` upon trying to import the module. Digging further I saw that the node module which was added was using the deprecated `View.proptypes.style` instead of `ViewPropTypes.style`. I opened up the repo to make a PR and saw these changes already exist on github which I believe means the npm package must be updated? I didn't include additional details since this seems relatively minor and not a bug per se but since I'm using React Native 0.57.0 I'm unable to install from npm which makes it quite difficult to develop further. 

Update 4 days ago on https://github.com/oliviertassinari/react-swipeable-views/tree/master/native/packages/react-swipeable-views-native

Last Updated 10 months ago
Link: https://www.npmjs.com/package/react-swipeable-views-native

**Comment by oliviertassinari** [comment]
Sure, I will do a release :).

**Comment by Faolain** [comment]
Thank you! @oliviertassinari , I assume this issue will close once you do?

**Comment by oliviertassinari** [comment]
I don't have the time needed to work on it. @digital-flowers Do you want to take the ownership of the native version?

**Comment by digital-flowers** [comment]
@oliviertassinari  sorry, the problem that I am very busy these days, if you want add me as a contributor and i can help when i have a time, what do you think ?

**Comment by oliviertassinari** [comment]
I have invited you as a contributor :)

**Comment by digital-flowers** [comment]
@oliviertassinari appreciated  :)

**Comment by yacut** [comment]
@oliviertassinari I kann contribute this project...

**Comment by oliviertassinari** [comment]
If someone wants to lead the effort with the native version of the library, I would be happy to give him the necessary admin rights to execute :).

**Comment by yacut** [comment]
@oliviertassinari give me the admin rights please. I will lead the native version.

**Comment by oliviertassinari** [comment]
@yacut Thank you, I have given you the admin right for https://www.npmjs.com/package/react-swipeable-views-native.

**Comment by geminiyellow** [comment]
👏  big news. thanks all. @yacut @oliviertassinari

**Comment by yacut** [comment]
Thank you @oliviertassinari
I will make a release this weekend.

**Comment by yacut** [comment]
I hope the issue can be closed. The new native version is published: https://www.npmjs.com/package/react-swipeable-views-native

**Comment by geminiyellow** [comment]
👍

**Comment by oliviertassinari** [comment]
@yacut Awesome, you did great :)
