### ISSUE TITLE
Material-UI Outlined Input Causes Virtualize Transition Issues

### ISSUE THREAD

**Issue by AdamClark2001** [oliviertassinari/react-swipeable-views#483]
When using the virtualize HOC, if there is a Material-UI outlined input variant in the slides then transitions will switch between not animating and doing a double animation.  The observable behavior is exactly the same as described in issue [445](https://github.com/oliviertassinari/react-swipeable-views/issues/445), however, this is now happening in Chrome/Firefox with a specific Material-UI component.

If the input is switched to a filled or default variant the transitions work great.  Based on testing versions, the problem was introduced with version 0.12.11.

- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Transition animations happen once when the index prop is changed regardless of the slide contents.

## Current Behavior
The first transition happens instantly.  The second transition initially animates correctly but then does a second animation from the opposite direction.  Subsequent transitions flip flop between these behaviors.

## Steps to Reproduce (for bugs)
https://codesandbox.io/s/rlnwmn8wlm 

1. Click "go to next" to observe instant transition.
2. Click "go to next to observe double transition.
3. Repeat.

## Context
Our app will consist of a workflow of forms where a user may transition to a different form to perform work and then return to their previous form.  We would like to use react-swipeable-views to achieve simple transitions between forms.  We specifically want to use the virtualize HOC to prevent any performance issues as it will be possible to be N forms deep in a process.

Currently, I am working around this by not using the virtualize HOC but only providing content to the last 2 slides.  This has the downside of having a number of empty slides sitting in the DOM.

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |  0.13.0 |
| React                  |  16.5.2 |
| platform               |  Chrome/Firefox  |
| material-ui           | 3.3.1 |

**Comment by caleb-harrelson** [comment]
Thanks for the codesandbox example. In playing with the example it looks like this is fixed with Material-UI >= 4.0.0 (and the requisite react / react-dom 16.8 that requires. Here's [an example with those versions](https://codesandbox.io/s/adoring-pike-5n6vq?file=/index.js) and react-swipeable-views on the latest version (though it works on the 0.13.0 in your example too).
