### ISSUE TITLE
Broken on React v15

### ISSUE THREAD

**Issue by Nase00** [oliviertassinari/react-swipeable-views#49]
React v15 has broken rendering of slides, as seen here:

![](http://i.imgur.com/nwFeehm.gif)

I took a stab at fixing it in #48, but I'm not sure if it's the cleanest fix. In any case, I hope it's of some help.

**Comment by juliengroch** [comment]
You know when this correction is available ?

**Comment by oliviertassinari** [comment]
I can release something for tomorow.

**Comment by juliengroch** [comment]
oh ! great reactivity. Thx :)

**Comment by oliviertassinari** [comment]
Fix with https://github.com/oliviertassinari/react-swipeable-views/commit/8977ecf0c3254f20e11e9144704d466a3ebfbc38.
