### ISSUE TITLE
Support for Preact?

### ISSUE THREAD

**Issue by aibrahim3546** [oliviertassinari/react-swipeable-views#491]
Is `react-swipeable-views` supports **preact**?

I am trying to apply `react-swipeable-views` to my project. But I keep hitting this error:

<img width="983" alt="screen shot 2018-11-23 at 3 39 32 pm" src="https://user-images.githubusercontent.com/31366174/48932292-08389b00-ef36-11e8-91a9-c3a355831a4a.png">

**Comment by oliviertassinari** [comment]
@aibrahim3546 No clue. Your warning is coming from the React codebase. Please provide a minimal reproduction. It will help people to help you.

**Comment by aibrahim3546** [comment]
The problem was solved.

To solve this problem I had to install these two packages and the problem was solved:

`npm install --save-dev preact-compat/react preact-compat/react-dom`

I found the solution at here [#459](https://github.com/developit/preact-compat/issues/459)

Thank you for replying @oliviertassinari

**Comment by oliviertassinari** [comment]
Great, so we do support preact :)
