### ISSUE TITLE
Callbacks are not working

### ISSUE THREAD

**Issue by munkk** [oliviertassinari/react-swipeable-views#493]
Hello. Please can you explain how to use callbacks such as onChangeIndex, onSwitching etc. Right now they are not working if set index programmatically.  Thanks a lot.
https://codesandbox.io/s/3yx337p1op

**Comment by oliviertassinari** [comment]
@munkk These callbacks aren't called when you are controlling the component. It would create an infinite loop.

**Comment by RosarioAleCali** [comment]
@oliviertassinari So, when are those callbacks called?

**Comment by oliviertassinari** [comment]
@RosarioAleCali When the user interacts.
