### ISSUE TITLE
onChangeIndex/on should pass transitioned parent/child element

### ISSUE THREAD

**Issue by rwlaschin** [oliviertassinari/react-swipeable-views#495]
When attempting genericise the Swiper handers by having multiple swipers handled by a single callback, data is missing from the callback, namely either the parent or child element.

- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

When setting up a dialog with multiple swipers, using a single callback facilitates a data driven design.  This eliminates the need for extra function binding, special casing, function binding, or wrapper functions.

I would like to see a new parameter, dataKey
* dataKey - is a string identifier that is passed back in the callback

When the callbacks onChangeIndex and onSwitching are called I would like the child or the parent to be passed through.  The element passed through needs to have certain attributes applied to use as lookup keys/values -- is this normally done through inputProps?

## Current Behavior

Not a bug.

## Steps to Reproduce (for bugs)

Here's an example of how it can work
https://codesandbox.io/s/5w39jj6ly4

## Context

Without this enhancement clutter becomes an issue.  Handlers would need to be created that are almost identical, wrappers to pass to common handlers, or functions would need to be changed to bind additional information into the callback.  

This can lead to bugs and maintenance issues in a complex production application.

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |    0.12.18    |
| React                  |     16.6.3    |
| platform               |     Browser    |
| etc                    |    See Code Pen     |

Here's suggested changes, this may not work with how your design is currently
1. Add dataKey, asEvent props
1. Passes Event Objects like other handlers -- increases consistency
1. Sets Event Target to child that is being transitioned to
1. Applies dataKey to  target
1. Addes next and prevIndex

[Report.patch.txt](https://github.com/oliviertassinari/react-swipeable-views/files/2719702/Report.patch.txt)

Example of how to use it
[index.js.txt](https://github.com/oliviertassinari/react-swipeable-views/files/2719685/index.js.txt)

Currently, the changes are non-breaking but would require migration.

Let me know how you'd like to see this modified and I can make the appropriate changes.

**Comment by caleb-harrelson** [comment]
This is a big enough change to the API that I don't think it will be done with the project's current lack of a dedicated maintainer.
