### ISSUE TITLE
Install package on react@0.13.3 ?

### ISSUE THREAD

**Issue by miguel-ra** [oliviertassinari/react-swipeable-views#5]
I have a project with other packages and can not update react to 0.14.0.

Its posible install the package on react@0.13.3 ?

Thanks

**Comment by miguel-ra** [comment]
I get this message on console when i run sudo npm install react-swipeable-views --save

├── UNMET PEER DEPENDENCY react@0.13.3
├── UNMET PEER DEPENDENCY react-addons-pure-render-mixin@^0.14.0
├── UNMET PEER DEPENDENCY react-dom@^0.14.0
├── UNMET PEER DEPENDENCY react-motion@^0.3.0
└─┬ react-swipeable-views@0.3.0 
  └── object-assign@4.0.1 

npm WARN EPEERINVALID react-swipeable-views@0.3.0 requires a peer of react@^0.14.0 but none was installed.
npm WARN EPEERINVALID react-swipeable-views@0.3.0 requires a peer of react-addons-pure-render-mixin@^0.14.0 but none was installed.
npm WARN EPEERINVALID react-swipeable-views@0.3.0 requires a peer of react-dom@^0.14.0 but none was installed.
npm WARN EPEERINVALID react-swipeable-views@0.3.0 requires a peer of react-motion@^0.3.0 but none was installed.
npm WARN EPACKAGEJSON .temp No description
npm WARN EPACKAGEJSON .temp No repository field.
npm WARN EPACKAGEJSON .temp No license field.

**Comment by oliviertassinari** [comment]
Yes you can, the latest version (react-swipeable-views@0.3.0) drop the support of react v0.13.x. You need to use an older version

**Comment by miguel-ra** [comment]
Thanks for the answer.

sudo npm install --save react-swipeable-views@0.2.3
When i try to install de 2.3 version i get this other message :S 

├── UNMET PEER DEPENDENCY react-motion@^0.3.0
└─┬ react-swipeable-views@0.2.3 
  └── object-assign@4.0.1 

npm WARN EPEERINVALID react-swipeable-views@0.2.3 requires a peer of react-motion@^0.3.0 but none was installed.
npm WARN EPACKAGEJSON .temp No description
npm WARN EPACKAGEJSON .temp No repository field.
npm WARN EPACKAGEJSON .temp No license field.

How can i solve it?

**Comment by miguel-ra** [comment]
Solved.

After install the old version i will needed install react-motion dependency
