### ISSUE TITLE
Getting an error, while using this as a separate component.

### ISSUE THREAD

**Issue by tushartuteja** [oliviertassinari/react-swipeable-views#50]
VM7787 bundle.js:1105 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Tabs`.

my code is the following
`import React from 'react';
import SwipeableViews from 'react-swipeable-views';

var MyComponent = React.createClass({
	render: function(){return (
  <SwipeableViews>
    <div style={Object.assign({}, styles.slide, styles.slide1)}>
      slide n°1
    </div>
    <div style={Object.assign({}, styles.slide, styles.slide2)}>
      slide n°2
    </div>
    <div style={Object.assign({}, styles.slide, styles.slide3)}>
      slide n°3
    </div>
  </SwipeableViews>
);}});

var styles = {
  slide: {
    padding: 15,
    minHeight: 100,
    color: '#fff',
  },
  slide1: {
    background: '#FEA900',
  },
  slide2: {
    background: '#B3DC4A',
  },
  slide3: {
    background: '#6AC0FF',
  },
};

export default MyComponent;
`

**Comment by tushartuteja** [comment]
getting another error 
bundle.js:7644 Uncaught TypeError: Cannot read property '_currentElement' of null

first time I get the error mentioned in the above comment and then the above mentioned error.

**Comment by oliviertassinari** [comment]
@tushartuteja What version of this package are you using. Could this be an issue with the `Tabs` component instead of this one?

**Comment by tushartuteja** [comment]
0.5.1

**Comment by LunarSweeper** [comment]
I'm using 0.5.3 and have the same problem. I'm importing react-swipeable-views in NodeJS env with require:

var SwipeableViews = require('react-swipeable-views');

The content of SwipeableViews:

Object {__esModule: true}
  __esModule: true
  default: SwipeableViews(props)
  __proto__: Object

I guess the component should export function SwipeableViews(props) and not the object.

**Comment by oliviertassinari** [comment]
@LunarSweeper Babel is adding an extra layer to support ES6 modules. You need to use this in a ES5 environment. 
```js
var SwipeableViews = require('react-swipeable-views').default;
```

**Comment by LunarSweeper** [comment]
Yep, thanks. Works like a charm.

**Comment by oliviertassinari** [comment]
I'm closing this issue. I would need more detail. That doesn't seem to be directly linked to this repository.
