### ISSUE TITLE
autoPlay, pass prop to ref child component

### ISSUE THREAD

**Issue by minhna** [oliviertassinari/react-swipeable-views#501]
I use `autoPlay` with react-swipeable-views, I need to access `swipable-view` component to call `updateHeight` function.
Currently I have no idea how to do it.
Thank you very much.

**Comment by oliviertassinari** [comment]
@minhna The properties should be forwarded. Have you tried providing an `action` property?

**Comment by minhna** [comment]
It works by adding this:
```
action={(actions) => { this.swipableViewsActions = actions; }}
```
I don't have to use `ref` anymore. Thank you.
