### ISSUE TITLE
Are the demo examples broken ?

### ISSUE THREAD

**Issue by Minishlink** [oliviertassinari/react-swipeable-views#502]
- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

On the [component demos](https://react-swipeable-views.com/demos/demos/) page, one should be able to swipe in all the swipeable examples.

## Current Behavior

On the [component demos](https://react-swipeable-views.com/demos/demos/) page, the first example works great, I can swipe between slides easily. But on every other components, I can't swipe.

## Steps to Reproduce (for bugs)

1. Go to [component demos](https://react-swipeable-views.com/demos/demos/)
2. Scroll down to the resistance, coverflow, circular, virtualize example (and maybe others)
3. Try to swipe

## Your Environment

- Chrome 72
- Firefox 65
- Safari 12.0.3
- macOS 10.14

**Comment by oliviertassinari** [comment]
@Minishlink We don't support desktop mouse event by default. Only the first demo has this capability enabled.

**Comment by Minishlink** [comment]
Thanks @oliviertassinari ! I sent a PR to update the doc, to mention this :)
