### ISSUE TITLE
animate tab underline on swipe

### ISSUE THREAD

**Issue by mikestaub** [oliviertassinari/react-swipeable-views#504]
- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
While swiping between tabs, the underline should animate along with the container content. ( like on android mobile twitter app )

## Current Behavior
This feature is not supported. I think it will provide a better UX.

**Comment by oliviertassinari** [comment]
@mikestaub We have a `onSwitching` prop for this use case.

**Comment by mikestaub** [comment]
Do you think updating the css value via js will be performant?

**Comment by oliviertassinari** [comment]
@mikestaub It might do it yes.

**Comment by siriwatknp** [comment]
Here is a workaround, if you want to have that UX.
@oliviertassinari Please confirm that this won't cause performance issue, thanks.

https://codesandbox.io/s/swipeable-tabs-ux-improved-53ymk

**Comment by mikestaub** [comment]
This works great for me on mobile, I think this should live in this repo and be enabled by default.

Or at the very least, @siriwatknp's example should be in the docs.

**Comment by caleb-harrelson** [comment]
@mikestaub or @siriwatknp, you can make a PR for the new demo if you'd like. Otherwise I think this is a fine example in the issues. Closing for now.
