### ISSUE TITLE
iPhone 6 Plus safari issue

### ISSUE THREAD

**Issue by Antonov1Denis** [oliviertassinari/react-swipeable-views#505]
Strange slide behavior.
Sometimes the slide is not fully visible or not showing as you can see on screenshots and video.
Only occurs in **safari** on **iPhone 6 Plus** Software Version **12.2**

![IMG_0649_](https://user-images.githubusercontent.com/39348642/55959806-2ea46c00-5c74-11e9-8c4c-41e23549c1f3.PNG)
![IMG_0647_](https://user-images.githubusercontent.com/39348642/55959983-922e9980-5c74-11e9-9881-802821c9a55a.PNG)
![IMG_0650_](https://user-images.githubusercontent.com/39348642/55960060-af636800-5c74-11e9-8ed7-d88aafc1b99d.PNG)
![IMG_0652_](https://user-images.githubusercontent.com/39348642/55960081-bb4f2a00-5c74-11e9-9e5d-285518c70cdc.PNG)

You can see behaviour on video:
https://www.youtube.com/watch?v=pdzxT8cy1Vk

**Comment by ammoradi** [comment]
any news?

**Comment by Antonov1Denis** [comment]
@ammoradi Unfortunately no...

**Comment by caleb-harrelson** [comment]
The iPhone 6 Plus is no longer receiving OS updates from Apple either, so this is unlikely to be addressed without a PR from somebody that can fix and test it.
