### ISSUE TITLE
Autoplay is fast forwarding when switching back to browser tab

### ISSUE THREAD

**Issue by leMaik** [oliviertassinari/react-swipeable-views#508]
When a swipeable view with autoplay is shown and the user hides that tab and comes back to it later, the swipeable view "fast forwards" and eventually slows down to normal speed.

Maybe this is related to Chrome somehow "batching" `setInterval` calls while a tab is hidden? :thinking: 

- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
The autoPlay swipeable view switches exactly every interval milliseconds in all cases but _does not_ switch if the tab is not visible or at least it doesn't fast-forward later.

## Current Behavior
When the slides are visible again, they "fast forward" and slow down to normal speed eventually.

## Steps to Reproduce (for bugs)
1. Open a page in a tab with an autoPlay swipeable view, e.g. https://codesandbox.io/s/6ykr1vqo43
2. Switch to a different tab, grab a :coffee: or wait for about 10 seconds
3. Re-open the tab and see how the slides change very quickly at first (the more slides the more visible this issue becomes).

## Context
See https://github.com/TeamWertarbyte/material-auto-rotating-carousel/issues/51

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |  0.13.1  |
| React                  | 16.5.2        |
| Platform               | Chrome 74 |
| etc                    |         |

**Comment by oliviertassinari** [comment]
@leMaik Thanks for the bug report. We could pause the interval when the window loses the focus and resume when the focus is restored. We do the same with the Material-UI's snackbar component.

**Comment by leMaik** [comment]
@oliviertassinari Allright, I'm preparing a PR. I better approach would be to use the [Page Visibility API](https://developer.mozilla.org/de/docs/Web/API/Page_Visibility_API) is available, because an onfocused window might still be visible? :thinking:

**Comment by oliviertassinari** [comment]
The visibility API looks better suited, yes.

**Comment by leMaik** [comment]
It's widely supported too and does exactly what I need. https://caniuse.com/#feat=pagevisibility

> Hum shouldn't we pause the animation when the window is visible but not focused? thinking
No. Why should a carousel stop just because I focus a different window (but leave the browser open on my other screen)? :wink:

**Comment by oliviertassinari** [comment]
> Why should a carousel stop just because I focus a different window

Would it create visual distraction away from where the user attention is?

**Comment by leMaik** [comment]
I guarantee you users will raise a new issue if we now start stopping the animation when users onfocus the window. That's like stopping playback of YouTube videos when you unfocus the browser window.

**Comment by oliviertassinari** [comment]
I have played around with:
```js
window.addEventListener('focus', () => console.log('window.focus'));
window.addEventListener('blur', () => console.log('window.blur'));
window.addEventListener('visibilitychange', () => console.log('document.visibilityState', document.visibilityState));
```

I'm happy with the visibility event after more thoughts. Now, I don't think that we should the snackbar focus/blur logic.

**Comment by leMaik** [comment]
> (But, I don't think that we should change the snackbar focus/blur logic).

Agree :+1:
