### ISSUE TITLE
Error use makeStyles from @material-ui/styles for containerStyle

### ISSUE THREAD

**Issue by gespispace** [oliviertassinari/react-swipeable-views#515]
- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

My styles should set.
## Current Behavior

Crash dom react.

## Steps to Reproduce (for bugs)

https://codesandbox.io/s/material-demo-j72tj

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |   0.13.3  |
| React                  |16.8.6|
| platform               | xubuntu |
| etc                    |         |

**Comment by oliviertassinari** [comment]
containerStyle doesn't accept a classname.

**Comment by gespispace** [comment]
Why is that? maybe the should accept classname?

**Comment by oliviertassinari** [comment]
It accepts an inline-style object. You can potentially target the `react-swipeable-view-container` global class name.

**Comment by gespispace** [comment]
Ok, it is sad :( 
thank you
