### ISSUE TITLE
container className

### ISSUE THREAD

**Issue by PeterKottas** [oliviertassinari/react-swipeable-views#525]
- [ ] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |         |
| React                  |         |
| platform               |         |
| etc                    |         |

**Comment by PeterKottas** [comment]
Sorry, @oliviertassinari opened the issue by mistake before it was finished. This can be reopened now.

**Comment by PeterKottas** [comment]
My bad, it's implemented but called className and it's only mentioned after the api reference on https://react-swipeable-views.com/api/api/. What threw me off is that style for the container is called containerStyle but class for the container is just className. Little inconsistency never killed anybody I guess. Maybe something to look into but considering it would be a breaking change, I doubt this would be worth it.

**Comment by oliviertassinari** [comment]
@PeterKottas We don't expose this API because we need to inspect the styles of containerStyles.
