### ISSUE TITLE
core-js version ancient

### ISSUE THREAD

**Issue by mschipperheyn** [oliviertassinari/react-swipeable-views#532]
I'm having some issues using core-js on a monorepo  bc some library use outdated ones.
`yarn why core-js`
```
=> Found "react-swipeable-views-utils#core-js@1.2.7"
info Reasons this module exists
   - "_project_#social#react-swipeable-views#react-swipeable-views-utils#fbjs" depends on it

```

- [x ] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
core-js should currently be 3.1.4

## Current Behavior
This prob is caused by fbjs which is not well maintained in this respect. There are some open issues there on this topic, but perhaps it should not be used at all.

## Steps to Reproduce (for bugs)
`yarn why core-js`

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |      0.13.3   |
| React                  |      16.8   |
| platform               |  mac       |

**Comment by oliviertassinari** [comment]
@mschipperheyn I think that we should be able to loosen the dependency range here. We should also be able to update all the dependencies. I have zero interest in investing time in this project. As you can see in the history of activity, I have abandoned the project a year ago. If you want to work on it, then sure, why not. I will be happy to merge and release a green pull request :).

**Comment by mschipperheyn** [comment]
ah ok. I thought this project was active. Didn't realize.

**Comment by oliviertassinari** [comment]
@mschipperheyn It's still active. But not from me.
