### ISSUE TITLE
How can I use the autoPlay property?

### ISSUE THREAD

**Issue by jogunism** [oliviertassinari/react-swipeable-views#54]
Plz help anyone?
thank you.

**Comment by oliviertassinari** [comment]
Have a look https://github.com/oliviertassinari/react-swipeable-views/issues/46#issuecomment-210997639.

**Comment by KevinHu2014** [comment]
How about Native?

**Comment by oliviertassinari** [comment]
@KevinHu2014 that's exactly the same. This HoC is logic pure and do no depend on react-dom nor react-native. I'm gonna improve the doc.
