### ISSUE TITLE
Upgrade `dom-helpers` to prevent duplicate packages

### ISSUE THREAD

**Issue by wallzero** [oliviertassinari/react-swipeable-views#542]
- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

When building with `@material-ui` I receive a duplicate packages error for `dom-helpers`. Attempting to resolve to the latest `dom-helpers@5.1.0` breaks `react-swipeable-views` which relies on `dom-helpers@3.4.0`.

## Steps to Reproduce (for bugs)

1. Install latest `react-swipeable-views`
2. Build with `webpack` and `duplicate-package-checker-webpack-plugin`

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  | 0.13.3 |
| React                  | 16.8.6 |

**Comment by tlandn** [comment]
I also have this error, using with MaterialUI v4 cause error in "dom-helpers"

**Comment by witek** [comment]
For me `react-swipeable-views` does not work with `shadow-cljs` because of this issue.

**Comment by firstpersoncode** [comment]
is this fixed already ?

**Comment by jeanpoelie** [comment]
This should now be fixed with PR #556

**Comment by gr8back** [comment]
Still had the problem, maybe a conflict with @material-core or icons, downgrading react-swipeable-views to 0.12.8 or so, did the trick and installed old dom-helpers.

**Comment by mikkopori** [comment]
Same here, downgrading to 0.12.8 helped solve the issue for now.

**Comment by jeanpoelie** [comment]
> Same here, downgrading to 0.12.8 helped solve the issue for now.

You should be able to install the latest without issue

**Comment by mikkopori** [comment]
That is true, thank you, works now!
