### ISSUE TITLE
'Top level' Slides in a sub component

### ISSUE THREAD

**Issue by mrmadhat** [oliviertassinari/react-swipeable-views#549]
I'm creating a multi-step form with react-swipeable-views, on slide 3 the user can make a choice that should affect the rest of the questions asked/slides shown.

```
Slide 1
Slide 2
Slide 3
  if user selected project type = "design"
     Slide 4
     Slide 5
     Slide 6
  else
     Slide 4a
     Slide 5a
     Slide 6a
```

I would like slides 4, 5, 6 or 4a, 5a, 6a (sub-slides) to be considered 'top-level' slides however I would like to wrap sub-slides in a component in order to improve readability.

The problem is that slide 1,2,3 work and a transition to slide 4 happens but slide 5 is displayed below it.

- [x ] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

I would like to be able to transition from slide 4 to slide 5 as if it were in the same component as slides 1,2,3

## Steps to Reproduce (for bugs)

Slide through the slides on this example:

https://codesandbox.io/embed/create-react-app-5h8xi

**Comment by philippklodt** [comment]
I don't believe this is a bug, you are passing the entire subcomponent as 4th child so the library cannot really know what to consider swipeable elements in this case.

That said, I think you can achieve what you want by using another nested `SwipeableView` in your SubSlides component, the library handles this kind of nesting quite well.

I updated your example accordingly:
https://codesandbox.io/s/create-react-app-qgz8k

**Comment by mrmadhat** [comment]
Thanks @philippklodt I did achieve what I wanted with a nested view, the reason why I didn't want to do this initially was because it created an issue with a global back button I had but I did some work and managed to get it all sorted
