### ISSUE TITLE
Height not updating when wrapping an animation component to a tab

### ISSUE THREAD

**Issue by Kexin-Li** [oliviertassinari/react-swipeable-views#557]
- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

the height of each tab should automatically be updated by its content.

## Current Behavior

When the slide's content changed, the height of the slide didn't update.

## Steps to Reproduce (for bugs)

https://codesandbox.io/s/material-demo-8wx4i

1. Switch to tab two.
2. Click the expand button, see how height changes.

## Context

I have two slides with different height. In one slide, I have a toggle, when I trigger a toggle, it will show more content in this slide. While I have a `Fade` component, it wrapped the content which triggered to show.

I used `animateHeight ` props, and called `slideUpdateHeight()/updateHeight()` method in `componentDidUpdate` method, but is not working.

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |    0.13.3     |
| React                  |    16.8.6     |
| platform               |     macOS    |

**Comment by jeanpoelie** [comment]
Hi,

This could be the solution for you but someone needs to fix the conflicts, i might have time for this next week.

https://github.com/oliviertassinari/react-swipeable-views/pull/537

**Comment by caleb-harrelson** [comment]
The example you posted seems to work now. I added `enableMouseEvents` to [test it in browser](https://codesandbox.io/s/material-demo-forked-zunlm?file=/demo.js) and the content expands and collapses as expected. Do you still see this as an issue?
