### ISSUE TITLE
Which method will be called when click other tab

### ISSUE THREAD

**Issue by Joycewu31400** [oliviertassinari/react-swipeable-views#559]
![image](https://user-images.githubusercontent.com/7145051/69479782-39df8d00-0e3c-11ea-8e37-e389814a52db.png)
when i swipe "readme" to "6 Dependencies " 
![image](https://user-images.githubusercontent.com/7145051/69479830-ba05f280-0e3c-11ea-8589-146633337f7c.png)
![image](https://user-images.githubusercontent.com/7145051/69479831-bf633d00-0e3c-11ea-8646-590588821e52.png)

which method will be called from 1.1-1.4 and 2.1-2.4

**Comment by jeanpoelie** [comment]
I believe you are better of asking this is the react github because this seems to be a react related issue not specificly for a the swipeable views library.
