### ISSUE TITLE
issue with parameters passed by onChangeIndex

### ISSUE THREAD

**Issue by funkyeah** [oliviertassinari/react-swipeable-views#56]
The API docs for `onChangeIndex` show it is called with `function(index, fromIndex)` but it doesn't seem to work properly for me. I am a bit of a noob so maybe I'm not understanding it but I did dig through the code to try to figure it out. Here's what I see:

`this.props.onChangeIndex()` is called in a number of different files but sometimes it is called with one parameter `this.props.onChangeIndex(indexNew);` and other times with two `this.props.onChangeIndex(indexNew, indexLatest);` . Am I correct in asserting the API will not always pass the `fromIndex` parameter? If so, is this maybe a bug because shouldn't onChangeIndex only fire when the index changes from something to something else?

Also I don't think those two parameters have the correct meaning when passed anyway.
In the `handleTouchEnd` function of both the [index.native.antimated](https://github.com/oliviertassinari/react-swipeable-views/blob/1a9b8810ce07abbd29f150a7cc2cc36587435352/src/index.native.animated.js#L178) and [SwipeableViews.js](https://github.com/oliviertassinari/react-swipeable-views/blob/master/src/SwipeableViews.js#L201) you have the variables:

`indexNew`, `indexCurrent`, and `indexLatest`

`indexNew` gets assigned

```
    if (Math.abs(this.vx) > this.props.threshold) {
      if (this.vx > 0) {
        indexNew = Math.floor(this.state.indexCurrent);
      } else {
        indexNew = Math.ceil(this.state.indexCurrent);
      }
    } else {
      // Some hysteresis with indexStart
      if (Math.abs(this.indexStart - this.state.indexCurrent) > 0.6) {
        indexNew = Math.round(this.state.indexCurrent);
      } else {
        indexNew = this.indexStart;
      }
    }
```

 then sometime later [this.setState](https://github.com/oliviertassinari/react-swipeable-views/blob/master/src/SwipeableViews.js#L242) is used to give `indexCurrent` and `indexLatest` the value of `indexNew` 

```
    this.setState({
      indexCurrent: indexNew,
      indexLatest: indexNew,
      isDragging: false,
    },
```
and just a couple lines later in the setState callback `indexNew` is checked to see if it matches `indexLatest`

```
, () => {
      if (this.props.onSwitching) {
        this.props.onSwitching(indexNew, 'end');
      }

      if (this.props.onChangeIndex && indexNew !== indexLatest) {
        this.props.onChangeIndex(indexNew, indexLatest);
      }
    });

```

but how would they ever not be the same?

There is a good chance I just don't understand something about React or ES6 correctly.

**Comment by oliviertassinari** [comment]
@funkyeah You are right, the API isn't consistent. Can you have a look at https://github.com/oliviertassinari/react-swipeable-views/pull/58? It should improve this.

**Comment by funkyeah** [comment]
It looks like it should work to me. I'll be happy to give it a test when you want.

The only thing that looked a little fishy to me is the use of `this.state.indexCurrent` which often appears to be a duplication of `this.state.indexLatest` in https://github.com/oliviertassinari/react-swipeable-views/blob/standardize-onChangeIndex/src/SwipeableViews.js#L245

Although that is not always the case in other files. I guess it's just a little hard to understand what they are supposed to mean at all times... but probably still functioning correctly.

**Comment by oliviertassinari** [comment]
Well `indexStart` and `indexCurrent` are used for different purposes.
- `indexStart` is for adding some hysteresis.
- `indexCurrent` is for reflecting the swipe position at the next render.

**Comment by oliviertassinari** [comment]
You raised some good points. I could have added some comment to be more explicit. Are even better test them.

**Comment by funkyeah** [comment]
I wouldn't go that for. I would say my points are OK at best. I'm more just pointer to things that are hard for me to understand, which only means that they are hard for a total beginner to understand, not that anything is necessarily wrong.

Anyhoo, thanks for doing this project. I'm trying to use it in a react native app to setup gmail like swipe row items... basically the swipe to archive feature but instead swipe to mark as done. So the event API is what I'm depending on.
