### ISSUE TITLE
Could not find module in path: 'dom-helpers/transition/properties' 

### ISSUE THREAD

**Issue by repl-sean-heintz** [oliviertassinari/react-swipeable-views#564]
- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Clean installation of `react-swipeable-views` can be used with the example from the README.

## Current Behavior

```
ModuleNotFoundError
Could not find module in path: 'dom-helpers/transition/properties' relative to '/node_modules/react-swipeable-views/lib/SwipeableViews.js'
```

Seems to have been introduced by https://github.com/oliviertassinari/react-swipeable-views/pull/556

## Steps to Reproduce (for bugs)

https://codesandbox.io/s/dreamy-euler-xifo5

## Context

We had to lock our version of `react-swipeable-views` to a previous version to fix our build.

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  | 0.13.4 |
| React                  | 16.12.0|

**Comment by jeanpoelie** [comment]
Hi,

Thank you for your report, i will try to take a look at this tomorrow morning.
We just created a release for version 0.13.4 but have unfortunatly not gotten around to testing it due to personal obstructions.

I will let you know when we fixed the issue

**Comment by repl-sean-heintz** [comment]
@jeanpoelie I've opened a PR which addresses the issue, please take a look when you've got time. Cheers!

**Comment by jeanpoelie** [comment]
I have checked and merged the PR, i will need to do a new release but have some issues due to me being on a windows pc and not having the option to use rm which is only available on mac

**Comment by raduchiriac** [comment]
This issue still persist on `0.13.6`. Anyone else?

**Comment by jeanpoelie** [comment]
I have reopened it, i will be rolling back 2 PRs they seem to cause this issue

**Comment by yanickrochon** [comment]
No idea why this was closed. I just updated and got this error.

**Comment by oliviertassinari** [comment]
Are you using the latest release?

**Comment by yanickrochon** [comment]
@oliviertassinari  if you mean by "latest release" to install via "yarn add react-swipeable-views@0.13.8" then, yes, I tried the latest release. Going back to 0.13.4 did not help either, so I finally reinstalled 0.13.3 and it worked again.

In other words, I can't upgrade this module because it breaks my app otherwise.

**Comment by oliviertassinari** [comment]
@yanickrochon Something is off in your env, proof: https://codesandbox.io/s/x8x11zjmp.

**Comment by yanickrochon** [comment]
Well, since it works with 0.13.3, and not with any other, what did change?

**Comment by oliviertassinari** [comment]
@yanickrochon Hopefully it will work for your project in the next release :).
