### ISSUE TITLE
Question: When the 1.3.5 version will be available in npm?

### ISSUE THREAD

**Issue by KVtofan** [oliviertassinari/react-swipeable-views#572]
I saw the 1.3.5 version in Master branch and they contain warning fix (WillReceiveProps). But the latest version on npm is 1.3.4.

When will the latest version be available?

**Comment by jeanpoelie** [comment]
Hi,

I have just released 1.3.5, I have been running into some issues with releasing since it is my first time contributing and I was running from a windows machine with mac commands.
This release should be more-stable, please report back if you have any issues
