### ISSUE TITLE
does not work on latest react 16.12

### ISSUE THREAD

**Issue by zsolt-dev** [oliviertassinari/react-swipeable-views#573]
First, I would like to thank you for this great library 

- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
to work

## Current Behavior
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

## Steps to Reproduce (for bugs)
1. open https://codesandbox.io/s/material-demo-yrug3
2. does not work. 

It is not a codesandbox issue, I have checked codesandbox only after 30 minutes of debugging on my local development computer.

**Comment by phoqe** [comment]
I get the same result, using version 0.13.5 on macOS Catalina 10.15.2 with React 16.12.0.

**Comment by masives** [comment]
Same here on react 16.10.2, changing to 0.13.3 fixes the issue. Linux mint 19 Cinnamon

**Comment by kodermax** [comment]
I got the same.

**Comment by domhabersack** [comment]
If it breaks for you with the latest version, set the version number of all three required packages to the same version, no greater than 0.13.3:

```
"dependencies": {
  "react-swipeable-views": "0.13.3",
  "react-swipeable-views-core": "0.13.3",
  "react-swipeable-views-utils": "0.13.3"
}
```

Core and utils were installed at 0.13.5 for us if we didn’t set them explicitly, which made the plugin break.
