### ISSUE TITLE
0.13.5 has an error

### ISSUE THREAD

**Issue by kodermax** [oliviertassinari/react-swipeable-views#574]
![image](https://user-images.githubusercontent.com/590985/72812402-7ed44400-3c72-11ea-938e-1eefdebd9464.png)

**Comment by aaronwlee** [comment]
same so dumb, I've got these errors...

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.


https://github.com/facebook/react/issues/13445

**Comment by kodermax** [comment]
And the build process of this package doesn't work too
![image](https://user-images.githubusercontent.com/590985/72814056-77626a00-3c75-11ea-8b98-e87db55fde3f.png)

**Comment by adonig** [comment]
Looks like we have to continue using 0.13.3 until hopefully 0.13.6 fixes all those recent issues 😢

**Comment by kodermax** [comment]
Agree

**Comment by allicanseenow** [comment]
Can someone from the maintenance team make a confirmation on whether this bug exists? I am personally facing this issue right now with React 16.12

**Comment by zarezadeh** [comment]
I looked at react-swipeable-views-utils@0.3.5 package, and I realized the package in not built and contains only `src` folders and not `lib` folder. I think there's a problem occurred when building and publishing this version into npm registry

**Comment by jeanpoelie** [comment]
Hi,

Very sorry for the issues with the last couple releases.
I had not released anything using lerna before and am running into some odd bugs which occur during the build and publish.
It seems like something has broke the build pipeline, but the errors i am receiving say '=' is not an existing character.

Today i will try a different path building with a windows linux machine

**Comment by zhukov-it** [comment]
kek

**Comment by raduchiriac** [comment]
> Looks like we have to continue using 0.13.3 until hopefully 0.13.6 fixes all those recent issues 😢

I updated to 0.13.5 without reading the issues here. 

0.13.3 used to work. Now even `npm i react-swipeable-views@0.13.3`isn't fixing it. I tried clearing the cache too. I get a `Module not found: Error: Can't resolve 'react-swipeable-views-utils'` because i use `{ autoPlay }`

**Comment by aaronwlee** [comment]
> > Looks like we have to continue using 0.13.3 until hopefully 0.13.6 fixes all those recent issues 😢
> 
> I updated to 0.13.5 without reading the issues here.
> 
> 0.13.3 used to work. Now even `npm i react-swipeable-views@0.13.3`isn't fixing it. I tried clearing the cache too. I get a `Module not found: Error: Can't resolve 'react-swipeable-views-utils'` because i use `{ autoPlay }`

Have u try to remove lock file??

**Comment by raduchiriac** [comment]
> Have u try to remove lock file??

I did, no use. 
For those wanting to get back to a working version and they use the `autoPlay`, do this:

`npm i react-swipeable-views@0.13.3 react-swipeable-views-utils@0.13.3 -SE`

**Comment by jeanpoelie** [comment]
> > Have u try to remove lock file??
> 
> I did, no use.
> For those wanting to get back to a working version and they use the `autoPlay`, do this:
> 
> `npm i react-swipeable-views@0.13.3 react-swipeable-views-core@0.13.1 react-swipeable-views-utils@0.13.3 -SE`

Please try 0.13.6 which was released 2 days ago, today i might release a 0.13.7 to fix some dom helper issues that people are having
