### ISSUE TITLE
The `main` field in package.json points to the wrong file.

### ISSUE THREAD

**Issue by daniel-hauser** [oliviertassinari/react-swipeable-views#575]
Inside the package published to npm, the main field in `package.json` points to the wrong file.
It is probably caused by an error in the last publish and not using lerna as it shuled

Closes: #571 
Closes: #573 
Closes: #574 
Closes: #576

**Comment by jeanpoelie** [comment]
Hi daniel,

Thank you for noticing this, i will get right on it!

**Comment by shyam2tayal** [comment]
@jeanpoelie Any fix on this yet, our whole app is crashing due to this issue.

**Comment by jeanpoelie** [comment]
@shyam2tayal for now, please roll back to 0.13.2

npm i react-swipeable-views@0.13.2

**Comment by shyam2tayal** [comment]
I Don't think that available ,
Here is log by npm

`
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-swipeable-views@0.13.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
`

**Comment by jeanpoelie** [comment]
You are right, I made typo:
0.13.3

**Comment by shyam2tayal** [comment]
Yeah i tried that i comes with another issue 
![Screenshot 2020-01-23 at 1 32 11 PM](https://user-images.githubusercontent.com/6690620/72966404-e4e0d880-3de4-11ea-99e4-e26b2750ede5.png)

**Comment by jeanpoelie** [comment]
Hmm, thats odd, 0.13.3 is the last build done by the owner, could you try 0.13.1?

**Comment by divyanshukr96** [comment]
The [main ](https://github.com/oliviertassinari/react-swipeable-views/blob/d48e2ad7df5b18c43a5ef75b212bc18bdb9f6401/package.json#L108)field in `package.json` **not points to the any wrong file.**

Instead of only [react-swipeable-views](https://github.com/oliviertassinari/react-swipeable-views/tree/d48e2ad7df5b18c43a5ef75b212bc18bdb9f6401/packages/react-swipeable-views)  package whole source file of [oliviertassinari/react-swipeable-views](https://github.com/oliviertassinari/react-swipeable-views) has uploaded on NPM

**Comment by valentinvoilean** [comment]
Hi. We have the same problem for `react-swipeable-views-utils@0.13.5`.
The `lib` folder is missing.

**Comment by BerenLuth** [comment]
Same problem here, the only way to make it work again was going back to the version `0.13.3`

**Comment by s4msung** [comment]
Same problem here, have to downgrade to `0.13.3`

**Comment by nikandlv** [comment]
Yeup same!

**Comment by jeanpoelie** [comment]
Hello,

My apologies for all the problems lately with the last couple of packages!
I have finally fixed all the release issues and the newest package `0.13.6` is currently live.
Please let me know if you run into any other issues, I will do some extensive testing this afternoon.

https://www.npmjs.com/package/react-swipeable-views

**Comment by shyam2tayal** [comment]
@jeanpoelie I am having getting issue with dom-helpers , which is required in swipeableViews.js

![Screenshot 2020-01-26 at 5 09 11 PM](https://user-images.githubusercontent.com/6690620/73134617-b110e780-405e-11ea-80cd-98c72f0e974c.png)

**Comment by jeanpoelie** [comment]
I will take a look at this right away!

**Comment by nikandlv** [comment]
`0.13.6` broke because you updated the dom-helpers and that file its trying to compile that `properties` file which does not exist on last version of `dom-helpers`, second issue is even if you manually downgrade the dom-helpers, it compiles however it breaks change of pages
