### ISSUE TITLE
Why are RC tags published under `latest` on npm

### ISSUE THREAD

**Issue by prateekbh** [oliviertassinari/react-swipeable-views#577]
- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
RC tags should not be under `latest` tag on npm

## Current Behavior
RC tags are under `latest` tag on npm

I see that you publish a lot of RC versions on npm. May be these are for trying out things., is there a reason these are not published under `rc/beta/next` tag and are published under default `latest` tag on npm? Are these versions even usable/stable?

**Comment by jeanpoelie** [comment]
Unfortunatly there are some issues publishing from my pc for this project, I can only release using npm publish instead of yarn release.
this has been hunting me for weeks now, I dont own a mac pc to fix the yarn release command.
I have contacted the owner to request for help.

**Comment by prateekbh** [comment]
i guess you can still do `npm publish --tag rc`

**Comment by Rykuno** [comment]
> Unfortunatly there are some issues publishing from my pc for this project, I can only release using npm publish instead of yarn release.
> this has been hunting me for weeks now, I dont own a mac pc to fix the yarn release command.
> I have contacted the owner to request for help.

Really appreciate the efforts put forth. Much love!

**Comment by jeanpoelie** [comment]
> i guess you can still do `npm publish --tag rc`

I will keep this in mind for the next RC release, publishing on NPM is new for me.
i just released 0.13.6 which should resolve the issues from 0.13.3-0.13.5 and include the PR's from the last 2 months.
