### ISSUE TITLE
Module not found: Can't resolve 'dom-helpers/transition/properties' in 

### ISSUE THREAD

**Issue by bouyagas** [oliviertassinari/react-swipeable-views#581]
![image](https://user-images.githubusercontent.com/6065727/73304653-ad0fd180-41e6-11ea-8c78-d67666f7362c.png)

**Comment by wisekaa03** [comment]
I tried to upgrade to 0.13.6, but this problem forced me to roll back to 0.13.3

**Comment by thclark** [comment]
This is surely a duplicate of #566

**Comment by theshashiverma** [comment]
@bouyagas downgrade to 0.12.18 this will work

**Comment by oliviertassinari** [comment]
Duplicate of #564
