### ISSUE TITLE
cannot swipe outside content

### ISSUE THREAD

**Issue by petercutting** [oliviertassinari/react-swipeable-views#590]
I am using SwipeableViews in React in PhoneGap on iOS, Android and Web
I am using updateHeight() and animateHeight to adjust the size of each view to its content - a list. 
This works but there is a problem
If a list is short then there is a lot of empty space between it and the bottom AppBar
Unfortunately this empty space does not swipe
If the list is empty then the user is stuck there

I woulld like the SwipeableView container too fill the available space (between top appbar and bottom appbar) and be swipable anywhere irrespective of the height of any particular list
I am wondering if there is a solution to this

**Comment by SvenWesterlaken** [comment]
Set a `min-height` or use `flex-grow: 1` on `<SwipeableViews>` with the `containerStyle` prop. This way the container has a minimum height and can expand if necessary.
