### ISSUE TITLE
Typo in overscanSlideBefore affecting TypeScript

### ISSUE THREAD

**Issue by andrewleader** [oliviertassinari/react-swipeable-views#593]
In the virtualize component, the `overscanSlideBefore` property has a typo... in the latest NPM package, it's mis-typed as `Slied`

```
    return (
      <VirtualizeSwipeableViews 
      index={this.getIndex()}
      onChangeIndex={(newIndex:any) => this.props.onRelativeIndexChanged(newIndex - start)}
      slideRenderer={this.slideRenderer}
      overscanSlideAfter={1}
      overscanSliedBefore={1}
```

It seems to **only affect typescript**... the types seem to think the property is misspelled, but using the misspelled version doesn't work (throws a console error and property doesn't get applied).

Workaround is to use `any` like follows...

```
    var additionalProps:any = {
      overscanSlideBefore: 1
    };

    return (
      <VirtualizeSwipeableViews 
      index={this.getIndex()}
      onChangeIndex={(newIndex:any) => this.props.onRelativeIndexChanged(newIndex - start)}
      slideRenderer={this.slideRenderer}
      overscanSlideAfter={1}
      {...additionalProps}
      onWheel={this.onWheel}
      onScroll={this.onScroll}
      className={this.props.classes.swipeableViews}/>
    );
```

**Comment by caleb-harrelson** [comment]
The type definitions aren't in this library, they're in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), where this issue was [already fixed](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42796/files).
