### ISSUE TITLE
Different height slides

### ISSUE THREAD

**Issue by zlangbert** [oliviertassinari/react-swipeable-views#6]
This lib is awesome, thanks!

I'm using it with a some slides that have different heights, and all slides end up being the height of the tallest slide. Any ideas about how to get rid of the extra space on the smaller slides?

**Comment by oliviertassinari** [comment]
I'm glad to hear it.

That's weird. Do you confirm that your use case is similare to the third demo?

**Comment by zlangbert** [comment]
Sorry I wasn't clear. I don't want to set a static height on the container and have to scroll. I'd like the container to expand and contract depending on the height of the active slide.

Something like: http://chenglou.me/react-motion/demos/demo4-photo-gallery/

**Comment by oliviertassinari** [comment]
Oh I see what it's you need here.

**Comment by petercutting** [comment]
Each of my slides contains a list <Table>. It took me ages to realise that the longest list defines the scroll behaviour of all of the slides - as a result, a short list can be scrolled completely out of view.
I looked at animateHeight but it seems to have other problems: (1st slide does not initialy display. cpu intensive?. swipe only allowed over content). Is there any way to get sane scroll behaviour?

**Comment by tuomohopia** [comment]
I'm struggling badly with this too. Any workarounds or ways to solve this?

I've found that `animateHeight={true}` prevents almost all of swipe actions.
