### ISSUE TITLE
Waypoint is triggered infinitely inside a slide component

### ISSUE THREAD

**Issue by zephy20** [oliviertassinari/react-swipeable-views#601]
I'm using a waypoint library(https://github.com/civiccc/react-waypoint) in one of my slide components. It has an infinite scroll in both directions(it has overflow). When it mounts, then the waypoint upwards is triggered infinitely which causes fetching data forever even when I haven't scrolled upwards to fetch more data. This is happening ever since I'm using this library. 

Im not able to find the cause or reason for this. Anyone?

**Comment by caleb-harrelson** [comment]
The interaction is with another library and you haven't posted any code so it's hard to say what's going on. If you're still having the issue you could put together a [codesandbox example](https://codesandbox.io) demonstrating the problem.

**Comment by R-Bower** [comment]
FYI in case anyone runs into this problem, you need to set the `scrollableAncestor` prop of the rendered react-waypoint component to a DOM element outside of the swipeable-views container.  I set it to `window`, but this may not work for every use-case.
