### ISSUE TITLE
Can't resolve 'docs/src/modules/components/Pagination' in...

### ISSUE THREAD

**Issue by yysfwls** [oliviertassinari/react-swipeable-views#603]
![image](https://user-images.githubusercontent.com/29426633/85483212-fbd76100-b5f6-11ea-9786-9a1610901862.png)
![image](https://user-images.githubusercontent.com/29426633/85483250-0bef4080-b5f7-11ea-8762-5fb6a83acfd0.png)

**Comment by caleb-harrelson** [comment]
The relevant [demo](https://react-swipeable-views.com/demos/demos/#auto-play) is functional, though it appears you've added code and are running it locally. Since there's not enough info I'm gong to close this, but feel free to provide more info or ask a question in a new issue.

**Comment by villerdex** [comment]
@caleb-harrelson how do we exactly add the pagination component then?
