### ISSUE TITLE
[type] Rename api `action` 

### ISSUE THREAD

**Issue by kodai3** [oliviertassinari/react-swipeable-views#615]
## Expected Behavior

rename `action` props

(maybe `actionCallbacks`?)

## Current Behavior

React.HTMLProps has `action?: string` prop
we have `action?: (hooks: SwipeableViewsHooks) => void` prop (which is missing in current type definitions https://github.com/oliviertassinari/react-swipeable-views/issues/545)

**Comment by caleb-harrelson** [comment]
If you'd like to throw a PR together for this I can review and merge it.

**Comment by oliviertassinari** [comment]
It can be fixed in the types
