### ISSUE TITLE
 [Feature Request] could we move react-swipeable-views-native into react-swipeable-views ?

### ISSUE THREAD

**Issue by KingAmo** [oliviertassinari/react-swipeable-views#623]
## Expected Behavior
we could have `index.native.js` and `index.js` that have the two implementation , and when run in `react-native`, `index.native.js` will be used, and when run in react-native-web or react, `index.js` will be used
## Current Behavior

Currently we need to install two package and import from to package, when you use `react-native` and `react-native-web` together, it is very inconvenient

**Comment by caleb-harrelson** [comment]
The react-native implementation is experimental and not supported (not that the rest of the package is very supported anymore either...) so I don't think moving it to be better integrated would be sending the right message.
