### ISSUE TITLE
Range Input not working properly inside a swipeable-view

### ISSUE THREAD

**Issue by ashkanahrabi** [oliviertassinari/react-swipeable-views#634]
- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Range Input inside a swipeable view is not working properly!
This happens on both touch and mouse events while the user is sliding the input thumb. 

## Steps to Reproduce (for bugs)

This codesandbox.io template:
    https://codesandbox.io/s/confident-bogdan-u33up
    

## Context
As you can see in the template, when user tries to swipe the input thumb, nothing happens!
This issue is not seen when the swipeable view is disabled.

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |        0.13.9 |
| React                  |       16.13.1  |
| platform               |       macOS Big Sur (Chrome version 87.0), iOS 14 (Safari)  |
| etc                    |         |

**Comment by manmal** [comment]
@ashkanahrab Have you found a solution that works on all devices in the meantime?

Wrapping the slider like this works for me on __desktop__ Chrome: 
```tsx
<div
 onMouseDown={(e) => e.stopPropagation()}
 onMouseUp={(e) => e.stopPropagation()}
 ><Range .../></div>
```

But I haven't managed to get this to work on touch devices 🙁 
Even with this kinda desperate attempt, no chance - dragging the slider always moves the swipeable container:
```tsx
<div
    onMouseDown={(e) => e.stopPropagation()}
    onMouseUp={(e) => e.stopPropagation()}
    onMouseMove={(e) => e.stopPropagation()}
    onTouchMove={(e) => e.stopPropagation()}
    onTouchStart={(e) => e.stopPropagation()}
    onTouchStartCapture={(e) => e.stopPropagation()}
    onTouchEndCapture={(e) => e.stopPropagation()}
    onTouchEnd={(e) => e.stopPropagation()}
    onTouchCancel={(e) => e.stopPropagation()}
><Range ... /></div>
```

**Comment by ashkanahrabi** [comment]
@manmal Unfortunately I couldn't find a way. As you mentioned, dragging everything inside the swipeable, moves the swipeable view too.

I'm closing this cause I think it's the normal behavior of swipeable views.
