### ISSUE TITLE
Swipe is not working on mozilla

### ISSUE THREAD

**Issue by prashan9775** [oliviertassinari/react-swipeable-views#65]
I used this library with material ui tabs. It is working fine in chrome and safari but it is not working on mozilla. When i try to swipe the pages on mozilla they start sliding.

material ui link -- >http://www.material-ui.com/#/components/tabs

**Comment by oliviertassinari** [comment]
It's working fine on Firefox v46.0. What version are you using?

**Comment by prashan9775** [comment]
Hi oliver,

Firefox version is 46 only . I tested for this link -->
http://www.material-ui.com/#/components/tabs

PFA with the mail.

On Wed, May 4, 2016 at 10:50 PM, Olivier Tassinari <notifications@github.com

**Comment by prashan9775** [comment]
Firefox version is 46 only.

![screenshot_2016-05-05-18-00-11](https://cloud.githubusercontent.com/assets/16535928/15044318/8766e022-12f1-11e6-8f98-4235f9a84354.png)
![screenshot_2016-05-05-18-01-25](https://cloud.githubusercontent.com/assets/16535928/15044319/876d4926-12f1-11e6-8b3a-86f168f0b280.png)

**Comment by oliviertassinari** [comment]
I'm closing the issue as I don't have enough information to reproduce the issue.
