### ISSUE TITLE
Peer dependency for React 16

### ISSUE THREAD

**Issue by mcqj** [oliviertassinari/react-swipeable-views#657]
There is a dependency in react-swipeable-views-utils on react-event-listener. react-event-listener has been archived and has a peer dependency on react@^16.3.0. This leads to warnings when installing. I have not encountered runtime errors as a result.

At some stage, react-event-listener should be replaced, unless it can be unarchived to update its peer dependency.

**Comment by oliviertassinari** [comment]
Duplicate of #663
