### ISSUE TITLE
Update to be used along with react 18

### ISSUE THREAD

**Issue by michalstrzelecki** [oliviertassinari/react-swipeable-views#663]

**Comment by JustonJ99** [comment]
upvote

**Comment by progdog-ru** [comment]
Please, update it 🙏

**Comment by michalstrzelecki** [comment]
Is it a legacy package?

Please update its dependencies.

I want to use it with react 18.

**Comment by kvintanaka** [comment]
This package is mentioned in a demo for Material UI (MUI) here: https://mui.com/material-ui/react-stepper#text-with-carousel-effect, and several other popular apps.

So, upvote for React 18!

**Comment by codelikepro22** [comment]
Any update?

**Comment by aviyi** [comment]
Any update?

**Comment by jacobdmn** [comment]
Any updates guuuuys??

**Comment by jacobdmn** [comment]
🟢 a solution that might help: 
===> ADD --legacy-peer-deps to your building command in your workflow !
https://stackoverflow.com/questions/66020820/npm-when-to-use-force-and-legacy-peer-deps/66035709#66035709

**Comment by aviyi** [comment]
Any updates?

**Comment by Mishhub** [comment]
Is it a legacy package?!
I'm getting dependency errors in react 18!

**Comment by codelikepro22** [comment]
react-swipeable-views is a nice package but it is not working with React18, so we replaced it with new package on this tutorial video:
https://www.youtube.com/watch?v=n0Rl-SsTVKc&feature=youtu.be

**Comment by progdog-ru** [comment]
> react-swipeable-views is a nice package but it is not working with React18, so we replaced it with new package on this tutorial video: https://www.youtube.com/watch?v=n0Rl-SsTVKc&feature=youtu.be

love you!

**Comment by skrln** [comment]
Someone made a PR to make it React18 compatible, but it hasn't been merged yet. Let's go upvote that PR!

https://github.com/oliviertassinari/react-swipeable-views/pull/668

**Comment by dc198689** [comment]
Oh my god, I am stuck at this issue ...
@oliviertassinari , any idea ?

**Comment by BenoitEirik** [comment]
Tip: Here's what you can do while you wait:
1. Download https://github.com/ramsesndame237/react-swipeable-views/tree/master/packages/react-swipeable-views folder and place it somewhere in your project
2. Do `npm install your-path/react-swipeable-views`
4. Import like this: `import SwipeableViews from 'your-path/react-swipeable-views/src';`

**Comment by samislam** [comment]
It's 5 months and the package isn't supporting react 18 yet.

**Comment by aash-hepta** [comment]
upvote

**Comment by color4pen** [comment]
upvote

**Comment by christopher-caldwell** [comment]
This package is no longer being maintained, it seems.

**Comment by johnpaulmarino** [comment]
my friends. Is there any solution to this?

**Comment by dyaa** [comment]
My 1¢ option, This repo should be archived and we should look for a replacement that's still maintained and work with React@18.*

**Comment by codelikepro22** [comment]
> https://www.youtube.com/watch?v=n0Rl-SsTVKc&feature=youtu.be

**Comment by oliviertassinari** [comment]
I'm closing as fixing this issue a non-goal per https://github.com/oliviertassinari/react-swipeable-views/issues/676

**Comment by acamara2016** [comment]
sad ending 😢

**Comment by sunil-well** [comment]
any solution yet ?

**Comment by acamara2016** [comment]
I ended up using this library. https://www.npmjs.com/package/react-slick

**Comment by younglecturer7** [comment]
Please someone should help me with any available packages that I can use in replace of react swipeable view for react 18. Thanks
