### ISSUE TITLE
Will not install with react 18.2.0

### ISSUE THREAD

**Issue by AdamPhasey** [oliviertassinari/react-swipeable-views#672]
Tried to install but will not accept 18.2.0. Do you have plans to upgrade its compatibility?

- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |         |
| React                  |         |
| platform               |         |
| etc                    |         |

**Comment by askunlimited** [comment]
having the same issue trying to install on react 18.2.0 but giving could not resolve dependency error. Is there a hack or a compatibility upgrade in sight?

**Comment by nnmax** [comment]
same issue

**Comment by tahola** [comment]
up, same here

**Comment by tahola** [comment]
Same issue, I added a --force to npm, it seem to work fine...

`npm install --force --save react-swipeable-views`

**Comment by oliviertassinari** [comment]
Duplicate of #663
