### ISSUE TITLE
Regression: index in OnChangeIndex is sometimes undefined

### ISSUE THREAD

**Issue by hannesj** [oliviertassinari/react-swipeable-views#95]
This broke when upgrading from 0.5.4 to 0.6.0

It seems the culprit is [here](https://github.com/oliviertassinari/react-swipeable-views/compare/v0.5.4...v0.6.0#diff-fb00d0b037b3caf7a015eac7e03a3593R214), where this.indexLatest can be undefined.

**Comment by oliviertassinari** [comment]
At first glance, this change seems safe. Who could I reproduce this issue?

**Comment by hannesj** [comment]
For those two versions to be eqvivalent, shouldn't [this](https://github.com/oliviertassinari/react-swipeable-views/blob/master/src/SwipeableViews.js#L212) row be `const indexStart = this.indexStart;` instead of `const indexStart = this.indexLatest;`, as this.indexLatest is not initialized anywhere before. 

I'll try to do a small codepen of this tomorrow.

**Comment by oliviertassinari** [comment]
Oh, you are right. I'm gonna fix this.
